### ISSUE TITLE
Make your icon a little bit larger

### ISSUE THREAD

**Issue by FawayTT** [BrowserWorks/waterfox#102]
Hello, I just have a really small "bug" with your project. Personally, I really like your logo/icon what you actually have, but it's the 16x16 version on my taskbar is a little smaller than other 16x16 icons of programs. So, my suggestion would be to use full space of 16x16 area for the icon. And yes, I'm an perfectionist.

**Comment by MrAlex94** [comment]
I'll make sure to get this remedied 🙂

**Comment by MrAlex94** [comment]
Should be resolved now as I've update the branding icons a while ago 🙂

**Comment by eanon** [comment]
Hello, Old thread, but since I experience the same in my Windows 7's task bar on 2017, I add my message here. Just see the attachment (icon -- the one between Foobar and Firefox -- is smaller than the other ones and not very distinguishable).

![snap_0005141](https://user-images.githubusercontent.com/6631714/33516858-e91a23bc-d779-11e7-87f7-923daf4600d4.png)
