### ISSUE TITLE
WF 56.2.11: Text cursor not displayed on specific site

### ISSUE THREAD

**Issue by terrypin999** [BrowserWorks/waterfox#1049]
I go this site
[https://forum.allaboutcircuits.com/](url)
If I try to write a new post or reply to an existing one, in any of the forums, I fail, because the text cursor does not appear in the message box.

I have to switch to another browser such as Chrome, Edge **or Firefox 52**.

No other sites I've tried give me the same problem. I've emailed the site administrator but no response so far.

Of course, this may be impossible for others to reproduce as  it requires logging in.

I'm using Windows 10, version 1803 (OS Build 17134.829)

**Comment by terrypin999** [comment]
Before seeing this thread a few minutes ago I posted about a similar issue here: 
[https://github.com/MrAlex94/Waterfox/issues/1049](url)

In my case, clicking outside WF did not resolve it.

Interestingly, when I came to post **here**, the text cursor was AWOL and clicking elsewhere and returning caused its return. Possibly an unrelated issue?

**Comment by hawkeye116477** [comment]
So that will require registering on that forum.
Install mozregression tool https://mozilla.github.io/mozregression/install.html, then run bisection, check to search for bug fix and choose some range, for example as last bad => FF 56 and last good FF 60 and test till you'll find last bad and last good, then write results with link to pushlog, similarly as I did on `https://github.com/MrAlex94/Waterfox/issues/1066#issuecomment-536187366`

**Comment by hawkeye116477** [comment]
Is that works good now?
