### ISSUE TITLE
Request: Add support for KeePassXC-Browser

### ISSUE THREAD

**Issue by AsukaLangleyfag** [BrowserWorks/waterfox#1095]
Sorta copy of [#1084]
KeePassXC-Browser can be fixed on linux if you follow https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide but it doesn't on windows. I looked in source and it's still `Software\Mozilla\NativeMessagingHosts` so i have no clue why it doesn't work, it does work with current firefox.

**Comment by AsukaLangleyfag** [comment]
Nevermind looks like my base decided to turn off integration for some reason, it still does work on windows.

**Comment by damajor** [comment]
Please re-open, I am running latest Waterfox current at this date.
KeepassXC-browser extension is not working. Troubleshooting from KeepassXC devs does not help :(
Something related to native messaging hosts that prevent the keepassxc-proxy.exe to be loaded by Waterfox.

**Comment by FranzGotsis** [comment]
Here is a "manual" solution for waterfox  that is not as nice as a native support. 

You need a working firefox installed for that. On Linux (my Systems are running on OpenSuse Leap 15.4 and Ubunto 22.04 and on RedHat) you then copy the file org.keepassxc.keepassxc_browser.json
from /home/<user name>/.mozilla/native-messaging-hosts/
 to
/home/<user name>/.waterfox/<your profile>/

The name of the active profile directory can be found using opening the page "about:profile" in the browser (that works on  computers with a Microsoft OS as well - I have not tested on apple).

I have tested that with waterfox G4.5, G5.0.1, G5.1 and G5.1.1.

You can create the file using the following  content

{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}

give it the name "org.keepassxc.keepassxc_browser.json"
and save it in the directory
/home/<user name>/.waterfox/<your profile>/
(that spares you installing firefox first).

Actually  - as can be seen from the file content - it is pretty simple to support waterfox in KeePassXC but the team has rejected that (up to now - refer to issue 1594 - https://github.com/keepassxreboot/keepassxc/issues/1594, comment from  phoerious commented Mar 1, 2018 ).

Oh and beware: Before the first connection the keepassxc program asks for permission to grant the new client access to the password store. Unless you grant that permission the browser just sees that it is unable to connect to the password database.

I find KeePassXC quite nice and featureful and runs indeed on various platforms (including Android and Apple I-Phones) so that it is a nice alternative for a large variety of platforms in security sensitive areas (as mine is). Restricting the allowed devices works only if you can force a user to use specific hardware and even then they will constantly try to bypass your restrictions. I found it time saving to offer alternatives when it is possible with a reasonable effort.
BTW: Waterfox is being used on the computers we are managing because it allowed legacy add-ons to keep working and because it really and reasonably easily allows to stop siphoning information to third parties.

**Comment by awsdert** [comment]
To add to the previous user's post, here's a more convenient way of making the file, the file itself :)
[org.keepassxc.keepassxc_browser.json](https://github.com/user-attachments/files/21249546/org.keepassxc.keepassxc_browser.json)
