### ISSUE TITLE
Youtube 1440p playback

### ISSUE THREAD

**Issue by b1k3rdude** [BrowserWorks/waterfox#1101]
**Describe the bug**
Play full screen at anything higher than 1080p60 results in a freezes of the video playback while the audio continues with the video kicking back in later.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.youtube.com/watch?time_continue=1&v=68uUeZGppXw
2. Play the video full-screen @ 1440p
3. the video will free 2-3 times.

**Expected behaviour**
see description.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - August security patch.

**Additional context**
Playing the same video at the same res. full-screen in chrome v76 works flawlessly.

**Comment by SenpaiSharp** [comment]
I have never tested Youtube video against Chrome, as I could not be bothered to install it but I have the same issue with 4K60 on **all** of Firefox's cousins. I have a video card that is more than capable of running such content and indeed, I can run such videos in MPC with my card barely teetering into fan running territory on a hot summer day. On Youtube, such videos will get always get the fans running and I will get a lot of stutters and freezes.

1440p has never given me any issue though and since we have the same environment, I am going to guess your video card is a bit below mine. If your drivers have a power efficiency mode enabled, you could see if disabling that might give you a bit of help. I kind of doubt it will though, I think this is ultimately a some sort of heavy performance *Fox tax that has to do with how they render videos.
