### ISSUE TITLE
Request: privacy-related addons and settings

### ISSUE THREAD

**Issue by gloschtla** [BrowserWorks/waterfox#1174]
It would be nice, if the newly installed waterfox shows the user some highly recommended methods to protect your privacy. For example: DNS over TLS (settings), block DNS leaks (about:config), HTTPS everywhere (addon), Decentraleyes, and [more listed by mozillla](https://addons.mozilla.org/en-US/firefox/search/?recommended=true&sort=rating&type=extension).

**Comment by grahamperrin** [comment]
Also: 

- [Firefox better for privacy than Waterfox? · Issue #920 …](https://github.com/MrAlex94/Waterfox/issues/920)

> if the newly installed waterfox shows the user some highly recommended methods to protect your privacy. 

With respect, 

:-1: 

– because there's already automated presentation of the blog post for the installed version of the application, and some users view this as intrusive (and automated presentation of _any_ additional page might be viewed as doubly intrusive, and so on). 

Also because recommendations can be surprisingly contentious. 

For recommendations, and discussion of recommendations, the support area is probably ideal. Things there can be pinned, or can naturally gain popularity. 

> listed by mozillla.

Related: [Collecting your thoughts about Manivest V3 and the Recommended Extensions program - Add-ons / Development - Mozilla Discourse](https://discourse.mozilla.org/t/collecting-your-thoughts-about-manivest-v3-and-the-recommended-extensions-program/45846?u=grahamperrin)
