### ISSUE TITLE
Unable to join Discord Web voice

### ISSUE THREAD

**Issue by iGlitch** [BrowserWorks/waterfox#137]
Cloning the Netflix useragent and replacing it with general.useragent.override.discordapp.com makes Discord Web voice calls usable again.

**Comment by MrAlex94** [comment]
Ah I'll add that in for you :-)

**Comment by Scrxtchy** [comment]
#133 is the fix
interestingly enough, discord support got back to me today, a week since I sent them my report

>IcyPebbles (Discord) 
Apr 3, 05:53 PDT 
Hey Scratch, 
Glad to hear it! Did it help with your issue? 
Cheers,
IcyPebbles
We have a tweet tooth. Hit us up on Twitter for real-time support: https://twitter.com/discordapp

:-1: 
didn't even acknowledge that not only had I identified the problem, but also given them a working solution for it

**Comment by MrAlex94** [comment]
Should be fixed now.
