### ISSUE TITLE
Is it possible to remove Google Analytics from about:addons?

### ISSUE THREAD

**Issue by De4th69** [BrowserWorks/waterfox#172]
Seems like Mozilla added Google Analytics to about:addons without saying anything. Would it be possible for you to remove it, without breaking anything? 

There's a bug open on their Github page: https://github.com/mozilla/addons/issues/3145

**Comment by azettl** [comment]
As Waterfox is also only loading the discovery page from mozilla (discovery.addons.mozilla.org) i guess it will not be possible, except if the whole discovery page gets replaced or mozilla removes the google analytics part?

**Comment by WagnerGMD** [comment]
![pageaboutaddons_umatrixrules](https://user-images.githubusercontent.com/11284493/28131938-b3b004d4-673b-11e7-96e6-bf59a216419f.png)
**At the end** (and just to mention it), you might find one solution with an addon like Umatrix (see the picture above). Because you can remove the page (by default) in the whitelist (check **matrix-off**) and define (or create) your own rules.

**PS :** Sorry I had forgot a warning. Then for the moment, I won't advice "uMatrix.webext.xpi" (only the Umatrix **WebExtensions** and in the case, yes I had try a few times). Don't try to install it because the addon won't work (or I will assume isn't compatible with Waterfox_v54.0.0.1).

**Comment by Xinayder** [comment]
Maybe Waterfox could block the request to GA by default on the addon discovery page.

**Comment by De4th69** [comment]
Ok so blocking it is the way to go. I'm curious if they will remove it.

edit: https://news.ycombinator.com/item?id=14753546

**Comment by WagnerGMD** [comment]
>  [...] you have send data about me to Google. Without my consent. 
> Please don't hide behind technical details. (or I would rather say a false excuse)
> -- <cite>[TekMol][1]</cite>

[1]:https://news.ycombinator.com/item?id=14755633

I had check today again and as you can see in these pictures :
- http://nsa37.casimages.com/img/2017/07/13/170713022357195367.png
- http://nsa37.casimages.com/img/2017/07/13/170713022356953929.png

I think that we can say the same thing about Disqus (Facebook, etc) . Because a few weeks ago, I had discover the same kind of trouble with the addon [Referer Control](https://addons.mozilla.org/en-US/firefox/addon/referercontrol/). Perhaps it isn't the only one ?

**PS :** Good luck with the Google Recaptcha because no it's doesn't work... Specially if you want to post a review (or report ? or report abuse ? etc) on the website [addons.mozilla.org](https://addons.mozilla.org).
Any news about the [issue n°167](https://github.com/MrAlex94/Waterfox/issues/167) ?

**Comment by MrAlex94** [comment]
Definitely looking into this. Will probably add some JavaScript [here](https://github.com/MrAlex94/Waterfox/blob/master/toolkit/mozapps/extensions/content/extensions.js) to block any requests to Google. (Unless Mozilla change this server side?)

What do you all think?

**Comment by De4th69** [comment]
That would be great! Seems like there's also some stuff loaded from Facebook and more if I read the second picture from @WagnerGMD correctly. Would be great if that could be killed too.

Thank you for your great work!

**Comment by WagnerGMD** [comment]
In fact, I wanted to add also a warning about the addons. Because after the installation, you might discover a bad surprise.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/d3e9b4534ab9069eb661097e3aff896ef6ada0f5 solves this problem 🙂

**Comment by WagnerGMD** [comment]
It's sound to be good (according to [this picture](http://nsa37.casimages.com/img/2017/07/17/170717015212183117.png)).

**PS :** There is very little one improvement with the Umatrix **WebExtensions**. But my advice will remain to avoid it (buggy).

**Comment by unepyc** [comment]
@MrAlex94 
According to [this issue comment](https://github.com/mozilla/addons/issues/3145) Mozilla does not use Google Analytics any longer if the Do Not Track setting is enabled. However, I guess, it can't be wrong to watch out for other connections to Google in future versions of Firefox.
