### ISSUE TITLE
[Feature Request] Add support for Gopher Protocol

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#182]
Firefox stopped being compatible with it a long time ago.

**Comment by grahamperrin** [comment]
FYI [OverbiteWX](https://addons.mozilla.org/addon/overbitewx/)

**Comment by ghost** [comment]
Seriously? -_-
This should not be part of the core browser. It's the job for an addon.

OverbiteWX is a webextension and uses a website to function.

overbiteff is a classic addon, it works on it's own. Didn't tested it.

on classic addon archive
caa:addon/overbiteff

**Comment by hook321** [comment]
Hi! I'm surprised someone went back to issues this old. At some point FTP will stop being common, when that comes and Mozilla likely removes support for it in Firefox I don't think people will be saying the same thing.

**Comment by ghost** [comment]
I was looking for old issues that could be closed.... You may want to close your own issue? XD lol

You are over extrapolating the addon removal fiasco. They removed them, because they thought they will be able to compete against chrome with a faster browser. It's not some removal fetish.

The whole point of powerful addons is to extend the browser. gopher is almost never used now days, to be supported in an addon makes more sense at this time.... You disagree with that logic? Obsolete stuff should be supported by addons.  We could imagine a future where ftp ends up supported by an addon..... If adobe open sources flash, should it be integrated in the browser? What about all these flash games and flash only sites???

Have you tested overbiteff ? It's no good?
