### ISSUE TITLE
Multiprocess Windows disabled on WF v55.0.2!

### ISSUE THREAD

**Issue by tonialb** [BrowserWorks/waterfox#188]
Hi,

Just updated Waterfox on v55.0.2. But I found disabled the Multiprocess Windows on Troubleshooting Information. Tried to relaunch  the browser without addons. Also, I created a new fresh profile. On both scenarios multi-process remain disabled!

Do you guys have the same problem or its just my browser? Does it create any problem if I turn it ON manually?

thanks

**Comment by tonialb** [comment]
It seems that e10s is not enabled by default, on this version of Waterfox. Tested a fresh copy in another computer.

**Comment by WagnerGMD** [comment]
```
## For the record, (on the page about:config) it could be related to these settings :
pref("browser.tabs.remote.autostart",true);
pref("browser.tabs.remote.autostart.2",true);
pref("browser.tabs.remote.force-enable",true);
pref("accessibility.force_disabled",1);
pref("dom.ipc.processCount",1);
pref("dom.ipc.processCount.web",1);
## The value of processCount might be altered (don't trust)...
## Because there is one trouble related to accessibility tools.
pref("extensions.e10sBlockedByAddons",false);
pref("extensions.e10sBlocksEnabling",false);
pref("extensions.e10sMultiBlockedByAddons",false);
pref("extensions.e10sMultiBlocksEnabling",false);
## Multi-process staged rollout	--->	e10srollout@mozilla.org_v2.0.xpi
## Download Waterfox then extract it (with 7zip, etc) and follow this path = "Waterfox 55.0.2 Setup\core\browser\features"
```
Hi,

no you're not alone because I have the same problem (it seem's to be disable). But in fact I start to believe **Waterfox_v55** (from this [reddit topic](https://www.reddit.com/r/waterfox/comments/6trq5j/test_out_waterfox_55_here_please_read_full/) too) doesn't come with [Electrolysis](https://wiki.mozilla.org/Electrolysis)...
Because I didn't find the file `e10srollout@mozilla.org.xpi` (inside the folder called **features**). And on the page **about:support**, I didn't find the next line (**Web Content Processes**) just after **Multiprocess Windows**.

![frozenbuttonmultiprocess_browserwaterfox_v55](https://user-images.githubusercontent.com/11284493/29575476-e5d4967a-8764-11e7-8351-6f79118582e1.png)

As you can see (on the picture), another way exist (at the bottom) : **about:preferences#general**. At least it's true with Firefox...
Because the button **Content processes limit** doesn't work.
At first (don't forget), you will need to uncheck (the box) : **Use recommended performance settings**.

**Comment by tonialb** [comment]
Yes, e10srollout@mozilla.org.xpi is missing. That's the reason why was not enabled. I fixed that using the file "prefs.js" from the old Waterfox 54. Its working fine. :)

Thanks for the help

**Comment by WagnerGMD** [comment]
You're welcome @tonialb and that's right, it's seem we still can enable it. Nevertheless, once it's done, it will work has expected ?
One good point about **e10s**, it's seem the way to follow to avoid an huge amount of RAM (>1 Go). Once it's reach, the browser is **very laggy** and didn't want to clear (the RAM) until the next browser reboot.
I didn't see this leak (or huge amount) of memory with Firefox (and (at the contrary) the trouble seem's to concern Cyberfox; because I suppose it was never fixed...). So it's sound to be bad idea to not activate **e10s** by default.

**PS :** To check, you just need to play one very long (about a few hours) video on youtube (or another website in HTML5).

**Comment by grahamperrin** [comment]
As things have changed more than once with releases of 56, I suggest closing this issue.
