### ISSUE TITLE
download waterfox 54 for Linux?

### ISSUE THREAD

**Issue by galstudio** [BrowserWorks/waterfox#190]
Where can I download waterfox 54? And then the 55 version for Linux is quite problematic

**Comment by hawkeye116477** [comment]
@galstudio Why is it quite problematic? What problems you have?
You can download 54 from here: https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-54.0.1.en-US.linux-x86_64.tar.bz2

**Comment by galstudio** [comment]
The problem is as follows:
https://github.com/MrAlex94/Waterfox/issues/186#issue-251246122

But to install or update this instruction  I do not see the point https://www.reddit.com/r/waterfox/comments/6u4cur/waterfox_55_do_not_work_on_linux_mint_182/dls0062/

 Installation and startup Firefox 55 went without problems, I do not understand why the waterfox issues an error.

Thanks for the link.

**Comment by hawkeye116477** [comment]
@galstudio 

>  I do not understand why the waterfox issues an error.
Latest Waterfox was probably compiled with little newer libstdc++. 

You can also install Waterfox 55 from my repo: https://hawkeye116477.github.io/waterfox-deb/, just do method 2, install waterfox from my repo and newer libstdc++ should be installed automatically, because I included it in my repo.  I only added what is only needed, no full repo and I took lib from: https://launchpad.net/ubuntu/yakkety/, but should be working on xenial and maybe others Ubuntu.

**Comment by galstudio** [comment]
After installation from repo: https://hawkeye116477.github.io/waterfox-deb/ will there be problems with the system?

**Comment by hawkeye116477** [comment]
@galstudio No, I uploaded the oldest lib as exist, which works with Waterfox, so all should be fine. It even older than I have on Manjaro Linux (branch stable), I have 7.1.1, ppa/ubuntu-toolchain-r/test has 7.2, on my repo it's 6.2. **I checked on Mint 18.2 KDE and Cinnamon and all is fine.**

Update: I removed libstdc++ from repo and new version of waterfox and waterfox-kde with fixed issue of libstdc++ is on my repo now,
