### ISSUE TITLE
Fire and water Fox 

### ISSUE THREAD

**Issue by lennynld** [BrowserWorks/waterfox#21]
Fire and water can't be active at the same time

**Comment by p-schneider** [comment]
The same Firefox Profile cannot be used at the same time. In order to get Firefox and Waterfox run side by side you have to tell one of the two to use a different Profile (-P) and you have to tell it not to try to reuse the existing instance (-no-remote).
You can start firefox or waterfox with the -ProfileManager parameter to set up a new profile.

(Quote from #14:)
You can set Waterox to use a different profile with -p -no-remote on its shortcut.
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
http://kb.mozillazine.org/Command_line_arguments

**Comment by danpe91** [comment]
Also you could modify the shortcuts so it executes by default with those parameters and you do not have to open it from command line
