### ISSUE TITLE
Waterfox  and old firefox api

### ISSUE THREAD

**Issue by nyancat18** [BrowserWorks/waterfox#215]
Hi

sorry for ask you this question.

But  i want know if  Waterfox will support the old firefox addon api?

*or it will reject this* **just like firefox**

**Comment by criztovyl** [comment]
afaik the old api will still be supported.

**Comment by nyancat18** [comment]
@criztovyl i tak about waterfox 57+ :+1:

**Comment by MrAlex94** [comment]
The plan is to keep add-ons running for now. I'm currently looking into creating experimental WebExtension APIs, so port the old add-on APIs so developers can then move forward that way :-)

**Comment by juneyourtech** [comment]
@MrAlex94 There are certain XUL-based extensions that only run with XUL. If both XUL and WebExtensions could be supported simultaneously, and for (far) longer than Firefox does, then this would allow for a more graceful transition than what moz://a are doing right now.

**Comment by nyancat18** [comment]
@juneyourtech   its exactyle what i want *i depend of   RAS*

and ras authos hate new api :(

**Comment by Ulf3000** [comment]
you can still write plain bootstrapped addons for ff quantum (57+) ...

we should just port the best old addons to bootstrapped addons and have a solution which works in ff nightly(and waterfox quantum) for the foreseeable future

porting back in the sdk will be probably too hard i tell you that now .. 

and xul addons still work !!!  .. but since ff57+ uses a different browser.xul some of those addons just cant find the elements they are supposed to modify and sometimes theres problems which must be replaced by promise and multithreading solution

**Comment by grahamperrin** [comment]
> … looking into creating experimental WebExtension APIs, so port the old add-on APIs …

You might like to follow Mozilla bug [1215059 - (webextensions-additional-apis) [meta] Extend WebExtensions with custom APIs so more legacy add-ons can be ported](https://bugzilla.mozilla.org/show_bug.cgi?id=1215059).

**Comment by grahamperrin** [comment]
@captnfab hi, re: your <https://github.com/captnfab/FireTitle/>, this month's decision at <https://bugzilla.mozilla.org/show_bug.cgi?id=1396010#a13659144_582971> (the title of that bug probably was _not_ a good fit for some of what was discussed) and last year's <https://github.com/MrAlex94/Waterfox/issues/215#issuecomment-330824190> above: 

- if there could be a Waterfox implementation of a WebExtensions API for what's required, how would you summarise that API?

TIA

----

(A 'Waterfox implementation' of an API, to complement [Mozilla's implementation](https://wiki.mozilla.org/WebExtensions) of WebExtensions APIs. A superset of sorts.)
