### ISSUE TITLE
Handle unboxed arrays in jsarray.cpp fast paths {part 2}

### ISSUE THREAD

**Issue by nixiValor** [BrowserWorks/waterfox#22]
this thread is in relation to https://github.com/MrAlex94/Waterfox/issues/20

the current modifications to

```
js/src/builtin/SMID.cpp
js/src/gc/Marking.cpp
js/src/gc/Nursery.cpp
js/src/gc/Nursery.h
js/src/jit/EffectiveAddressAnalysis.h
js/src/jit/jitcodeMap.cpp
js/src/vm/debugger.h
js/src/vm/ReceiverGuard.cpp

Below are few examples of changes in watefox not in firefox relative to bug 1163091
js/src/builtin/SMID.cpp
line 19 ++ #include "jsprf.h"

js/src/gc/Marking.cpp
line 42 ++ using mozilla::PodCopy;
line 43 ++ using mozilla::PodZero;

js/src/jit/EffectiveAddressAnalysis.h
line 10 ++ #include "jit/MIRGenerator.h"

js/src/jit/jitcodeMap.cpp
line 1555 ++ JS::ForEachProfiledFrameOp::FrameHandle::FrameHandle(JSRuntime* rt, js::jit::JitcodeGlobalEntry& entry,

js/src/vm/ReceiverGuard.cpp
line 7 ++ #include "builtin/TypedObject.h"
line 8 -
line 11 ++ using namespace js;

```

say otherwise & the changes in the files are not present in firefox 40.0.3 branch when running a diff of waterfox 40.0.3 & firefox.40.0.3 branch.

you have https://github.com/MrAlex94/Waterfox/tree/master/intl/icu the whole tree version different to firefox even firefox nightly which is testing the next safe branch of icu.

there are many changes visible when running a diff of current git branch of waterfox & firefox 40.0.3 did you use or do you use the same code i this git repository for the browser builds you release. if not where can i find its code.

**Comment by MrAlex94** [comment]
These aren't issues. These are patches _required_ to get Intel's C++ compiler to compile. Please stop posting issues unless they're actually _issues_. Download Firefox and compile for yourself with Intel's compiler, you'll run into the exact same issues that I've added these modifications to get a working build. 

Waterfox is made to be compiled with ICL and that's it.

And I've updated ICU because the bug for updating it has gotten old. ICU is a few stable versions ahead. I don't understand your questions, this is what Waterfox has been built on. A quick google search and you'd find the latest ICU release is the same as Waterfox's whereas Firefox's is out of date: http://icu-project.org/apiref/icu4c/

Unless you're posting an issue, please don't use Github issue system for questions, message me directly on somewhere like reddit or here. 

I'm not sure if you're understanding what Waterfox is? Of course there are going to be differences to the Firefox source code, that's what Waterfox IS, a fork of Firefox.
