### ISSUE TITLE
ubuntu 17.04 mozconfig  redirection error

### ISSUE THREAD

**Issue by kuh3h3** [BrowserWorks/waterfox#227]
ubuntu /bin/sh is not /bin/bash`s symbolic link.
rather /bin/dash`s symblic link.

so current  .mozconfig`s  this redirection not work in /bin/dash.

X=$(bc <<< "1.5*$(getconf _NPROCESSORS_ONLN)")
mk_add_options MOZ_MAKE_FLAGS=-j${X%.*}

i deleted that  redirection line and add j2 directly.

mk_add_options MOZ_MAKE_FLAGS=-j2

**Comment by hawkeye116477** [comment]
@kuh3h3 7.04 really, have you that old Ubuntu? I hope that you made mistake and should be rather 17.0.4.

**Comment by kuh3h3** [comment]
sorry mistype .you are  right. 17.04

**Comment by laniakea64** [comment]
Ubuntu 17.04 is now dead, and Waterfox's `.mozconfig` doesn't have the stated code in it since https://github.com/MrAlex94/Waterfox/commit/c4a9f63b94876aa8af064379cc35ec750fe18671.  I build Waterfox in Xubuntu 16.04, which also uses `dash` as `sh`, and haven't seen this issue.

Is this issue still present in current Waterfox in Ubuntu 18.04?

**Comment by MrAlex94** [comment]
It has been a while, please re-open if you have issues with it.
