### ISSUE TITLE
on linux it should be .config/waterfox

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#243]
On linux, there's a convention for quite some time that you put your config stuff in .config/myprogram instead of .myprogram.

Firefox is very old, what 17 years old now? That convention didn't exist back then. They didn't moved it as it wasn't worth the pain. This is why it is still in .mozilla.....

You should move it again, now that it's fresh in peoples minds and overwhelmingly used by power users, and then never touch it ever again.

**Comment by TobiasHoll** [comment]
Technically it should use `$XDG_CONFIG_HOME/waterfox` (`$XDG_CONFIG_HOME` [defaults](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) to `$HOME/.config`).

Related Firefox bug: [259356](https://bugzilla.mozilla.org/show_bug.cgi?id=259356)

**Comment by ghost** [comment]
Almost what you said....
In ubuntu the variable is not set.
Then the apps should default to that.

**Comment by grahamperrin** [comment]
OK, Mozilla bug [259356 - Support for the Freedesktop.org XDG Base Directory Specification](https://bugzilla.mozilla.org/show_bug.cgi?id=259356). 

I guess that if Waterfox for Linux and for FreeBSD can be fixed to address all or part of that bug, then we should also: 

- consider the possibility of a change of path leading to apparent breakage of some types of extension 

– whilst #329 relates to a portable edition, on Windows, its 'path change' aspect reminds of another Mozilla bug (if I find it, I'll add a link) …

**Comment by TomJansen** [comment]
The problem with this is that it is not really good practice to just change `~/.waterfox` to `$XDG_CONFIG_HOME/waterfox`, because the spec actually refers to 3 locations:
 
`$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. Defaults to: `$HOME/.local/share`

`$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. Defaults to: `$HOME/.config`

`$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. Defaults to: `$HOME/.cache`

So we need to split up the profile folder, but the problem is figuring out what file should go where...

**Comment by grahamperrin** [comment]
@TomJansen maybe post to the Mozilla bug instead? I have some comments (based primarily on experience with Apple) but they're not Waterfox-specific …

**Comment by grahamperrin** [comment]
For _Core_, needs review: 

- [⚙ D6995 Bug 259356 - Add support for the XDG Base Directory Specification.](https://phabricator.services.mozilla.com/D6995)

**Comment by ilu33** [comment]
I don't think this should be fixed in waterfox as long as it is neither fixed in firefox nor in thunderbird. It's not critical in any way and users expect the directories of mozilla forks in $XDG_HOME. Time can be spent on more important issues.

**Comment by mikejzx** [comment]
Any updates on this? 

As a Linux user it's certainly irritating to have applications store their files in the home directory and clog it up all the time. There was discussion of this happening 16 years ago here: https://bugzilla.mozilla.org/show_bug.cgi?id=259356 and it still hasn't been implemented...

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/3161f531322ae17998d4cc068c723f869f9faae7
