### ISSUE TITLE
LocalStorage is not cleared by add-on

### ISSUE THREAD

**Issue by ontheair81** [BrowserWorks/waterfox#246]
Hello,

I am using the add-on "Self-Destructing Cookies" for privacy reasons. This add-on deletes cookies and LocalStorage except of a whitelist.

The add-on is working fine in Firefox ESR, but not in Waterfox. LocalStorage is never cleared.

Waterfox 55.2.2 on Windows7 Pro
Self-Destructing Cookies version 0.4.12

Thank you for any help!

**Comment by criztovyl** [comment]
I guess this could be related to e10s, but SDC shouln't allow e10s to be enabled.
Could you screenshot about:support?

**Comment by ontheair81** [comment]
Im not so sure what might be interesting in this case from about:support, so I am posting the whole content as text instead of a screenshot. Its in german, but should be no problem, I guess.

Allgemeine Informationen
------------------------

Name: Waterfox
Version: 55.2.2
Build-ID: 20171010194856
Update-Kanal: release
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2
Betriebssystem: Windows_NT 6.1
Fenster mit mehreren Prozessen: 1/1 (aktiviert durch Benutzer)
Web Content Processes: 0/1
Google-Schlüssel: Fehlt
Mozilla-Location-Service-Schlüssel: Fehlt
Abgesicherter Modus: false

Waterfox-Funktionen
-------------------

Name: Firefox Screenshots
Version: 10.12.0
ID: screenshots@mozilla.org

Erweiterungen
-------------

Name: Classic Theme Restorer
Version: 1.7.1
Aktiviert: true
ID: ClassicThemeRestorer@ArisT2Noia4dev

Name: Deaktivierungs-Add-on von Google Analytics
Version: 1.0.7
Aktiviert: true
ID: {6d96bb5e-1175-4ebf-8ab5-5f56f1c79f65}

Name: Facebook Blocker
Version: 1.4.1-signed.1-signed
Aktiviert: true
ID: info@skymeissner.com

Name: Flagfox
Version: 5.1.29
Aktiviert: true
ID: {1018e4d6-728f-4b20-ad56-37578a4de76b}

Name: Foundstone HTML5 Local Storage Explorer
Version: 1.1.1-signed.1-signed
Aktiviert: true
ID: HTML5LocalStorageExplorer@foundstone.com

Name: I don't care about cookies
Version: 2.7.2
Aktiviert: true
ID: jid1-KKzOGWgsW3Ao4Q@jetpack

Name: Image Picker
Version: 1.9.5
Aktiviert: true
ID: ImagePicker@topolog.org

Name: Self-Destructing Cookies
Version: 0.4.12
Aktiviert: true
ID: jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack

Name: uBlock Origin
Version: 1.14.14
Aktiviert: true
ID: uBlock0@raymondhill.net

Name: Video DownloadHelper
Version: 6.3.1
Aktiviert: true
ID: {b9db16a4-6edc-47ec-a1f4-b86292ed211d}

Grafik
------

Allgemeine Merkmale
Compositing: Direct3D 11
Asynchrones Wischen und Zoomen: Mausrad-Eingabe aktiviert; Ziehen der Bildlaufleiste aktiviert
WebGL-1-Treiber: WSI Info: EGL_VENDOR: Google Inc. (adapter LUID: 00000000000081d9) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses
WebGL-1-Treiber: Renderer: Google Inc. -- ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)
WebGL-1-Treiber: Version: OpenGL ES 2.0 (ANGLE 2.1.0.dec065540d5f)
WebGL-1-Treiber: Erweiterungen: GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object
WebGL-1-Erweiterungen: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture
WebGL-2-Treiber: WSI Info: EGL_VENDOR: Google Inc. (adapter LUID: 00000000000081d9) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses
WebGL-2-Treiber: Renderer: Google Inc. -- ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)
WebGL-2-Treiber: Version: OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)
WebGL-2-Treiber: Erweiterungen: GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object
WebGL-2-Erweiterungen: EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc
Audio-Back-End: wasapi
Direct2D: true
DirectWrite: true (6.2.9200.22164)
GPU 1
Aktiv: Ja
Beschreibung: Intel(R) HD Graphics
Herstellerkennung: 0x8086
Gerätekennung: 0x0102
Treiber-Version: 9.17.10.3347
Treiber-Datum: 1-29-2014
Treiber: igdumd64 igd10umd64 igd10umd64 igdumd32 igd10umd32 igd10umd32
Subsys-ID: 1497103c
RAM: Unknown

Weitere Informationen
ClearType-Parameter: Gamma: 2,2 Pixel Structure: RGB ClearType Level: 100 Enhanced Contrast: 50
AzureCanvasAccelerated: 0
AzureCanvasBackend: Direct2D 1.1
AzureCanvasBackend (UI Process): skia
AzureContentBackend: Direct2D 1.1
AzureContentBackend (UI Process): skia
AzureFallbackCanvasBackend (UI Process): cairo
GPUProcessPid: 5088
ClearType-Parameter: Gamma: 2,2 Pixel Structure: RGB ClearType Level: 100 Enhanced Contrast: 50
Entscheidungsprotokoll
WEBRENDER:
opt-in by default: WebRender is an opt-in feature
unavailable by runtime: Build doesn't include WebRender




Wichtige modifizierte Einstellungen
-----------------------------------

accessibility.typeaheadfind: true
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.frecency_experiment: 3
browser.download.folderList: 0
browser.download.useDownloadDir: false
browser.places.smartBookmarksVersion: 8
browser.search.suggest.enabled: false
browser.search.useDBForOrder: true
browser.sessionstore.upgradeBackup.latestBuildID: 20171010194856
browser.startup.homepage_override.buildID: 20171010194856
browser.startup.homepage_override.mstone: 55.2.2
browser.tabs.remote.autostart: true
browser.urlbar.autocomplete.enabled: false
browser.urlbar.searchSuggestionsChoice: false
browser.urlbar.suggest.bookmark: false
browser.urlbar.suggest.history: false
browser.urlbar.suggest.openpage: false
browser.urlbar.suggest.searches: false
extensions.lastAppVersion: 55.2.2
font.name.serif.x-western: Arial
general.useragent.locale: de
gfx.crash-guard.d3d11layers.appVersion: 55.1.0.1
gfx.crash-guard.d3d11layers.deviceID: 0x0102
gfx.crash-guard.d3d11layers.driverVersion: 9.17.10.3347
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d9video: 2
media.benchmark.vp9.fps: 172
media.benchmark.vp9.versioncheck: 2
media.eme.enabled: true
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1506527661
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20171010194856
media.gmp-manager.lastCheck: 1508394773
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1506527665
media.gmp-widevinecdm.version: 1.4.8.903
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
media.webrtc.debug.log_file: C:\Users\STEFAN~1\AppData\Local\Temp\WebRTC.log
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.predictor.enabled: false
network.prefetch-next: false
places.database.lastMaintenance: 1508043429
places.history.enabled: false
places.history.expiration.transient_current_max_pages: 35606
plugin.disable_full_page_plugin_for_types: application/pdf
privacy.clearOnShutdown.cookies: false
privacy.clearOnShutdown.offlineApps: true
privacy.history.custom: true
privacy.sanitize.sanitizeOnShutdown: true
security.sandbox.content.tempDirSuffix: {7340ea91-14f8-48c5-ba81-93474cf2d3a2}
services.sync.declinedEngines:
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1506530322

user.js-Einstellungen
---------------------

Der Profilordner besitzt eine user.js-Datei, welche Einstellungen enthält, die nicht von Waterfox erstellt wurden.

Wichtige nicht veränderbare Einstellungen
-----------------------------------------

Chronik- und Lesezeichendatenbank
---------------------------------

JavaScript
----------

Inkrementelle GC: true

Barrierefreiheit
----------------

Aktiviert: false
Barrierefreiheit verhindern: 0

Bibliotheken-Versionen
----------------------

NSPR
Minimal vorausgesetzte Version: 4.15
Verwendete Version: 4.15

NSS
Minimal vorausgesetzte Version: 3.32.1
Verwendete Version: 3.32.1

NSSSMIME
Minimal vorausgesetzte Version: 3.32.1
Verwendete Version: 3.32.1

NSSSSL
Minimal vorausgesetzte Version: 3.32.1
Verwendete Version: 3.32.1

NSSUTIL
Minimal vorausgesetzte Version: 3.32.1
Verwendete Version: 3.32.1

Experimentelle Funktionen
-------------------------

Isolierte Umgebungen
--------------------

Ebene der isolierten Umgebung des Inhaltsprozesses: 1
Effektive Ebene der isolierten Umgebung: 1

**Comment by criztovyl** [comment]
> Fenster mit mehreren Prozessen: 1/1 (aktiviert durch Benutzer)
Web Content Processes: 0/1

> browser.tabs.remote.autostart: true

SDC can't handle Local Storage with e10s and you seem to have enabled it.
But I thought that SDC, marked as e10s-incompatible by it's author, wouldn't let you enable e10s.

(A screenshot of `about:support` would have shown if you have e10s enabled without the rest you pasted here, the rest is uninteresting in this case.)

**Comment by ontheair81** [comment]
Thank you for your help!

(Was not sure which part is interesting in this case, so I just posted all to be sure ;-) )

**Comment by grahamperrin** [comment]
@ontheair81 does [Self-Destructing Cookies](https://addons.mozilla.org/addon/self-destructing-cookies/) 0.4.12 have the required effect in Waterfox 56.0.3? 

For extensions such as that, please **disallow multi-process** Waterfox before testing with 56.0.3. Thanks.

**Comment by ontheair81** [comment]
I had some strange effects with that:
- SDC should not let me enable e10s because its marked as incompatible. But enabling worked.
- After disabling e10s, SDC should work again with clearing LocalStorage. But it did not.

This was 3 months ago. As I needed a quick solution for this problem, I changed to FirefoxESR and later to Firefox Quantum (where the API now is active and some AddOns are able to clear LocalStorage now).

Unfortunately it was a busy time and I was not able to check it again with Waterfox - as I want to move from Quantum to Waterfox again.

But if other people have more current informations about this issue, would be nice to hear about!

**Comment by grahamperrin** [comment]
## Self Destructing Cookies

> After disabling e10s, SDC should work again with clearing LocalStorage. But it did not.

OK, I might take a look at that issue this weekend. 

## Other extensions that might be of interest

@WagnerGMD recently drew attention to [Shim Storage](https://addons.mozilla.org/addon/shim-storage/). 

I occasionally use legacy version [0.2.6](https://addons.mozilla.org/addon/privacy-settings/versions/?page=1#version-0.2.6) of [Privacy Settings](https://addons.mozilla.org/addon/privacy-settings/), which can affect `dom.storage.enabled` although I have no experience of using the extension in that way.

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/addon/self-destructing-cookies/ states: 

> … incompatible with Firefox 55+ … 

– and Waterfox 56.0 was based on Firefox 56.0.2, so I should not expect the extension to work reliably with any 56.x release of Waterfox.

**Comment by GitCurious** [comment]
Will Waterfox ever get the API that allows extensions to clear localstorage ?

**Comment by grahamperrin** [comment]
Classic Add-ons Archive URL for Self-Destructing Cookies: 

- caa:addon/self-destructing-cookies

In the Wayback Machine: 

- http://web.archive.org/web/20181002185912/https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

**Comment by grahamperrin** [comment]
> … API that allows extensions to clear localstorage ?

Mozilla bug [1355576 - Implement clearing of LocalStorage in browsingData API](https://bugzilla.mozilla.org/show_bug.cgi?id=1355576) (VERIFIED FIXED in Firefox -esr52)

For 1355576 three commits are found, but I don't know whether their changes are in master: 

- https://github.com/MrAlex94/Waterfox/commit/e530ba4d4394d92201da69f600814f80ea8eab00
- https://github.com/MrAlex94/Waterfox/commit/5eeefa573dd8b384b7066f67dd898dccdac893e5
- https://github.com/MrAlex94/Waterfox/commit/e760ae7c085a3053bb90e491b3443b6acbd1d99c (2017-08-06) – _Backed out changeset 5020a2dcb8a7 (bug 1355576) for failures in test_ext_browsingData.js_

----

https://bugzilla.mozilla.org/show_bug.cgi?id=1355576#c47 (2017-11-07) refers to: 

- https://hg.mozilla.org/releases/mozilla-esr52/rev/cf34a0574e58

Still, I don't know whether that would help. Bear in mind, the explicit incompatibility with Firefox 55+. 

@ontheair81 would you like to change the title of this issue? To include the phrase _Self-Destructing Cookies_

**Comment by ilu33** [comment]
The present title is fitting. This is not only about self-destructing-cookies but a general problem.
@grahamperrin Since you investigated this issue: Did you find ANY addon that clears local storage in waterfox 56? I can't find any.

**Comment by grahamperrin** [comment]
Maybe this? 

### Foundstone HTML5 Local Storage Explorer

- caa:addon/foundstone-html5-local-storage

### [Site Bleacher](https://addons.mozilla.org/addon/site-bleacher/)

I used Foundstone HTML5 Local Storage Explorer to capture information including a few lines that began `"https://helpx.adobe.com:443/"`(probably from [Flash Player Help](https://helpx.adobe.com/flash-player.html)) then Site Bleacher to clean at Adobe's page. Then again Foundstone HTML5 Local Storage Explorer, which no longer found the lines. 

### Others

https://addons.mozilla.org/search/?q=local%20storage&type=extension&appver=56.2.6 finds 86 at the time of writing. Not all suitable for clearance of local storage with Waterfox 56.x, but there is (for example) Site Bleacher, first and foremost, which does seem to successfully clean local storage on a site-specific basis. 

I wondered whether https://addons.mozilla.org/search/?q=local%20storage&type=extension&appver=56.0 or (no application version) https://addons.mozilla.org/search/?q=local%20storage&type=extension would yield a broader set of results but no, for both searches there are 86 results. 

[Clear Browsing Data](https://addons.mozilla.org/addon/clear-browsing-data/) and [Fire Clear Cache](https://addons.mozilla.org/addon/fire-clear-cache/) are examples of extensions that can be [installed without warning since Waterfox 56.2.3](https://github.com/MrAlex94/Waterfox/commit/8e978a6df522a2e12ab3080d691fec490db01a56) but might be not entirely compatible with Waterfox 56.2.6. For each extension of interest, check its _versions_ page; if there's a requirement for Firefox 57.0, don't assume complete compatibility with Waterfox 56.2.6.

**Comment by ilu33** [comment]
Thanks you for your recommendations. Sadly HTML5 Local Storage Explorer is not open source.  
Most of those 86 addons found by your search use local storage in some way instead of cleaning it. Others are not available for our browser version in spite of your search criteria (I cross tested on a FF 56, same result), notably ClearPrivateData, Clear Browsing Data and StoragErazor. 
Clear Cookies and Storage Button, Cookiebro (permission to Store unlimited amount of client-side data ??!), Nuke Private Data (permission to read and modify bookmarks??!), Browser Cleaner Pro (no function on firefox) and Website Information are not open source. But I found several test candidates: Site Bleacher, Cookie Quick Manager, eCleaner. I'll report back.

**Comment by ilu33** [comment]
Cookie Quick Manager, Cookie Auto Delete, Site Bleacher, Remove Cookies and Storages Button and Remove Cookies Button can delete local storage of the open tab - sometimes but sometimes not. You have to open the exact subdomain which is not even possible on some domains. http domains persist because you are redirected to the https site. None of them auto-delete. None of them remove addons.mozilla.org entry. None of them remove indexdb data. These addons are of no help. 

Deleting individual entries with HTML5 Local Storage Explorer (not open source) works well. 

Clear Cookies and Storage Button (not open source) and ecleaner (Forget Button) both work - all local storage shown by HTML5 Local Storage Explorer is gone - extension data included which should not have happened according to settings. So I have at least a radical solution.

But everything under /waterfox/storage (indexdb data?)  is still there. ecleaner has an old issue about it [https://github.com/andy-portmen/ecleaner/issues/15] but development seems dead anyway.

**Comment by grahamperrin** [comment]
> … indexdb data? …

If you use any file manager in that area, take care – simply browsing the file system might inadvertently cause failure of IndexedDB. You can use [Firefox Storage Test](https://firefox-storage-test.glitch.me/) to tell whether things are good, working, operational.

**Comment by ilu33** [comment]
Course I did :-) Thanks for the link, and yes, indexeddb is broken. What other choice do I have but break it? I don't want to live with youtube and other tracking (youtube places an ID into indexedDB).  This is a serious problem for a privacy oriented browser like waterfox. A self-operating privacy addon like Self-Destructing Cookies - operating for every kind of client-side storage - is sorely missing. If I understand correctly the API is missing for everything but cookies, so probably nothing much @mralex can do about it - short of setting dom.indexedDB.enabled to false (as the ghacks user.js does).

**Comment by ilu33** [comment]
Just fyi the proposals for indexeddb from the wilderssecurity forum:

> 1. There is the Disable IndexedDB add-on. Unfortunately, exceptions for specific sites are not possible (so you have to manually allow IndexedDB for them). Furthermore, we don't know if it will still be available for Firefox 57+ as it isn't a webextension.
> 2. In your Firefox profile is a folder called storage which in turn contains the three subfolders default, permanent and temporary. The permanent folder is obviously used by some add-ons and should probably not be touched. Now the trick is to delete everything which is in the default and temporary folders (you'll find most probably entries from various websites) and make those two folders read-only. Needless to say, that dom.indexedDB.enabled should be left set to true. ... It seems that those sites still think that IndexedDB is available although they cannot write to those folders mentioned above.

**Comment by grahamperrin** [comment]
IndexedDB discussions (off-topic from LocalStorage) might become sprawling. FYI: 

- [indexedDB broken - UnknownError - Error opening Database : firefox](https://www.reddit.com/r/firefox/comments/9c2q9m/indexeddb_broken_unknownerror_error_opening/)

**Comment by grahamperrin** [comment]
> … Cookiebro 

Featured :+1: and it works with _Firefox 48.0 and later_, and: 

>> - Automatically (optional) delete indexedDB and localStorage caches from websites at browser startup

https://addons.mozilla.org/addon/cookiebro/

[Cookiebro - Cookie Manager [WebExtension] released : firefox](https://www.reddit.com/r/firefox/comments/7snq3l/cookiebro_cookie_manager_webextension_released/) (archived)

> (permission to Store unlimited amount of client-side data ??!), …

[Permission request messages for Firefox extensions | Mozilla Support](https://support.mozilla.org/kb/permission-request-messages-firefox-extensions)

> ## LocalStorage is not cleared by add-on

Does Cookiebro not work?

**Comment by ilu33** [comment]
I did not test CookieBro due to the excessive (so I thought) permissions and due to it not being open source. I settled on ecleaner. But I will reconsider this. 
And sorry for the off-topic - I took the topic not by word but by supposed intent as in: looking for something that clears all kind of storage. I wanted to share my findings but of course I could have opened my own topic.

**Comment by GitCurious** [comment]
CookieBro still does not work with Waterfox in respect to clearing the webappstore.sqlite file, which I can see does get cleaned when using Firefox

I guess this is until WF gains some kind of parity with Fx v57 ?

All this technical stuff confuses me, so I have been using Firefox instead since last year as I do use CookieBro for it`s  cookie handling capabilities.

[I do keep checking if Cookiebro works properly when Waterfox is occasionally updated]

**Comment by grahamperrin** [comment]
A recent post about Cookiebro (and another extension): 

- [56.2.7.1 broke some of my addons : waterfox](https://www.reddit.com/r/waterfox/comments/apfsa2/56271_broke_some_of_my_addons/)

**Comment by MrAlex94** [comment]
LocalStorage may be quite a difficult update - so I'd say if you're focused on extensions that do such things, possibly considering using `Current` now that it's available (wasn't at the time?).
