### ISSUE TITLE
Button that opens your homepage when you open a new tab

### ISSUE THREAD

**Issue by TomJansen** [BrowserWorks/waterfox#250]
As the title says, a button in the general settings menu to open your homepage when you open a new tab. In my opinion, this is such a standard feature I am surprised that it is not in Firefox. I know that an extension exist for this, but I think it should be built into Waterfox.

**Comment by WagnerGMD** [comment]
Several years ago, I had start to think about something little similar. Basically the difference (in my idea) is just about (or concern) the bookmarks. That's why I believe the GUI could be really improve on several points.
At least, just one button to create one bookmark backup will be a nice improvements.

**Comment by MrAlex94** [comment]
browser.newtab.url was removed in Firefox 41 due to malware overwriting the preference all the time. Due to the restrictions in place in modern versions, may be worth bringing this back.
