### ISSUE TITLE
only one empty tab, CPU keeps 200%

### ISSUE THREAD

**Issue by just2d** [BrowserWorks/waterfox#279]
waterfox 57.2.2 64bit 
Mac OS 10.13.1

After I open some tabs, CPU goes high gradually, even when I close all the tabs and leave only one empty tab, the CPU keeps high at 200%, when I restart the waterfox, CPU comes to 0%.

I thought that some tabs triggered some bugs in waterfox(or firefox, when I used firefox before, this happened occasionally too)

I recorded the profile with Gecko Profiler 0.17, hope it's helpful.

[Waterfox 2017-11-22 19.33 profile.sps.json.gz](https://github.com/MrAlex94/Waterfox/files/1495781/Waterfox.2017-11-22.19.33.profile.sps.json.gz)

![qq20171122-192511](https://user-images.githubusercontent.com/6417639/33125728-a159bf34-cfbc-11e7-9c5f-aa9bc9521a2c.png)

**Comment by grahamperrin** [comment]
From the `.json` file: 

```
{
  "meta": {
    "interval": 1,
    "startTime": 1511342004953.4973,
    "abi": "x86_64-gcc3",
    "misc": "rv:55.0",
    "oscpu": "Intel Mac OS X 10.13",
    "platform": "Macintosh",
    "processType": 0,
    "product": "Waterfox",
    "stackwalk": 0,
    "toolkit": "cocoa",
    "version": 9,
    "preprocessedProfileVersion": 9
  },
```

If the issue is reproducible with more recent Waterfox 56.0.4.1 on a more recent version of High Sierra: 

- can you let us have the URLs of a set of tabs, a set that you associate with high CPU usage on your Mac? 

Also it might be useful to have a System Information report. 

Thanks. 

In the meantime, I might take a look at the profile with a pre-release build of High Sierra.

**Comment by grahamperrin** [comment]
> … I might take a look at the profile with a pre-release build of High Sierra.

I never found the time, sorry. 

Is this still an issue with 56.1.0? 

If so: would you like to test 56.2.0 before its general release? 

[Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)
