### ISSUE TITLE
Violentmonkey and Tampermonkey not working in Waterfox 56

### ISSUE THREAD

**Issue by Ofunniku** [BrowserWorks/waterfox#299]
As it says on the tin: neither work in WFX56 with whatever version of those addons I install.

I tried restarting browsers after enabling the addons too they just never seem to load (I also can't access their options pages from the addons tab)

Rolling back to Waterfox 55.1.0.1 immediately sets them working again, so will have to stick to that version for now.

**Comment by MrAlex94** [comment]
Will have to backport the patches from [here](https://blog.mozilla.org/addons/2017/07/18/compatibility-firefox-56/) it seems as a few add-ons seem to be broken!

**Comment by Ofunniku** [comment]
Still an issue as of 56.0.1

**Comment by LafinJack** [comment]
Same here, also with uBlock Origin.

**Comment by mkruselj** [comment]
Yes, uBlock not working in WF56... What's happening?

**Comment by mkruselj** [comment]
What's the status on this one?

WF56 unusable over here, with uBlock not running at all (not sure why!).

**Comment by MrAlex94** [comment]
Could you try setting **extensions.e10sBlockedByAddons** and **extensions.e10sMultiBlockedByAddons** to **true**, then restarting? This will disable add-ons not explicitly marked as compatible and may be a cause for the instability and add-ons not working.

Also, what versions of uBlock aren't working?

**Comment by mkruselj** [comment]
I will try that, Alex, thanks!

I have uBlock Origin 1.14.22.

Will report if the above setting changes work in about 5 minutes!

**Comment by mkruselj** [comment]
OK those two settings were _already_ set to "true"... I set them to false, but uBlock didn't return. I don't see its icon in the status bar.

Another plugin that doesn't seem to work here is uAutoPagerize. It's interesting because in Add-ons panel, I don't see "Options" button for those add-ons (they are usually there for uBlock!)

**Comment by MrAlex94** [comment]
Hm.. could you use the [Profile Manage](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) to test out a new profile, then install uBlock? I'd imagine it works then, and something is wrong with the profile you're currently using.

**Comment by mkruselj** [comment]
OK I'll try that too.

But why does my current profile work on 55.2.2?

**Comment by mkruselj** [comment]
Hmmm... fresh profile and it works!

But I really have too many customizations going on in my current profile, rebuilding it from scratch seems a chore (especially since FF Sync is not perfect and it doesn't sync addon settings, not all addons support that...)

Can I pack my profile folder and send it to you so you can see in detail what might be wrong with it in WF56?

**Comment by grahamperrin** [comment]
@mkruselj if you can share troubleshooting information, I'll take a look. From about:support

**Comment by mkruselj** [comment]
Sure, no prob!

https://pastebin.com/DLmeW7c4

Actually damn, that's with 55.2.2. Moment...
  
EDIT:

https://pastebin.com/WxqjF914

This is with 56.0.1.

**Comment by mkruselj** [comment]
OK so I spent a bit of time and rebuilt my profile from scratch... everything is alright with the world now, uBlock is fine again.

Image Search Options is not, though. WebExtensions won't install on a clear profile. Possibly because the latest version of it needs FF57? No matter, I went with XUL version.


If you want to chase this bug further, feel free. I've kept my old broken profile on my drive, in case I missed something when rebuilding the profile.

**Comment by grahamperrin** [comment]
pastebin.com/WxqjF914 at a glance, I couldn't see anything that might cause the problem. uBlock Origin 1.14.22 works for me. Firefox 56.0.1 on FreeBSD-CURRENT. 

> …  uBlock is fine again.
> 
> Image Search Options is not, …

[Image Search Options](https://addons.mozilla.org/addon/image-search-options/) works for me. 

> … I went with XUL version.

https://addons.mozilla.org/addon/image-search-options/versions/ no version requires Firefox Quantum. 

> …  WebExtensions won't install …

Please see [No compatibility with FF57 Addons · Issue #346 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/346)

**Comment by MrAlex94** [comment]
@mkruselj, if you don’t have any personal/sensitive information in your old profile I’ll happily take a look at it. 

As Graham said, nothing I can see that affects it.

**Comment by Ofunniku** [comment]
@MrAlex94 as of Waterfox 56.0.2, the issue appears to have been resolved; Userscripts from Violentmonkey are being loaded and sites are correctly rendering with the scripts taking effect.

Can others confirm Violentmonkey and Tampermonkey as working for 56.0.2?

PS: @LafinJack @mkruselj from the symptoms I can see, your issues are not relevant to my specific issue, as I had NO issues with uBO or uMatrix with Waterfox 56's release. As of the latest version uBO and uMatrix still appear to be correctly filtering pages and blocking connections. My other addons appear to all be loading and functioning correctly.
