### ISSUE TITLE
Waterfox 56: Impossible to add spaces and separators to toolbars in customize mode

### ISSUE THREAD

**Issue by remez** [BrowserWorks/waterfox#312]
Hello,
I need to customize my toolbars adding a fixed space or other elements added by the CTR.
I go in "Hamburger" -> "Customize"
In the "Additional Tools And Features" Windows I see some elements that I want to move to my toolbars.
If I try to move "Space" or "Separator" or "Flexible Space" in any toolbar, when I release the left button of the mouse, the element isn't inserted in the toolbar.

Configuration:
Windows 7 64 bit
Waterfox 56.0 64bit English
Default Theme
Tried with a clean installation of Waterfox and CTR (last Official version and last beta)

Thank you

[https://github.com/Aris-t2/ClassicThemeRestorer/issues/384](url)

**Comment by grahamperrin** [comment]
> https://github.com/Aris-t2/ClassicThemeRestorer/issues/384

Also https://github.com/Aris-t2/ClassicThemeRestorer/issues/383

> …"Space" or "Separator" or "Flexible Space" …

Not specific to Waterfox. There's the same problem with Classic Theme Restorer with Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT. 

@remez to reduce duplication/multiplication, maybe close this issue; things might be progressed under the earlier issues in the Classic Theme Restorer repository.

**Comment by mzso** [comment]
@MrAlex94 
Maybe this is an easy fix? The way Aris talks about this in the CTR issue certainly makes it sound so.

**Comment by Lorienna** [comment]
The following commit broke the spacers and separators in CTR:


- https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=f2836ff575eb04b5c9a2fc44e9e47a5ed35ddfdb&tochange=0e4a948fbae28f323599eedd0da5f75a13289ff5

- [Bug 1366813 - Add customizable flexible space item in customize mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1366813)

Reverting it would probably restore their normal functioning.

And of course the pref `browser.photon.structure.enabled` must be always set to `false` to keep the Photon UI off :)

@Aris-t2

**Comment by Aris-t2** [comment]
For me it was always clear Firefox code broke special toolbar items on purpose. There was no need to add such changes to Fx56, when it was actually meant for Fx57. Not sure, if this change can be reverted inside Waterfox code, but I'm optimistic. ;-)

A workaround for CTR still does the job:
1. Enter customizing mode after starting Waterfox. 
2. Right-click on a spacer / empty space / flexible space item and select "Add to toolbar".
_(Drag&drop is either broken or permitted by the browser, CTR only offers the items and their appearance, but not how they are handled by the browser)._
3. Once on toolbar you can move those items wherever you like them to be.

There is a discussion about this on CTRs Github support area too: https://github.com/Aris-t2/ClassicThemeRestorer/issues/383

**Comment by grahamperrin** [comment]
Thanks @Aris-t2 and NB (from the linked issue): 

>> … disappearance (from available buttons) after first use of _Customise_ …

In other words: 

> 1. Enter customizing mode after starting Waterfox.

If what's required is not present in that mode, then: 

a) quit/exit Waterfox
b) start Waterfox
c) repeat step (1).

**Comment by grahamperrin** [comment]
From <https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-348703527> (2017-12-02): 

> … and Firefox 56 do not support spaces, flexible spaces and separators anymore.

Also <https://www.reddit.com/r/waterfox/comments/7jndj6/-/drbun04/> (2017-12-16): 

>> Firefox 56 … broke the ability to move flexible spaces, spaces and separators to toolbars. … 

We have limited workarounds, with extensions such as Classic Theme Restorer, but this is – essentially – an issue (by design) with Mozilla Firefox 56. #824 is a duplicate.

**Comment by IzzySoft** [comment]
> #824 is a duplicate.

I doubt that. Quoting the original description here:

> In the "Additional Tools And Features" Windows I see some elements that I want to move to my toolbars. If I try to move "Space" or "Separator" or "Flexible Space" in any toolbar, when I release the left button of the mouse, the element isn't inserted in the toolbar.

In #824 those elements are not there at all – so of course they cannot be moved.

Somehow same outcome (no spacers to use) – but I'm not sure these are dupes.

**Comment by grahamperrin** [comment]
Compare with a new profile with Firefox 56.0.2 …

**Comment by Lorienna** [comment]
<b>Note:</b> in Waterfox/Firefox 56, the Flexible Space is available in the customization palette when the preference <code>browser.photon.structure.enabled</code> is set to <code>true</code>.

**Comment by Lorienna** [comment]
## <sub>Modifying the preference to add spaces and separators<sub>

The method of editing the `browser.uiCustomization.state` preference has been described multiple times, including by Aris in the <a href="/Aris-t2/CustomCSSforFx/issues/109#issuecomment-394116049" title="General discussions, feedback, questions belong here (v4) · Issue #109 · Aris-t2/CustomCSSforFx · GitHub">CustomCSSforFx#109 (comment)</a> and on mozillaZine forums <a href="http://forums.mozillazine.org/viewtopic.php?f=38&t=3037911" title="Separators in Firefox Quantum Fx57+ without CSS/WEs/add-ons &bull; mozillaZine Forums">here</a> and <a href="http://forums.mozillazine.org/viewtopic.php?f=48&t=2827985&start=5686" title="[Ext] Classic Theme Restorer &bull; mozillaZine Forums">there</a>.


<details><br>

To place a special widget, for example, on the Navigation Toolbar, go to `about:config` address > search for the `browser.uiCustomization.state` preference > copy and paste the content of its string value into a text file > find the `nav-bar` array > add an entry there > update the string in `about:config` and restart the browser.

A flexible space (bold):

<pre>
"nav-bar":["urlbar-container","downloads-button","<b>customizableui-special-<i>spring2019</i></b>","home-button"]
</pre>

A fixed space:
<pre>
"nav-bar":["urlbar-container","downloads-button","<b>customizableui-special-<i>spacer2019</i></b>","home-button"]
</pre>

A separator:
<pre>
"nav-bar":["urlbar-container","downloads-button","<b>customizableui-special-<i>separator2019</i></b>","home-button"]
</pre>

As you can see, the `nav-bar` array is a JSON array where the values must be enclosed in straight quotation marks and separated by commas, and the numeric suffix of the _special_ value must be random and unique throughout the toolbar arrays for the _type_ of item.

You can also move the Flexible Space from the customization palette onto the Navigation Toolbar, and then change the `spring` part to `separator` or `spacer` before restarting the browser.

Another possibility is to manually edit the `prefs.js` file when the browser is closed.
Make sure the quotes are escaped with backslashes there:

<pre lang="rtf">
\"nav-bar\":[\"urlbar-container\",\"downloads-button\",\"customizableui-special-spacer2019\",\"home-button\"]
</pre>

The toolbar arrays include:

<pre lang="robot">
nav-bar                 navigation toolbar
PersonalToolbar         bookmarks toolbar
TabsToolbar             tabs toolbar
toolbar-menubar         menu bar
</pre>

<pre lang="robot">
ctraddon_addon-bar      classic theme restorer: add-on bar
ctraddon_extra-bar      classic theme restorer: additional bar
</pre>

</details>

**Comment by Lorienna** [comment]
## <sub>Modifying the toolbar items with CSS to create spaces and separators</sub>

You can transform flexible spaces into other spacing items, hide buttons or increase their margins.
Learn about the `userChrome.css` file in the <a href="/Aris-t2/CustomCSSforFx/blob/master/README.md#user-content-instructions--howto--readme" title="CustomCSSforFx/README.md at master · Aris-t2/CustomCSSforFx · GitHub">CustomCSSforFx/README.md</a> or on the <a href="https://www.userchrome.org/how-create-userchrome-css.html" title="How to Create a userChrome.css File">userchrome.org</a> site.

<details><br>

<blockquote>

<a href="/Aris-t2/CustomCSSforFx/issues/88#issuecomment-352249348" title="General discussions, feedback, questions belong here (v3) · Issue #88 · Aris-t2/CustomCSSforFx">Aris-t2 commented on Dec 17, 2017:</a>

You can force flexible spacers to have fixed width values:

<pre lang="jisonlex">
#main-window:not([customizing]) #nav-bar toolbarspring {
  min-width: 20px !important;
  max-width: 20px !important;
}</pre>

You can use this hack to create one separator out of two spaces (place one space after another). Make sure to use the same width everywhere like in this example (->"20px"):

<pre lang="jisonlex">
#main-window:not([customizing]) #nav-bar toolbarspring {
  min-width: 20px !important;
  max-width: 20px !important;
}
#main-window:not([customizing]) #nav-bar toolbarspring + toolbarspring {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: -20px !important;
}</pre>

<a href="/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/flex_space_on_navbar_replace_with_separator.css" title="CustomCSSforFx/flex_space_on_navbar_replace_with_separator.css at master · Aris-t2/CustomCSSforFx">Turn all flexible spaces on navigation toolbar into separators</a>:

<pre lang="jisonlex">
#main-window:not([customizing]) #nav-bar toolbarspring {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: 1px !important;
}</pre>

</blockquote>

Transform all flexible spaces on the Navigation Toolbar except the first and the last ones into separators with the `:nth-of-type` and the `:nth-last-of-type` pseudo-class selectors, and decrease the <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity" title="Specificity - CSS: Cascading Style Sheets | MDN">specificity</a> of the rule with the `:root` pseudo-class selector instead of `#main-window`:

<pre lang="sass">
:root:not([customizing]) #nav-bar toolbarspring:nth-of-type(n+2):nth-last-of-type(n+2) {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: 1px !important;
}</pre>

Make the first and the last flexible spaces on the Navigation Toolbar into separators using the `:first-of-type` and the `:last-of-type` pseudo-class selectors:

<pre lang="sass">
#main-window:not([customizing]) #nav-bar toolbarspring:first-of-type,
#main-window:not([customizing]) #nav-bar toolbarspring:last-of-type {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: 1px !important;
}</pre>

Turn, for example, the 3rd and the 5th flexible spaces on the Navigation Toolbar (counting from start/left) into fixed spaces with the `:nth-of-type`:

<pre lang="sass">
#main-window:not([customizing]) #nav-bar toolbarspring:nth-of-type(2n+3):nth-of-type(-n+5) {
  min-width: 15px !important;
  max-width: 15px !important;
}</pre>

Use the `:nth-last-of-type` to create a fixed space from, e.g., the 2nd flexible space on the Navigation Toolbar (counting from end/right):

<pre lang="sass">
#main-window:not([customizing]) #nav-bar toolbarspring:nth-last-of-type(2) {
  min-width: 15px !important;
  max-width: 15px !important;
}</pre>

Transform a particular flexible space into a separator of distinct style:

<pre lang="css">
:root {
  --separators-width-spring2019: 4px;
}

#main-window:not([customizing]) #customizableui-special-spring2019 {
  -moz-appearance: none !important;
  min-width: var(--separators-width-spring2019) !important;
  max-width: var(--separators-width-spring2019) !important;
  margin: 0.4em 4px !important;
  border-right-width: var(--separators-width-spring2019) !important;
  border-right-style: dotted !important;
  border-right-color: HotPink !important;
}</pre>

Replace flexible spaces situated after the Location Bar with separators using the General / Following Sibling Combinator (`~`):

<pre lang="css">
#main-window:not([customizing]) #urlbar-container ~ toolbarspring {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: 1px !important;
}</pre>

Replace one flexible space situated _immediately after_ a button with a separator using the Adjacent / Next Sibling Combinator (`+`):

<pre lang="css">
#main-window:not([customizing]) #downloads-button + toolbarspring {
  -moz-appearance: separator !important;
  min-width: 1px !important;
  max-width: 1px !important;
  -moz-margin-start: 1px !important;
}</pre>

Increase margins of individual buttons targeting them by #ID that can be found using the <a href="https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox" title="Browser Toolbox - Firefox Developer Tools | MDN">Browser Toolbox</a>; within the string value of the `browser.uiCustomization.state` preference; in the <a href="/Aris-t2/CustomCSSforFx/blob/master/classic/css/buttons/icons_custom_icons.css">style recipes</a> of CustomCSSforFx; etc.:

<pre lang="css">
#main-window:not([customizing]) #downloads-button,
#main-window:not([customizing]) #home-button {
  margin-right: 15px !important;
}</pre>

<pre lang="css">
:-moz-any(#downloads-button, #home-button) {
  margin-right: 15px !important;
}</pre>

Leave empty space instead of an unneeded button:

<pre lang="css">
#main-window:not([customizing]) #home-button {
  visibility: hidden !important;
}</pre>

The set of pseudo-class selectors matching the sibling elements of the same type (`toolbarspring`) within a container (`nav-bar`) and its descendant containers:

<pre lang="nanorc">
:first-of-type            the first elements
:last-of-type             the last elements
:only-of-type             the only elements
:nth-of-type()            the nth elements (counting from start)
:nth-last-of-type()       the nth elements (counting from end)
</pre>

The toolbar ID selectors include:

<pre lang="lfe">
#nav-bar                  navigation toolbar
#PersonalToolbar          bookmarks toolbar
#TabsToolbar              tabs toolbar
#toolbar-menubar          menu bar
</pre>

<pre lang="lfe">
#ctraddon_addon-bar       classic theme restorer: add-on bar
#ctraddon_extra-bar       classic theme restorer: additional bar
</pre>

The element selectors of spaces and separators on toolbars and in the hamburger menu:

<pre lang="robot">
toolbarspring             flexible spaces
toolbarspacer             fixed spaces
toolbarseparator          separators
</pre>

The ID selectors of individual special widgets (custom spaces and separators on the main window toolbars):

<pre>
#customizableui-special-<i><b>spring</b>2019</i>       [id$=<i><b>spring</b>2019</i>]           a flexible space
#customizableui-special-<i><b>spacer</b>2019</i>       [id$=<i><b>spacer</b>2019</i>]           a fixed space
#customizableui-special-<i><b>separator</b>2019</i>    [id$=<i><b>separator</b>2019</i>]        a separator
</pre>

</details>

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/dqk4h5
