### ISSUE TITLE
Request: Remove Lz4 compression (.json.mozlz4, bookmarks, etc.)

### ISSUE THREAD

**Issue by ForkedLightning** [BrowserWorks/waterfox#330]
Compression on text files used for config and bookmarks with an obscure format bordering on proprietary (given that there are no easily available tools) is an anti-feature and serves no purpose asides from preventing the user from viewing and editing them. If compression is required, they can be stored in a widely used open format like .gz

Mozilla has no intention of changing this. They promised to do something about it 3+ years ago. The browser doesn't even read the uncompressed .json files in absence of the compressed ones which makes it more damning.

**Comment by grahamperrin** [comment]
This may be contentious with [Fix Waterfox making too many writes for SSDs · Issue #225 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/225). 

----

Mozilla bugs that may be of interest include: 

- [1209390 - Use standard lz4 file format instead of the non-standard jsonlz4/mozlz4](https://bugzilla.mozilla.org/show_bug.cgi?id=1209390)
- [1410877 - Improve the reliability of Places and the storage subsystem](https://bugzilla.mozilla.org/show_bug.cgi?id=1410877) – a meta bug with nothing (yet) about compression, I half-expect something to appear there in the future.

**Comment by Squall-Leonhart** [comment]
This will also cause data loss for anyone that has used firefox 56.

**Comment by grahamperrin** [comment]
Now at AMO: 

- [mozlz4-edit](https://addons.mozilla.org/addon/mozlz4-edit/)

> … [is this the first extension to add `.json.mozlz4` editing capability to Firefox- and Firefox Quantum-based browsers?](https://addons.mozilla.org/addon/mozlz4-edit/reviews/1073100/) …

**Comment by grahamperrin** [comment]
> … browser doesn't even read the uncompressed `.json` files …

Not reproducible. Tested with Waterfox 56.0.4.1 (56.0.4.20_2) in safe mode: 

![2018-03-04 10 39 49 waterfox](https://user-images.githubusercontent.com/192271/36944684-3ca7e7aa-1f99-11e8-95c7-8af0d8dfbe37.png)

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info waterfox | grep Version ; uname
Version        : 56.0.4.20_2
FreeBSD
```

----

@ForkedLightning if you can not get your installation of Waterfox to open and display a `.json` file, please post to [Waterfox Community Support](https://www.reddit.com/r/waterfox/) (on Reddit); someone will be happy to help.

**Comment by ghost** [comment]
reopen please

i see "search.json.mozlz4" (related to search engines). I did a grep, it's the only one.
`ls -lR $HOME/.waterfox/XXXXXXX.default | grep mozlz4`

**Comment by grahamperrin** [comment]
Consider 60 as a base, interop with Firefox ...

**Comment by ghost** [comment]
Ohh ok wait, now i got it. I thought that it was half done.... I had the impression that they used to be more .mozlz4 .

Alex should comment why he closes an issue. He often doesn't say anything....

**Comment by MrAlex94** [comment]
Sorry for closing this without saying anything.

Essentially I don’t think it’s worth the problems disabling this will cause considering the availability of tools to extract the data. 

I would agree if it was a closed, proprietary format but since it’s not and it’s just the way Mozilla chose to compress things (albeit inconvenient).
