### ISSUE TITLE
Adobe Flash Player 28.0.0.126 can not present its context menu, crashes, with Waterfox 56.0.1 on Linux

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#335]
Spun off from [Right click in flash causes flash to crash : waterfox](https://www.reddit.com/r/waterfox/comments/7ltwkd/right_click_in_flash_causes_flash_to_crash/)

tl;dr the crash seems to be:  

- consistently reproducible on Linux
- not reproducible on Mac OS X
- not reproducible on FreeBSD-CURRENT. 

The menu as it appears, without crashing, on the latter: 

![2017-12-24 22 08 47](https://user-images.githubusercontent.com/192271/34383830-13b298da-eb10-11e7-87a2-35029852a1cd.png)

- testing with the animation at https://helpx.adobe.com/flash-player.html

**Comment by Jazoray** [comment]
Adding lines that appear in dmesg at time of crash:

```
[Thu Dec 28 07:09:57 2017] plugin-containe[12877]: segfault at 0 ip 00007f894b2f3fe1 sp 00007ffcbb8e4a90 error 6 in libmozgtk.so[7f894b2f2000+4000]
[Thu Dec 28 07:20:30 2017] plugin-containe[14572]: segfault at 0 ip 00007fbc91df4fe1 sp 00007ffde4963070 error 6 in libmozgtk.so[7fbc91df3000+4000]
```

copying the  libmozgtk.so files from unaffected versions of waterfox into affected versions of waterfox makes the right click crash no longer reproducible.

but doing so probably adds a heap of other issues, so this shouldnt be a workaround.

**Comment by Jazoray** [comment]
the issue also occurs when the flash object tries to create a file upload dialog.

**Comment by MrAlex94** [comment]
Probably a sandboxing issue, no? Has anyone tried disabling sandboxing for flash completely? I wouldn't recommend it, but it's an option.

**Comment by Jazoray** [comment]
i'm not entirely sure how to disable sandboxing for flash. but google seems to suggest the setting `dom.ipc.plugins.flash.disable-protected-mode`. i tried setting it to true, restarting the browser, and trying to reproduce the bug. 

toggling the setting has no effect. this bug is still reproducible with `dom.ipc.plugins.flash.disable-protected-mode` set to `true`

**Comment by Lorienna** [comment]
Regressed by:
- [Bug 1364355](https://bugzilla.mozilla.org/show_bug.cgi?id=1364355) + [commits](https://hg.mozilla.org/integration/autoland/pushloghtml?changeset=457e6aea4650)
Implement client side decorations - Support ARGB visuals | RESOLVED FIXED in Firefox 55

Fixed by:
- [Bug 1405267](https://bugzilla.mozilla.org/show_bug.cgi?id=1405267) + [commit](https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?changeset=d06512adfab5)
Right clicking on Flash content crashes plugin process | RESOLVED FIXED in Firefox 57

##
Please build and test!

**Comment by Jazoray** [comment]
i'm on 56.2.12 (64-bit) and flash player 32.0.0.192 and i can no longer reproduce the issue

**Comment by grahamperrin** [comment]
Reproducible here, at <https://helpx.adobe.com/flash-player.html> with version 32.0.0.223 of the Player added to 56.2.12:

![image](https://user-images.githubusercontent.com/192271/61429705-359be400-a91f-11e9-9665-de5561ddff2e.png)
