### ISSUE TITLE
Privacy Issue with Waterfox sending its custom user agent

### ISSUE THREAD

**Issue by Joel889** [BrowserWorks/waterfox#345]
I noticed that Waterfox changes Firefox's user agent to indicate that Waterfox is being used. Given Waterfox's small user base, this provides a pretty good tracking opportunity. I understand that it is interesting to know how many users Waterfox has, but since privacy is Waterfox's highest priority I think the user agent should be identical to Firefox's.

**Comment by grahamperrin** [comment]
Related: [User-Agent: Waterfox · Issue #178 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/178)

**Comment by defkev** [comment]
Set `privacy.resistFingerprinting` to `true` if you want a more generic user agent.

This will change the default user agent to `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0` unless overwritten by a `general.useragent.override...` entry.

**Comment by hook321** [comment]
That setting does more than just changing the user agent.
https://www.ghacks.net/2016/07/04/tor-privacy-settings-coming-to-firefox/

**Comment by jbeich** [comment]
Maybe also backport mozilla/gecko-dev@d20c7d929c84 to avoid pretending to be a vulnerable Firefox version.

**Comment by cnleo** [comment]
If you setup the privacy “privacy.resistFingerprinting” to “true” 
the entry in “general.useragent.override” has no effect
It will not change the default user agent “Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0“
Only for individual domains “general.useragent.override.yourindividualdomain.tld”
has an effect.

@jbeich thanks, yes it would be awesome +1 for backport
because I don’t think this is a good useragent. It feels like “hey look rv:50, they have resist fingerprinting on”
It would be awesome If they use the ESR version one with actual patchlevel revision (is the patchlevel submited in general useragent?).

**Comment by grahamperrin** [comment]
> … custom user agent

That ceased some time ago. 

Close this? 

(For the discussions unrelated to the UA, you'll probably find other issues on the subject(s).)
