### ISSUE TITLE
No compatibility with FF57 Addons

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#346]
Several addons i use have been updated for FF57 and can no longer be downloaded or installed due to compatibility errors. I am not sure if this is a false alarm due to waterfox being marked as version 56 or if there really is a compatibility issue. I guess it depends on how much of the code base was combined.

**Comment by grahamperrin** [comment]
Please let us have the `addons.mozilla.org` address of an affected add-on. 

Also the result of visiting https://udger.com/resources/online-parser

**Comment by mikeloeven** [comment]
Here is the main one https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/

**Comment by defkev** [comment]
If the addon author sets the min-version of his addon to 57 you will need to run 57 to install the addon.

**Comment by mikeloeven** [comment]
does waterfox not have the FF57 code base yet ?

**Comment by defkev** [comment]
Thankfully not, as this would break every legacy addon, just like FF Quantum 💩 

> Waterfox will now remain at 56 for the time being...
> ...
> * Based on Firefox 56.0.2 release

https://www.waterfoxproject.org/blog/waterfox-56.0-release-download

**Comment by jdunn0** [comment]
With the release of Firefox 57, Mozilla both removed support for older add-ons and added new APIs for WebExtensions based add-ons to use.
The idea being at that point that the WebExtensions APIs would be good enough that the older add-ons would not be needed.
While that is true for some add-ons, that are many older add-ons that depend on APIs that just don't exist with WebExtensions so you need to use Firefox 56 or Waterfox 56 to use them.
This leads to the unfortunate case where you need an older version of Firefox or a fork like Waterfox to use those older add-ons and the newer version of Firefox to use the add-ons that have migrated to use the new APIs unless that add-on only uses WebExtension APIs that were available in Firefox 56.

In theory, you can have a release of Firefox or Waterfox that supports both the older add-ons and the latest WebExtensions APIs but at the moment, only Mozilla could really do that and they decided against doing that.
The resources and manpower required to support both is something that the smaller development groups for Pale Moon and Waterfox just can't do.
Even just supporting the older add-ons after Mozilla stops supporting them (Around June 2018 when Firefox 52 ESR support ends) will become harder for the developers of Pale Moon and Waterfox.

Hopefully should maintaining support for older add-ons be no longer practical for Pale Moon and Waterfox, there will enough WebExtension APIs available to make it a good option for all add-ons or Mozilla realizes they made a mistake and adds the support for older add-ons back into Firefox.

**Comment by grahamperrin** [comment]
## Waterfox use of … Quantum code

> does waterfox not have the FF57 code base yet ?

Please subscribe to: 

- [Waterfox Quantum? · Issue #267 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/267)
- [Stylo – layout.css.servo.enabled – in Waterfox · Issue #332 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/332)

– and if we browse other issues, we might find more that relate to Firefox Quantum or Project Quantum code bases. 

----

> # No compatibility with FF57 Addons

## Nano Defender

https://addons.mozilla.org/addon/real-nano-defender/versions/ all _apparently_ work: 

> with Firefox for Android 57.0 and later, Firefox 57.0 and later

– so it's **reasonable to assume** that the extension will not work with any Firefox 56.x-based version of Waterfox. 

Assumptions aside …

## Defocusing from Waterfox

Sometimes, rarely, you'll find that Firefox version requirements expressed at `addons.mozilla.org` are not entirely representative of an add-on's requirements. 

That's true for extensions such as Conex: 

- no sign of compatibility with Waterfox 56.0.1 at https://addons.mozilla.org/addon/conex/versions/ or https://addons.mozilla.org/addon/conex/versions/?page=2
- if you ignore the greyed-out _Add to Firefox_ button for version 0.0.79 – if you download it – you'll find that it **does** install with Firefox 56.0.2 or Waterfox 56.0.1. 

Here, with Waterfox: 

![2018-01-01 12 02 47](https://user-images.githubusercontent.com/192271/34467589-25b11aac-eeee-11e7-8642-14f5648e1d0f.png)

Also for Conex there are `.xpi` releases at GitHub: 

- https://github.com/kesselborn/conex/releases

No such luck with Nano Defender 13.16. With compatibility checking enabled, `nano_defender-13.16-an+fx.xpi` can not be installed. 

## [checkCompatibility2](https://addons.mozilla.org/addon/checkcompatibility2/)  _also known as_ Disable Addon Compatibility Checks (Version 4-56)

With this extension installed: if you're lucky, an _apparently_ incompatible extension will be usable with Firefox 56.0.2 or Waterfox 56.0.1. 

An example: 

![2018-01-01 12 46 14](https://user-images.githubusercontent.com/192271/34467809-485c4c48-eef3-11e7-8d9e-e5bd96af7197.png)

![2018-01-01 12 46 42](https://user-images.githubusercontent.com/192271/34467815-4c4ab7cc-eef3-11e7-8ae4-7340d8594b46.png)

![2018-01-01 12 47 05](https://user-images.githubusercontent.com/192271/34467818-505aa84a-eef3-11e7-8eee-8d47aedc4679.png)

## addons.mozilla.org

If ever you successfully perform an installation of an extension that is apparently incompatible with Waterfox; 

- do not expect automated updates from `addons.mozilla.org`
- please be prepared to periodically check the add-on's page. 

## In any case

If you choose to ignore compatibility information: proceed with caution, and at your own risk.

**Comment by criztovyl** [comment]
Maybe also interesting, from the `xpi`'s `manifest.json`:

```json
  "applications": {
    "gecko": {
      "strict_min_version": "57.0"
    }
  }
```

**Comment by grahamperrin** [comment]
Yep, as far as I know that strictness (`strict_min_version`) is what's overridden, at install time, by checkCompatibility2. 

- Mozilla bug [1192437 - Support custom min/maxVersion Web Extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1192437)
- [extensions.checkCompatibility - MozillaZine Knowledge Base](http://kb.mozillazine.org/Extensions.checkCompatibility)

**Comment by NRG90** [comment]
Regarding Nano Defender on Waterfox 56.0.1:

[![Schermata_2018-01-04_alle_12.30.25.png](https://s13.postimg.org/6zalh94br/Schermata_2018-01-04_alle_12.30.25.png)](https://postimg.org/image/gwlmabbxf/)

download the converted one (from Chrome Version) here:

http://www.mediafire.com/folder/2hzlanm6715l9/Firefox_and_Waterfox_Legacy_addons

**Comment by grahamperrin** [comment]
Another add-on that supposedly requires at least Firefox 57.0, truly works with Waterfox 56.0.2: 

- [Mobile Dyslexic 0.3](https://addons.mozilla.org/addon/mobile-dyslexic/versions/?page=1#version-0.0.3)

**Comment by sanjayen** [comment]
@NRG90 how did you install Nano Adblocker? I downloaded Nano Defender. How do you keep it updated with the latest version? Thank you for providing the upload site.

**Comment by ip004** [comment]
Hi. The FireX Proxy 5.1.2 add-on from Firefox's add-ons page, doesn't seem to be able to be installed in Waterfox 56.0.3 because there's an error message that says ""FireX Proxy could not be installed because it is not compatible with Waterfox 56.0.3.". I guess that's because WebExtension add-ons that are only compatible with Firefox 57 and newer, aren't compatible with Waterfox 56.0.3, but is there a way to fix that? Thanks.

**Comment by grahamperrin** [comment]
> … 5.1.2 …

Please follow the link to versions, there's a compatible version. 

Alternatively, use about:addons to find and install the extension; the most recent compatible version is automatically chosen for you.

**Comment by NRG90** [comment]
@sanjayen 

Regarding Nano Defender, I used the chrome foxified add-on to convert the Chrome version to the legacy one compatible with waterfox  and  then I manually check new versions on Chrome web Store

[![Schermata_2018-02-02_alle_15.38.32.png](https://s17.postimg.org/vdhy09rxb/Schermata_2018-02-02_alle_15.38.32.png)](https://postimg.org/image/ozsux0n17/)
https://www.mediafire.com/folder/2hzlanm6715l9/Firefox_and_Waterfox_Legacy_addons

**Comment by grahamperrin** [comment]
From above: 

> If ever you successfully perform an installation of an extension that is apparently incompatible with Waterfox: 
> 
> - do not expect automated updates from `addons.mozilla.org`
> …

From the issue that discusses the possibility of allowing Waterfox 56.1 to receive updates for that type of extension: 

> … [AMO doesn't allow installing Waterfox-incompatible extensions.](https://github.com/MrAlex94/Waterfox/issues/484#issuecomment-375512243) …

For completeness, note that with user agent `Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4` **plus** a change to compatibility checking, the **Download anyway** feature of AMO _can_ allow installation of extensions that are partly incompatible with Waterfox 56.0.4.1. 

Conex, for example: 

![2018-03-23 07 55 52](https://user-images.githubusercontent.com/192271/37818128-fa63ea56-2e70-11e8-94d1-9004941125c1.png)

– outdated version 0.2.1 works _with Firefox 60.0a1 and later_

![2018-03-23 07 56 23](https://user-images.githubusercontent.com/192271/37818132-fd21916c-2e70-11e8-9f5e-5ed432e9f3cb.png)

![2018-03-23 07 58 43](https://user-images.githubusercontent.com/192271/37818133-ffcd4e92-2e70-11e8-9e1e-17d6bc0efed1.png)

## Partial compatibility

In the third shot, there's enabling of an option that we _should not_ (probably _must not_) expect to work with Waterfox 56.0.4.1.

**Comment by nl255** [comment]
As for Nano Adblocker/Nano Defender, the latest versions work fine if you get them from the Chrome store so they obviously don't need 57+ to work.

**Comment by grahamperrin** [comment]
## Reddit Enhancement Suite (RES)

RES is another example of an extension that requires Firefox 57 (or greater) for some but _not all_ of its features. 

There's the red alert at its AMO page, https://addons.mozilla.org/addon/reddit-enhancement-suite/ – and if you install [the most recent version](https://addons.mozilla.org/addon/reddit-enhancement-suite/versions/) then (with Waterfox 56.1.0) there'll be no automated discovery of updates – but version 5.12.2 of RES _is_ **essentially fine** with version 56.1.0 of Waterfox. 

### Known issues

The first set of commits for an API that's not usable with Firefox 56.0.2 was: 

- [Use openerTabId with openNewTabs on Firefox by bomjacob · Pull Request #4518 · honestbleeps/Reddit-Enhancement-Suite](https://github.com/honestbleeps/Reddit-Enhancement-Suite/pull/4518) 

That set fixed issues such as these: 

- <kbd>Shift</kbd> + <kbd>Enter</kbd> on a link will open a tab at the end of the tab bar, rather than next to the current one
- Opening comments in new tabs in clunky
- Single Click Opener placing tabs in the wrong location

If those are the type of issue that might bother you, then you should think twice before installing a version of RES that's marked (at AMO) as incompatible with Waterfox. 

If (like me) those things are no bother, then you should be fine with 5.12.2. 

----

That's not intended to be a comprehensive list of known issues – there might have been, and probably will be, other commits involving APIs that are not yet usable with Waterfox. It's just a shortlist, an example.

**Comment by CyberShadow** [comment]
> That set fixed issues such as these:

Here's a patch which reverts that change and allows shift+C etc. to work again:

```diff
diff --git a/lib/environment/background/tabs.js b/lib/environment/background/tabs.js
index cb03bda1..845a04ff 100644
--- a/lib/environment/background/tabs.js
+++ b/lib/environment/background/tabs.js
@@ -13,12 +13,11 @@ addListener('openNewTabs', ({ urls, focusIndex }, { id: tabId, index: currentInd
 			});
 		});
 	} else if (process.env.BUILD_TARGET === 'firefox') {
-		// Firefox needs cookieStoreId to open in correct container
 		urls.forEach((url, i) => {
 			chrome.tabs.create({
 				url,
 				active: i === focusIndex,
-				openerTabId: tabId,
+				index: ++currentIndex,
 				cookieStoreId,
 			});
 		});
```

I don't know what the RES project's stance is on supporting Waterfox, but it should be trivial to adapt it to support the older API version as well as the newer version, if it's available.

Edit: And [here's a built .xpi (patch above applied against latest master)](https://dump.thecybershadow.net/c74e93ef63e603fb2c7c7009b879b373/res.xpi).

**Comment by grahamperrin** [comment]
### Waterfox 56.2.3

#### Installing from addons.mozilla.org (AMO)

From <https://www.reddit.com/r/waterfox/comments/9g0tea//e60tgo5/>: 

> … Video DownloadHelper on AMO … 'Add to Firefox' button isn't greyed out anymore. It was greyed out with 56.2.2, …

Video DownloadHelper https://addons.mozilla.org/addon/video-downloadhelper/ 7.3.5 is a good example of a version of an extension that: 

1. "Works with Firefox 57.0a1 and later" and 
2. differs significantly from the most recent compatible legacy version. 

Given the constraints of WebExtensions you'll probably find it necessary to use the [companion application](https://www.downloadhelper.net/install-coapp) if you manually install 7.3.5 over 6.3.3. Then if you find 7.3.5 and its companion not working as expected with Waterfox 56.2.3, re: https://www.downloadhelper.net/help you can seek help in the support forum. 

----

Generally, loosely speaking: 

- whilst browsing AMO, with Waterfox 56.2.3 it's easier (than with 56.2.2) to manually install an extension that _might_ be not entirely compatible with Waterfox
- to check compatibility, prior to installation, it's worth stepping aside from the main page of the extension – click **See all versions** then pay attention to the "Works with …" line. 

#### Updating

The AMO-oriented update routines in 56.2.3 remain stringent. 

For example: Video DownloadHelper should not automatically update from 6.3.3 to 7.3.5.

**Comment by grahamperrin** [comment]
From <https://www.reddit.com/comments/9g0tea/-/e60osk4/>: 

> … I suppose that somehow Waterfox 56.2.3 has been now marked as equivalent to Firefox 57 (or 58 ?) for AMO addon compatibility 

57 but not 58

> so that we now … see all 57+ (and maybe 58+ too ?) extensions as compatible even when they are not. …

### An unusual, relatively complex example: NoScript

A most recent release of this extension requires Firefox 59.0 or greater: 

1. https://addons.mozilla.org/addon/noscript/ 
2. https://addons.mozilla.org/addon/noscript/versions/ 

At (1) there's a hint, "Fx52?". 

At (2) users of Waterfox 56.2.3 will find most of the _+ Add to Firefox_ buttons greyed out. Just one of the buttons is green – for version **10.1.6.5**, which " Works with Firefox for Android 57.0 and later, Firefox 57.0 and later". The NoScript case is very unusual because this one green button should be ignored **and** you will not find the appropriate version by continuing to page through the versions that are listed at AMO. 

Instead: https://noscript.net/getit#older for more recent version **5.1.8.7** of NoScript, which is intended primarily for use with Firefox ESR 52. 

5.1.8.7 is the version that's appropriate for Waterfox 56.2.3. Discussion in the Waterfox area at https://redd.it/9ez5w7 and support for the extension can be sought at <https://forums.informaction.com/viewforum.php?f=3>. 

### A pleasantly simple example: Firefox Multi-Account Containers

A blue _+ Add to Firefox_ button at <https://addons.mozilla.org/addon/multi-account-containers/>.

A green (AMO classic) _+ Add to Firefox_ button at <https://addons.mozilla.org/addon/multi-account-containers/versions/> and here's the detail: 

> Works with Firefox for Android 57.0 and later, Firefox 57.0 and later 

Waterfox 56.2.3 is not entirely compatible with version 6.0.0 of the extension, but the combination is fine.

**Comment by skrivskithar** [comment]
Checker plus for gmail

This extension doesn't work after update 21.2.3 (I've been using that version since I moved to Waterfox). I don't understand much about addon development, but I guess it has to do with FF discontinuing legacy addons: 

https://addons.mozilla.org/en-US/firefox/addon/checker-plus-gmail/?src=search

If there's no workaround for new versions to work, is there any way to disable it from notifying me about new updates?

**Comment by grahamperrin** [comment]
https://jasonsavard.com/forum/discussion/5290/strict-min-version/p1

**Comment by grahamperrin** [comment]
> any way to disable it from notifying me about new updates?

I think not. #349

**Comment by skrivskithar** [comment]
thanks for your effort, graham!

**Comment by grahamperrin** [comment]
### Cookie AutoDelete

From <https://www.reddit.com/comments/dahnh0/-/f1te63v/?context=1>

> Some add-ons say they are not compatible with waterfox, but seem to work perfectly. Latest Cookie Autodelete is one such. …

Re: <https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/513#issuecomment-482822105>

>> … First Party Isolation + CAD doesn't work unless you are on a FF version of 59 or higher. …

Also re: https://addons.mozilla.org/addon/cookie-autodelete/

>> … can clear localstorage as of version 2.1.0 and Firefox 58+. …

https://addons.mozilla.org/addon/cookie-autodelete/versions/ 2.1.0 

- "… Added: First Party Isolation Support (Firefox 59+, …"; and 
- according to the AMO page it _works with_ Firefox 56.0 and later, Android 57.0 and later

– **however** given what's above, I should assume that 2.1.0 and 2.2.0 are not entirely functional with Waterfox Classic 56.2.14 (assume that features such as _clearance of localstorage_ are non-functional).

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/commit/0c4a9333220575f5f3e571329afaaf9657192bd7#diff-2ccaee6c5cfa6c1e0a36166894df97bcL30 the `strict_min_version` was raised from `56.0` to `59.0` with release 3.0.0 of the extension.
