### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by DaAwesomeP** [BrowserWorks/waterfox#35]
When I open my profile with Waterfox, the memory slowly grows until it locks and then has to use the disk and pagefile. When I open the same profile in Firefox, there are absolutely 0 problems. It stays at a healthy memory.

Waterfox 40.1.0
Windows 8.1 Pro x64

**Comment by DaAwesomeP** [comment]
I just refreshed my profile (made a new one, imported user data, reinstalled extensions), and the problem is still there (the memory slowly climbs and is larger than when opened in Firefox). It's better, but still not good.

**Comment by MESWEB** [comment]
I have this same issue. When I use by long time then RAM is full of Waterfox. Sometimes Waterfox take much than 1,5 GB of RAM this is ridiculous because Chrome take less of RAM and when I close tabs in Google Browser then RAM is free up. This means only one - Waterfox collecting all of Browsing Memory and keep it after when I close Browser. Can someone explain this?

**Comment by MrAlex94** [comment]
This issue shouldn't be much of an issue anymore due to reverting back to VC for the time being.
