### ISSUE TITLE
56.0.1 was unable to even see the 56.0.2 update

### ISSUE THREAD

**Issue by leafcutterant** [BrowserWorks/waterfox#361]
I was on 56.0.1, clicking Help -> About quite often to receive the 56.0.2 update (defense against Spectre and Meltdown) as soon as possible. WF kept saying it's up to date. But it turns out that 56.0.2 has been out for at least a day and WF didn't catch it.

What could've caused this?

Just to rule out firewall issues, which process is responsible for fetching updates?

**Comment by NRG90** [comment]
It's happened also to me with macOS version...

**Comment by MrAlex94** [comment]
It's most likely the CDN. AFAIK it can take up to 24 hours to propagate across the network. Anyway, going to update every Linux version to 56.0.2 and then versions 55+ for Windows and macOS.

**Comment by WagnerGMD** [comment]
```
lockPref("app.update.auto",false);
lockPref("app.update.enabled",false);
lockPref("app.update.service.enabled",false);
## It will disable the update (menu Help ---> "About Waterfox")
```
You didn't mentionned the page **about:config**. Then I imagine yes it could be another cause.

**Comment by leafcutterant** [comment]
> ```
> lockPref("app.update.auto",false);
> lockPref("app.update.enabled",false);
> lockPref("app.update.service.enabled",false);
> ## It will disable the update (menu Help ---> "About Waterfox")
> ```

Where is this snippet from? And why are they disabled? I checked mine:

app.update.auto - false
app.update.enabled - true
app.update.service.enabled - entry doesn't exist

**Comment by PandaCodex** [comment]
Same people on 55.2.2 are not seeing the updates, same with other versions.

**Test case:**
Install [Waterfox 51.0.1 Setup.exe](https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2051.0.1%20Setup.exe)
Let it update
New version will be [Waterfox 55.2.2 Setup.exe](https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2055.2.2%20Setup.exe)
Check for updates, Waterfox is up to date.

![1n9usndufn9u2n9u](https://user-images.githubusercontent.com/25470255/34697875-e5c9eeee-f520-11e7-862a-a2f3b5051225.JPG)


Same with older versions people still using them because Waterfox can't see the new versions.

If you install Waterfox 56.0 it will update to the latest release 56.0.2, 55.2.2 should also, same with older versions. I have be posting about this issue for quite some time now hope it gets resolved soon

**References:** 
- https://www.reddit.com/r/waterfox/comments/7llc9j/waterfox_updates/drnmj8b/?context=3
- https://www.reddit.com/r/waterfox/comments/7o7bn6/with_the_release_of_the_mozilla_security_advisory/ds7vk5a/?context=3
- https://www.reddit.com/r/waterfox/comments/7o43fp/help_waterfox_5522_not_telling_me_to_update_to_56/
- https://www.reddit.com/r/waterfox/comments/74lhwh/why_doesnt_waterfox_provide_a_hash_to_check_the/
- https://www.reddit.com/r/waterfox/comments/6hodns/waterfox_540_release_windows_mac_linux_now/dj8r05b/?context=3

**Comment by grahamperrin** [comment]
> … 55.2.2 …

Please see [55.x fails to apply update · Issue #369 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/369)

**Comment by WagnerGMD** [comment]
It's an extract from my own file **mozilla.cfg** (it's an equivalent to **about:config**). I won't be able to say why @leafcutterant the last one doesn't exist for you.
Perhaps it doesn't exist anymore ? Yes it could be because sometimes I don't read the news or just a little part. That's why I had probably miss it.

For one simple good damn reason **: the people want to control these updates.** Because they wish to avoid trouble because sometimes the update isn't a good choice or worst buggy.
They will refuse Firefox Quantum because the WebExtensions aren't yet ready (not good enough or missing features) and yes I understand these point of view.

**Comment by leafcutterant** [comment]
@WagnerGMD, thanks. I want to be notified about available updates, but I want to be in control deciding whether I want to install or not. How should I configure my about:config to reach this behavior?

**Comment by leafcutterant** [comment]
Update: I still had the same issue and it seems it persisted for a week.

I was on 56.0.2, found out today via the site that 56.0.3 has been out for a week. I went to Help -> About, it said it's up to date. Did the same thing again, then it noticed the new version and downloaded the update.

This makes me believe it's not the CDN. Could it be the default about:config settings? (See the ones my WF came up with in my [comment above](https://github.com/MrAlex94/Waterfox/issues/361#issuecomment-356108438).)

**Comment by WagnerGMD** [comment]
```
lockPref("app.update.auto",false);
lockPref("app.update.enabled",true);
lockPref("app.update.service.enabled",false);
## According to Firefox_v60_Nightly this one still exist
```
Sorry my late answer, I had just see your post and you're welcome @leafcutterant. You will be able to control them just with one little change (2nd line). Because now you can proceed the update manually (when you want (every 2 or 4 weeks, etc) open the menu **About Firefox**).
To deny the update just close it (or don't click on the button). Then you can dismiss report it to later) the update. But apparently it will ask it again (at each browser launch). There is maybe one settings to recall this answer but I ignore (exist or no ? Which one ?...).

**Comment by leafcutterant** [comment]
Update: the problem still persists. Based on the Github release, 56.1.0 has been out for 7 days, but when I go to Help -> About, it still mistakenly says Waterfox is up to date.

My about:config values remain the same as they were, also identical to @WagnerGMD's, except for the fact that I don't have `app.update.service.enabled` (it's also missing from a fresh Waterfox profile, so I guess it's weeded out from Waterfox). So I don't know why is it not working.

    app.update.auto;false
    app.update.enabled;true

**Comment by grahamperrin** [comment]
[“Auto-update will release soon! Got caught up in other work - apologies! 👨‍💻” : waterfox](https://www.reddit.com/r/waterfox/comments/87ybgu/autoupdate_will_release_soon_got_caught_up_in/)

**Comment by grahamperrin** [comment]
Review time. Please, is this still an issue?

**Comment by leafcutterant** [comment]
@grahamperrin Kinda-sorta. My instance noticed 56.2.0 1-2 days after the release (can be attributed to the CDN), but it still wasn't noticed automatically / Waterfox didn't tell me by itself although it should have, based on my settings.
