### ISSUE TITLE
Installer clobbers previous session when both firefox and waterfox are installed

### ISSUE THREAD

**Issue by SirIntellegence** [BrowserWorks/waterfox#382]
I ran the installer to update waterfox (to 56.0.3) and the tabs I had open before I installed the update were replaced with the tabs I had open from firefox when I first installed or when I first installed waterfox. I am currently at work so I can't try to see if I can get it to happen again at the moment.

**Comment by jdunn0** [comment]
Firefox and Waterfox store backup copies of the sessionstore file (open tabs) that are used in case the current sessionstore file is missing or corrupt.

When running Waterfox for the first time, you can import your profile with the sessionstore file to create a new Waterfox profile.
This new Waterfox profile will update the sessionstore file as the session (open tabs) changes and keep backups of older sessionstore files for a period of time.

It appears that when the update to Waterfox 56.0.3 was installed, Waterfox decided to use an older backup sessionstore file for some reason instead of the current sessionstore file that your previous version of Waterfox was using.

Why that would happen I'm not sure but the fact that Firefox is also installed should have nothing to do with it at all.
Waterfox 55 and up store profile data in a separate location and Waterfox will never use the Firefox profile data unless you tell Waterfox to import the profile.

To help figure out what happened in your case, can you list the version of Waterfox you had installed before the update, the Operating System version you have and if your user account has administrator permissions.

**Comment by SirIntellegence** [comment]
It looks like it was 55.2.2 on Win 10 with admin permissions

**Comment by grahamperrin** [comment]
Review time. Is this still an issue?

**Comment by SirIntellegence** [comment]
I will need to check. I need to run the installer again anyway...

**Comment by SirIntellegence** [comment]
It appears to be fixed.
