### ISSUE TITLE
Not an issue, only a question

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#39]
Sorry for using the Issues channel for the only purpose of finding an answer concerning of course Waterfox. There is unfortunately little documentation provided regarding this Firefox fork.

I'd wish to know what differentiates Waterfox from Firefox besides the code optimization.

I'm running Firefox 43.0.4 64-BIT at this time. I am as many Firefox users concerned with the browser's planned development and bothered by mainly two upcoming changements.

1- The add-on signature made mandatory starting Firefox 44 (some say not before ver.45). I've read that Waterfox will not subscribe to this add-on signature enforcement : is this true?

2- The Electrolysis project, planned for late 2016 as I understand it. Will Waterfox include Electrolysis accordingly with Firefox? I am concerned moreover because I run ~70 add-ons of which most valuable ones could become obsolete for the sole reason of not being updated to an Electrolysis-compatible version.

Thanks for sharing your knowledge of these two points, mainly.

**Comment by chdft** [comment]
There is a changelog on the projects website which includes a list of differences (feature wise) to mozilla firefox: https://www.waterfoxproject.org/blog/waterfox-43.0.4-release-download
Please also note that there is a [subreddit](https://www.reddit.com/r/waterfox) for general discussion about this browser.

I can't tell you anything beyond that, since I'm only a user of Waterfox as well.

**Comment by ghost** [comment]
Thanks @chdft for the information. I'll have a look at the subreddit.
