### ISSUE TITLE
Waterfox ▸ Help ▸ Submit feedback…

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#399]
Feedback URLs such as https://input.mozilla.org/feedback/waterfox/56.0.3/ currently redirect to Firefox-specific https://qsurvey.mozilla.com/s3/FirefoxInput/

## On the Waterfox side of things

The _Submit feedback…_ menu item should be associated with a different URL (one that will not redirect to Firefox-specific feedback), maybe https://www.reddit.com/r/waterfox/

- or remove the menu item, until there's something like a SurveyGizmo routine for Waterfox (<https://qsurvey.mozilla.com/> redirects to <https://www.surveygizmo.com/>). 

For what it's worth: I favour temporary removal of the feedback item. Focus instead on **Help ▸ … Help** …

## On the Mozilla side

There should be an issue for the inappropriate redirect …

**Comment by WagnerGMD** [comment]
From my point of view, reddit will be one bad choice for matters related to any code. It's totally buggy (the markdown code syntax) and they doesn't seem to care about (none improvements, neither news in the last 2 months).
At the contrary, it could be an idea for the **Submit feedback**. Another way could be the GitHub itself because (for me it's more readable and) the issue has a features called **tags** (or **label**). It will help a lot in the aim to filter these posts (after in the futur).

**Comment by grahamperrin** [comment]
I'm very often frustrated by the deficiencies of Reddit. I suggested Reddit only because it is (or was, [in 2014](https://redd.it/2ov0dr)) preferred by @MrAlex94.

---- 

For different reasons, GitHub can be equally frustrating. 

Features such as labels and milestones do have the potential to add value. However: if not very carefully planned – and if not applied with consistency – things such as labels can make it **more** difficult to find what's required, especially when a repository becomes relatively busy. 

There are notions such as [Suggestion: Introduce a Discussion tab · Issue #44 · dear-github/dear-github](https://github.com/dear-github/dear-github/issues/44) but I don't foresee GitHub becoming well-suited to discussion.

**Comment by WagnerGMD** [comment]
I understand very well @grahamperrin. We might need to think about that one day (Waterfox futur website).

Apparently, it's worst now. Because these last weeks, the CSS on reddit is buggy (big white space, missing posts, etc)... After a few days, I might have found the cause : **bad design** (if you want another bad example you can take Flarum). Because once you enable the both (cookie and javascript with one addon such as Umatrix, etc), the CSS will be display correctly. But it's just bad because the CSS doesn't require them.
To resume another bad point for reddit. I don't always want to be connected to read any topics.

**Comment by grahamperrin** [comment]
#538

**Comment by grahamperrin** [comment]
> … temporary removal of the feedback item. …

@WagnerGMD please, do you have any objection to that? 

See parallel discussion at/around https://github.com/MrAlex94/Waterfox/issues/548#issuecomment-390438419 (and reply here) – thanks.

**Comment by grahamperrin** [comment]
@Toromino thanks for https://github.com/MrAlex94/Waterfox/issues/548#issuecomment-391214627 your offer of a pull request. WagnerGMD is (I think) sometimes not an everyday reader of Waterfox-related notifications in GitHub, so it's kind of you to wait. 

> Fixing this would be a trivially easy thing.

Yep :-) I could attempt it myself but (sorry) priorities are elsewhere – I'll be heavily focused on extensions-related issues for the next few days. 

----

Plus of course, I could have reported the bug to Mozilla months ago. I could lie and say that priorities have been elsewhere but the truth is, I've been lazy :-) ~ mañana

**Comment by WagnerGMD** [comment]
No I don't see @grahamperrin any point to keep it. From my point of view, yes you can remove it.
Because it's **another bad design** (from Mozilla this time).
How are we supposed to follow any report (topic, etc) ? I don't (or nobody) have a clue...

**PS :** You're right (about the "not an everyday reader") because sometimes :
- I need to take a break (absent for several days). 
- I'm not always connected to internet (busy IRL)
- I just to want to read and I will reply when it's possible (too exhausted)
- etc

**Comment by grahamperrin** [comment]
Many thanks 👍 and as an aside, I sometimes spend _months_ away from bugs/issues!

**Comment by WagnerGMD** [comment]
You're very welcome @grahamperrin and sometimes I feel the same (let's take some vacancy even my phone today is buggy).

**Comment by grahamperrin** [comment]
Closing. Thanks folks. 

https://github.com/MrAlex94/Waterfox/pull/579#issuecomment-394119605 confirms sight of the change in Waterfox on FreeBSD. 

Users of Waterfox on other platforms may realise the change (the removal) in the next general release. 

----

**Comment by eric-007z** [comment]
Problem is about:config > plugins.update.url;https://www.mozilla.org/%LOCALE%/plugincheck/ - where I get a [Win-7] mozilla intercept saying old version with a firefox download button. Some might be confused. Same with
menu bar > help > "Waterfox help" >
app.support.baseURL;https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/ 
see
app.support.e10sAccessibilityUrl;https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/accessibility-ppt

What about interim, for such config defaults, create a single "under construction" github page, or some such intercept URL, listing all problem moz-links; and then set that new page as default for the config variables linking to moz pages? As each is fixed/changed, can then update the interim redirect. Presuming coding of a different default config variable is not difficult; it could be done next update.

Not a coder, but [for Win-OS] it appears searching about:config > http * moz * [ search w/o spaces which were added to avoid italics loss of the * characters] identifies and rounds up all the problem config pointers, however the decision goes on what to do to avoid confusing users. The menu > help TEXT has been rewritten "Waterfox help" but the about:config default went unchanged - more confusing than not. That's re my Win-OS; w/o knowing how Linux or FreeBSD do config variables???

**Comment by grahamperrin** [comment]
> Problem is about:config > `plugins.update.url`…

Please see <https://github.com/MrAlex94/Waterfox/issues/611#issuecomment-397526114> under _Hide redundant entries from about:config. · Issue #611 …_

For the other suggestions: this issue was closed, so please aim for an open area in either GitHub or Reddit. Thanks.
