### ISSUE TITLE
Can we PLEASE update Waterfox to Quantam?

### ISSUE THREAD

**Issue by Raj2032** [BrowserWorks/waterfox#413]
It would be great if Waterfox can catch up to Firefox, why is there such a hold back?

**Comment by criztovyl** [comment]
The classic, non-webextensions extension API holds back. But there is #267, maybe subscribe there.

**Comment by Raj2032** [comment]
WHy can't the classic non-webextension extenion api be included in Quantam?

On Tue, Jan 30, 2018 at 11:23 PM, Christoph Schulz <notifications@github.com

**Comment by criztovyl** [comment]
It can, but that takes time. This project isn't that big.
Also I guess that maintaining the classic api and additionally integrating it with Quantum isn't that trivial.

**Comment by jdunn0** [comment]
The Mozilla codebase is huge and managed by a large amount of people at Mozilla.
With Firefox 57, Mozilla decided to make code changes for Quantum and remove a lot of code that supported XUL/XPCOM add-ons.

Attempting to go though that codebase and figure out which changes were done for Quantium and which changes were to remove support for XUL/XPCOM add-ons and only keep the changes for Quantium is not an easy task for a small development team that to my knowledge primary consists of just @MrAlex94.

One interesting thing about Firefox 57 that doesn't seem widely known is that Firefox 57 still has support for some XUL/XPCOM APIs but that support is restricted to selected add-ons (The small list can be seen by looking at the value of extensions.legacy.exceptions in about:config) and those add-ons need to be signed by Mozilla's signing key for the browser to load them.

If you install Firefox Developer Edition, you can tweak some about:config options to let you load any XUL/XPCOM add-on, signed or unsigned but because some XUL/XPCOM APIs were removed, the add-ons may or may not work properly.
Unlike previous versions of Firefox, Mozilla did not release a list of changes to the XUL/XPCOM APIs so developers of XUL/XPCOM add-ons could make sure their add-ons still worked because Mozilla's policy is to only support WebExtensions based add-ons now regardless of what the codebase may still support.

Probably, within a few versions, Mozilla will actually finish removing the XUL/XPCOM APIs for add-ons entirely making the little support that is still there, actually gone.

In theory this means, a Waterfox 57 could be created based on Firefox 57 along with restoring support for XUL/XPCOM add-ons that were available in Firefox 56, and 55 (The point at which, I think Mozilla started removing the less used XUL/XPCOM APIs).

Though even then some of the Quantum changes may actually prevent the code for those older XUL/XPCOM APIs from working without a lot of changes which again is harder to deal with by a smaller development team.

Also, once Mozilla stops supporting Firefox 52 ESR in June or July then they will have no released versions of Firefox that include support for installing XUL/XPCOM add-ons (excluding the Developer Edition/Nightly builds of course), then Mozilla will likely want to stop hosting XUL/XPCOM based add-ons on Mozilla add-ons at which point, even getting XUL/XPCOM add-ons in the first place will be harder.

There is a small amount of those add-ons on Palemoons site though those add-ons don't necessarily work with the Mozilla codebase of XUL/XPCOM APIs released after Palemoon forked Mozilla's codebase.

Maybe Alex will be able to set up a Waterfox specific add-ons site before then for Waterfox to use so users can get XUL/XPCOM add-ons and update them.

But if Waterfox could support both XUL/XPCOM add-ons and WebExtensions based add-ons then the Waterfox add-ons site would need to allow XUL/XPCOM add-ons and WebExtensions to be shown on the site and developers with a WebExtension based add-on would need to publish their add-on to Mozilla Add-ons and the Waterfox add-ons site but that part probably wouldn't be much different then publishing a WebExtension for Firefox, Chrome, Edge, etc.  if it was supported.

Realistically, the ability to support XUL/XPCOM add-ons with the Quantum changes is probably only possible with a larger development team like Mozilla has.

The amount of work to maintain a Firefox fork that supports XUL/XPCOM add-ons, WebExtensions add-ons and Quantum features all at the same time is certainly not something, it seems would be easy and my brain hurts just thinking about digging into the Mozilla codebase to sort out all the different changes.

**Comment by grahamperrin** [comment]
> #267, 

Yep, I'd prefer to not track two issues for the one subject.

**Comment by LafinJack** [comment]
> The amount of work to maintain a Firefox fork that supports XUL/XPCOM add-ons, WebExtensions add-ons and Quantum features all at the same time is certainly not something, it seems would be easy and my brain hurts just thinking about digging into the Mozilla codebase to sort out all the different changes.

"And what do you call this act?"

"The Developers!"

**Comment by Raj2032** [comment]
Hey, just asking are you guys legally allowed to change the software
license to MIT or WTFPL?

**Comment by MrAlex94** [comment]
@Raj2032, no that's not allowed.

Also, there seems to be misunderstanding as to what 'Quantum' actually is. It's not something that Mozilla just supplanted into v57, it's a bunch of small projects over time coming together at one point. Firefox 56 is just as "Quantum" as 57, bar bug fixes and various features being explicitly enabled.

Please continue in the other thread.
