### ISSUE TITLE
Customize not working

### ISSUE THREAD

**Issue by Richie765** [BrowserWorks/waterfox#416]
I just started using Waterfox. When I start a clean install of 56.0.4 I can't enter customize. When I click on the hamburger, and then customize, the customize screen shows briefly and then exits customize immediately before I can do anything.

I tried to refresh all the settings, even tried on a fresh new user account all with the same effect. Using macOs 10.13.3

**Comment by NRG90** [comment]
on mac OS X 10.10.5 (Yosemite) with waterfox 56.0.4  

I don't have the issue you have... but I noticed that when I customize my toolbar, adding only some types of icons (add-ons with submenù in his icons), like "selective cookie delete" or "SmothScroll"
my toolbar has this glitch:

BEFORE:

[![Schermata_2018-02-02_alle_11.57.11.png](https://s9.postimg.org/822tmod9b/Schermata_2018-02-02_alle_11.57.11.png)](https://postimg.org/image/xxmk5vf2z/)

AFTER:

[![Schermata_2018-02-02_alle_11.56.47.png](https://s9.postimg.org/5kr2ff8sf/Schermata_2018-02-02_alle_11.56.47.png)](https://postimg.org/image/k3y7gu1x7/)

[![Schermata_2018-02-02_alle_12.10.53.png](https://s9.postimg.org/n1zro7tsv/Schermata_2018-02-02_alle_12.10.53.png)](https://postimg.org/image/rb4hqdx23/)

.

**Comment by jbeich** [comment]
@Richie765 wrote:
> customize screen shows briefly and then exits customize immediately before I can do anything

Also [reported](https://www.reddit.com/r/waterfox/comments/7um0ey/cannot_customize_layout_waterfox_5604_on_linux/) on /r/waterfox. To fix try applying mozilla/gecko-dev@6b36043a0db3 to 
https://github.com/MrAlex94/Waterfox/blob/d7f689c984bf15259ae5c882ab7d36919f3bbda8/browser/components/customizableui/CustomizeMode.jsm#L738-L745

Firefox photonized this code in mozilla/gecko-dev@ecca1af556f9.

Existing profiles aren't affected because Customize mode tip shows up only once. To force it again reset`browser.customizemode.tip0.shown` pref in `about:config`.

**Comment by jbeich** [comment]
Existing profiles aren't affected because Customize mode tip shows up only once. To force it again reset`browser.customizemode.tip0.shown` pref in `about:config`.

**Comment by jbeich** [comment]
Fixed by a400678cf54c.
