### ISSUE TITLE
Use unbiased pixel rounding for borders

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#422]
Same as https://github.com/MoonchildProductions/Pale-Moon/issues/1556

**Comment by Lorienna** [comment]
Regarding the PM team's solution...

The following commit solved the issue #__1556__ in the deprecated repo of Pale Moon 27 (ESR-38 hard fork with the classic UI):

- "Round subpixel border widths to nearest integer instead of nearest-below integer."
https://github.com/MoonchildProductions/Pale-Moon/commit/7d810df6d25093d0985c97525abd4914a787ae8b


As a consequence, caret became thick, and people complained:

- __Issue__ #__1575:__ "Split off caret width from CSS border width and give it the anaemic treatment"
`https://github.com/MoonchildProductions/Pale-Moon/issues/1575`

- __Commit:__ "Split border and caret width rounding."
https://github.com/MoonchildProductions/Pale-Moon/commit/c3b23d899c92037a49c4f8cd669069e5391ab42b

The patches for #__1556__ and #__1575__ were later ported to the Unified XUL Platform (UXP; ESR-52 hard fork):

- __Commit:__ "Use natural border width rounding."
https://github.com/MoonchildProductions/UXP/commit/d1b17ef97efd0e4f869c98dfada8d09f1cb1ad5a


Also, as a side-effect of rounding sub-pixel border widths, tabs in Basilisk (UXP-based browser with Australis UI) became afflicted with vertical lines in HiDPI mode:

- __Issue__ #__268:__ "[BASILISK] Vertical stripes in tabs at high DPI display resolutions"
`https://github.com/MoonchildProductions/UXP/issues/268`

- __Commit:__ "Create a 1px overlap between tab center and start/end backgrounds."
https://github.com/MoonchildProductions/UXP/commit/32c067857c532bf651e5e6946ec1a67772eb2252


As for the possible solution from the old PM repo suggested in #538, I believe that's irrelevant to Australis theme:

- __Issue__ #__1584:__ "Adjust theme to account for natural border width scaling"
`https://github.com/MoonchildProductions/Pale-Moon/issues/1584`

- __Commit:__ "Adjust the theme to account for natural border width rounding."
https://github.com/MoonchildProductions/Pale-Moon/commit/afa34c7a6978ac5c61797d5a875f34601e900def

---

Maybe someone can give this a proper testing in Waterfox.
