### ISSUE TITLE
Some form in forum won't work ???

### ISSUE THREAD

**Issue by DxRaider099** [BrowserWorks/waterfox#446]
I think pictures are the better way to explain my problem
in firefox or opera form on various site are like this : 
https://i.imgur.com/agB5COL.png

and all work correctly but for some mysterious reason the same page and site on waterfox show that : 
https://i.imgur.com/IbDxidm.png 

so when i try to post any response of any type then clic on the red button waterfox give me that 
https://i.imgur.com/9y6lkU3.png

Please if someone can help to fix it just tell me how .

**Comment by grahamperrin** [comment]
Use Waterfox to visit <https://udger.com/resources/online-parser>, what's the user agent string?

**Comment by DxRaider099** [comment]
Done the result is that : 

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4

**Comment by JohanPirlouit** [comment]
Hi everyone,

I had some issues including form issues as you have and video playback issues (where Flash player was requested instead of using the native FF player; you can try it on dailymotion.com because of their player policy). I've found that in all of my cases it was a problem with the browser detection routines used by websites. To fix that, I use the _Custom UserAgent String_ addon and with a custom UserAgent string set as (Windows 7 in my case):

`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0`

 That way, it is better for me ;-)

Maybe a UserAgent string setting could figure in the Waterfox settings (or somewhere else), such as Opera did in the past...

Regards,
Johan

**Comment by DxRaider099** [comment]
Before posting it, i've try to change the useragent string with an extension named useragent switcher and there is no change forms still stay broken and i've try to edit the useragent string directly on waterfox on the about:config page but same issue ....
So for the playback issue all work for me never have playback issue

**Comment by grahamperrin** [comment]
Thanks. 

Is the issue reproducible with Waterfox in safe mode?

Can you share the address of an affected forum?

Troubleshooting information will be useful. Text (not raw data) copied from: 

- about:support

**Comment by DxRaider099** [comment]
Ok, i've just test in safemode same issue,
Full report from about:support available here : 
https://pastebin.com/Gv9pQVBQ

Hope some data may help for fix :)

**Comment by DxRaider099** [comment]
Ok, i've just test in safemode same issue,
Full report from about:support available here : 
https://pastebin.com/Gv9pQVBQ

Hope some data may help for fix :)

**Comment by grahamperrin** [comment]
@DxRaider099 please did you find an explanation?

**Comment by DxRaider099** [comment]
@grahamperrin Sorry but no, just the 3/4 websites where i've previously show the issue no longer have it, cause i just close that topic.
The only clue i've is that may problably reliable to some javascript issue.

**Comment by grahamperrin** [comment]
OK 👍 thanks for the feedback.
