### ISSUE TITLE
staging: ?utm_source=www.mozilla.org

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#470]
From #469: 

> https://support.mozilla.org/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=fx-sub-nav

That source should ideally be amongst the Mozilla-isms that are to be removed.

**Comment by WagnerGMD** [comment]
Agreed I had discover this trouble a long time ago (more than 6 months). That's why I decide to use an addon (like [Request Control](https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/) and just in case if you need one example).

`https://outgoing.prod.mozaws.net [...]`
PS : Indeed that's another trouble on [AMO](https://addons.mozilla.org) (select one addon then check the links. And that's right, you could use it also to avoid this trouble).

**Comment by grahamperrin** [comment]
I sped through https://www.waterfoxproject.org/en-US/waterfox/features/ and a handful of other pages. At a glance I see no evidence of `?utm_source=www.mozilla.org` so I'll close this issue. We can reopen if necessary.
