### ISSUE TITLE
Storage Standard: browser.storageManager.enabled and dom.storageManager.enabled

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#506]
Consider changing the defaults from `false` to `true` for these two preferences: 

- browser.storageManager.enabled
- dom.storageManager.enabled

## Background

[Storage API - Web APIs | MDN](https://developer.mozilla.org/docs/Web/API/Storage_API) in particular [Browser compatibility](https://developer.mozilla.org/docs/Web/API/Storage_API#Browser_compatibility) note 3: 

> The Storage API is implemented and enabled by default in Firefox 57.

[Storage Standard](https://storage.spec.whatwg.org/)

A series of four results in the _web-platform-tests dashboard_ for WPT / storage: 

1. https://wpt.fyi/storage/?sha=b0c75cd885 including Firefox 56.0
2. https://wpt.fyi/storage/?sha=0860fcb11e including Firefox 56.0
3. https://wpt.fyi/storage/?sha=b467fe0c0b including Firefox 57.0
4. https://wpt.fyi/storage/?sha=e511e5e8af including Firefox 57.0

The great difference, for Firefox, between (2) and (3) was probably due to `browser.storageManager.enabled` and `dom.storageManager.enabled` being `false` in Firefox 56.0. 

The most recent result: 

- https://wpt.fyi/storage/

Some Mozilla bugs: 

- [1147820 - [meta] Improve Storage](https://bugzilla.mozilla.org/show_bug.cgi?id=1147820)
- [1254428 - Implement Storage spec](https://bugzilla.mozilla.org/show_bug.cgi?id=1254428)
- [1286717 - Expose persist/persisted method to StorageManager](https://bugzilla.mozilla.org/show_bug.cgi?id=1286717)  RESOLVED FIXED in Firefox 55
- [1354500 - Remove the proprietary persistent indexedDB permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1354500)
- [1421690 - (storage-v2) [meta] Storage (Site Data and Cookies) Management V2](https://bugzilla.mozilla.org/show_bug.cgi?id=1421690)
- [1428306 - Investigate removing browser.storageManager.enabled pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1428306) 

Storage Standard is mentioned in (not the focus of) two W3C documents: 

- [Clear Site Data](https://www.w3.org/TR/clear-site-data/)
- [Permissions](https://www.w3.org/TR/permissions/)

----

## Indexed Database (IndexedDB)

[Indexed Database API 2.0](https://www.w3.org/TR/IndexedDB/)

https://wpt.fyi/IndexedDB

**Comment by grahamperrin** [comment]
Plus today I stumbled across a post in mozilla.dev.platform, [Intent to unship: "storage" attribute in options for indexedDB.open() - Google Groups](https://groups.google.com/d/msg/mozilla.dev.platform/3b700_oeAzo/4hzZDEJQCwAJ) (2018-03-06), which described Storage Standard as a web standard that 

> specifies a better persistent storage mechanism and has broader vendor support

**Comment by WagnerGMD** [comment]
From another point of view (specially security or **privacy**), I won't recommand this change.

```
C:\Users\WagnerGMD\AppData\Roaming\Mozilla\Firefox\Profiles\6x9jwr02.dev-edition-default\storage\default\https+++www.youtube.com^firstPartyDomain=youtube.com\.metadata
C:\Users\WagnerGMD\AppData\Roaming\Mozilla\Firefox\Profiles\6x9jwr02.dev-edition-default\storage\default\https+++www.youtube.com^firstPartyDomain=youtube.com\.metadata-v2
C:\Users\WagnerGMD\AppData\Roaming\Mozilla\Firefox\Profiles\6x9jwr02.dev-edition-default\storage\default\https+++www.youtube.com^firstPartyDomain=youtube.com\idb\3211250388sbwdpsunsohintoatciif.sqlite
```
Because I'm wonder how Youtube was able to create these cookies ? It can't be ?
```
lockPref("network.cookie.cookieBehavior",2);
lockPref("network.cookie.lifetimePolicy",2);
## Because I had decide to block the cookies (I rather to define my own list of exceptions).
## At the contrary, it's a trouble since Firefox_v57 (the damn idiot at Mozilla sic... Because they forgot to provide one API (allow Cookies Exceptions) for WebExtension)
```
Well the answer seem's to be related to :
```
pref("dom.indexedDB.enabled",false);
pref("dom.storage.enabled",false);
## Open the Web Console (from the developer tools), you will see one message such as : "A mutation operation was attempted on a database that did not allow mutations" (etc)
```
But there is a bad point because (as you can see on [this picture](http://nsa39.casimages.com/img/2018/04/06/180406081952183565.png)) sometimes it will break a website (protonmail.com, mega.co.nz, etc)

**PS :** Another reason : no it doesn't seem to exist. No we don't have any good addons to control the both (switch on/off).
According to my memories, the last one was [Shim Storage](https://addons.mozilla.org/en-US/firefox/addon/shim-storage/) and it will need to be replace and improve ([Cookie Keeper](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) seem's to be also abandon (no news features)).

**HS :** Which post it was ? Nevermind because by the past (with Cyberfox under Windows), it has never help me.
```pref("memory.free_dirty_pages",true);```
Perhaps there is a difference related to the OS (FreeBSD, etc) ? I ignore but I had try several times and the result was always the same (none improvements).
In fact, the memory was improve a little when Firefox_v56 was published. And It was even better after with Firefox_v57 (aka Firefox Quantum) but I imagine it's might need again a fews improvements.

**Comment by grahamperrin** [comment]
Thanks, I'll continue testing (I set both preferences to `true` a few days ago). 

If I understand correctly, one of the apps that I use might switch to Storage Standard because of problems with IndexedDB.

**Comment by grahamperrin** [comment]
> `pref("memory.free_dirty_pages",true);`

@WagnerGMD there's a separate issue, 423: 

- memory.free_dirty_pages in Waterfox 56.x

> … how Youtube was able to create these cookies ? … 

This issue is primarily about `browser.storageManager.enabled` and `dom.storageManager.enabled`

**Comment by WagnerGMD** [comment]
I had try a few times but on the moment, I don't why I wasn't able to find it.
Thank you @grahamperrin, I will [keep it](https://github.com/MrAlex94/Waterfox/issues/423) (add to my bookmarks).

**Comment by hawkeye116477** [comment]
@MrAlex94 Any update to this? Seems that's uBO webext uses this also, if it's enabled, then it shows how many storage is used.

**Comment by MrAlex94** [comment]
Apologies, must have missed this! https://github.com/MrAlex94/Waterfox/commit/6f3f83685bdd12ff1d356c31d23eba08a8be4ae8

**Comment by grahamperrin** [comment]
I had forgotten this, too! I've been working without the features for the past eleven months. Now re-enabled.
