### ISSUE TITLE
Mega.nz high cpu usage before uploading file

### ISSUE THREAD

**Issue by nhantrn** [BrowserWorks/waterfox#526]
Don't know which version this problem arose but the latest WF56.1 has high cpu usage before uploading a file to mega.nz. Looks like it has something to do with encrypting workload? This doesn't happen in FF52 ESR. Did not try FF56.x. Issue is noticeable on large files.

**Comment by nhantrn** [comment]
Just tested FF56.x and it is affected too. So this is not a WF issue. I also went back to WF55.0.4 and it too was affected.

**Comment by grahamperrin** [comment]
> … something to do with encrypting workload? …

I don't use the service, but I would have the same guess. 

Have you sought advice from users of the service, or from the service provider?

**Comment by MrAlex94** [comment]
If you find a bug ID, please tag and re-open.

**Comment by Lorienna** [comment]
@MrAlex94 

Regression range:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=c35f0ad34397990adec0612015eb1a2a566434da&tochange=cf6065f64f9a8aef42144e7938c9c1aec92d8677


Fixed by:
[Bug 1397645 - Analyzing of large file upload on mediafire.com is too slow](https://bugzilla.mozilla.org/show_bug.cgi?id=1397645)

**Comment by grahamperrin** [comment]
Meta, tracking: #538

**Comment by grahamperrin** [comment]
@MrAlex94 would you like to reopen this? (Ordinary users can not.)
