### ISSUE TITLE
[Questions] Do the following effect waterfox?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [BrowserWorks/waterfox#543]
Hello there,

Just wanted to know if these userscripts are still necissary for Waterfox;
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts

These are essential to reduce identifiable information and don't break any browser functionality that I am aware of. I am still using Greasemonkey 3.17 for @run-at document-start, legacy extension function.

Hopefully this ticket isn't confusing and or considered spam. 

Thanks. :honey_pot:

**Comment by grahamperrin** [comment]
## rel=noopener

From one of the linked articles, [Web Security: add rel=noopener to external links - gHacks Tech News](https://www.ghacks.net/2017/01/24/web-security-add-relnoopener-to-external-links/) (2017-01-24): 

> … adding rel="noopener" to all links that open in new tabs and be done with it. Browser makers state that this will break certain sites and services on the Internet. … 

– with reference to Mozilla bug [1222516 - Implement rel=noopener](https://bugzilla.mozilla.org/show_bug.cgi?id=1222516),  RESOLVED FIXED in Firefox 52. 

Whether 'break' is an overstatement, I don't know. 

----

For what it's worth I have used [Don't touch my tabs! (rel=noopener)](https://addons.mozilla.org/addon/dont-touch-my-tabs/) since … I don't know when. Whilst I'm not aware of any issue with this extension, I _do_ sometimes find issues that I don't have time to diagnose. So it's possibly troublesome; and there's the acknowledgement that 

> some web applications make use of this function, it would break those
