### ISSUE TITLE
Close other windows and close tabs on the left

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#551]
Hello,

after all, there is already one function called **Move to New Window** and another one called **Close Tabs to the Right**.
Then I'm wonder if you could add another function to close the other windows (and just keep the main one) ? Because it's annoying to close manually every windows which was open by an adware (ads, popus, etc).
Why only the right side ? I don't understand why it doesn't exist for the left side. Do you believe you can add this function ?

Kind regards.

**PS :** Block ads with one addon ? Avoid this kind of advice because it's a bad one : no there aren't perfect (they don't block everything).

**Comment by hawkeye116477** [comment]
`PS : Block ads with one addon ? Avoid this kind of advice because it's a bad one : no there aren't perfect (they don't block everything).`
PS: Just use proper filterlists and ads should gone and if not, then report it to maintainers of filterlists. Nothing positive gives the use of many adblockers. There is no need to use ABP/AB + uBO, because uBO have rules that ABP/AB has and even more, so it blocks/hides more than ABP. So just use only uBO or Nano Adblocker, because they are the best. AdGuard is also fine, but again it supports own rules, ABP/AB rules and also some uBlock rules, some rules has different than uBO, but it doesn't mean that it can't block the same content as uBO, it just depends on maintainers to include proper rules in their filterlists. If you are missing some filterlist from ABP for example, then just subscribe it from URL :smile:.

**Comment by grahamperrin** [comment]
[Close Tabs Shortcuts](https://addons.mozilla.org/addon/close-tabs-shortcuts/) ▶ <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>F1</kbd>

**Comment by WagnerGMD** [comment]
First of all @hawkeye116477 I don't combine addon(s for the same thing). Nevertheless for the moment, I haven't yet made my choice. And tell me one thing : why did I choose to open this issue ? Because I didn't want to talk about addon(s and I assume no it isn't probably the right place). And if you need another reason : **my suggestion perhaps is just one attempt specially in the aim to improve Waterfox** (and a very little hope for Firefox).
No you're wrong (not today) because I had already think several times about this suggestion (at different moment over a year).

What's your call shortcut ? From my point of view, 2 is the good number (many people has various troubles (hands, memory, etc) and believe in the same fact : yes the keyboard one day need to be redesign).
**Pardon** @grahamperrin but did you read it carefully ? No well try again and take your time. Because no I had chose my words for a particular reason. That's right, I don't talk about the tabs but the windows itself. And no there aren't the same things (tabs != windows).
For the record, to close any tabs the shortcut (under Windows) is simple to remind : **ctrl + W**.

**Comment by grahamperrin** [comment]
> … did you read it carefully ? …

Yes, but (sorry) there seem to be mixed meanings. 

> … I don't talk about the tabs …

I read, amongst other things, first and foremost the subject line with this: 

>> ## … and close tabs on the left

– and: 

>> … for the left side. Do you believe you can add this function ? … 

– plus the question about ad blocking. So I understood that this issue was about at least three separate things, one of which isn't in the subject line, and my first comment was about closing tabs to the left.

**Comment by WagnerGMD** [comment]
All right @grahamperrin none problem.
In fact, sometimes I don't see the point to open several topic(s) instead of one. From my point of view, it's better to group them (in only one topic and it will be more easy to follow).
So that's right at the origin, there were three separate things and today I decide to add one more :
- **How are we suppose to extract the data ?**
- **How export them (in one file .txt, .json, .csv, etc) from "remember search and form history" ?** (I refer to the page **about:preferences#privacy**)

The only solution will be to install an addon (such as [SQLite Manager](https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/), etc) ? Unless there is another easier solution ?

Because I'm worry about this data and I just want to keep a backup (and no I don't want to use the sync).

**Edit 23 may 2018 :**
Explain me @grahamperrin if something is wrong ? Because I can't guess what you mean by the emoji.
And you can also try to answer to these questions. Because I don't have a clue on various matters...

From my point of view, don't forget **the main purpose** : it's just an attempt to help to improve Waterfox. Because I rather to write my ideas (or suggestions) instead of lost them (sometimes I have my own memories troubles).

**PS :** What's the trouble ? It's call issue but we can use it like any topic(s) to discuss.
Yes, that's true recently reddit has been improve (much better but the bugs remain) but I rather GitHub. At least, the markdown work's has expected and it doesn't seem to be buggy.

**Comment by Peacock365** [comment]
@WagnerGMD 

Don't worry, @grahamperrin dislikes people just for shits and giggles. He pulled the same move before:

https://github.com/MrAlex94/Waterfox/issues/545
https://github.com/browser-update/browser-update/issues/397

PS: I am sure this comment will receive yet another dislike from him (predictable behavior).

**Comment by MrAlex94** [comment]
I don’t care how angry you are about something, watch your language. I’ve edited your comment to remove profanity.

Your comment has also added absolutely nothing to this issue, please try and keep issues to relevant discussions.

**Comment by Peacock365** [comment]
@MrAlex94 

Perhaps you should tell @grahamperrin to stop downvoting people for no reason, thus making them angry in the first place. This, too, adds nothing to any issue except conflict. And while you are at it, please also tell him to stop opening issues for extremely minor stuff, thus inflating topics and rendering important stuff invisible.

PS: Why am I even contributing when this person receives backing for triggering other people. @WagnerGMD and I have both witnessed this nuisance already. You may call my reaction profanity, I call it the natural reaction to highly annoying behavior. @MrAlex94, after all it is your duty to stop it. Not ours, we don't even have the means. I will surely calm down once this annoyance has ended for good.

**Comment by MrAlex94** [comment]
Excuse me but this is NOT the way to do things. I have spoken with Graham,
but in private and more importantly I have done it kindly.

I do not care how annoyed you get, watch your language and just be nice to
other people. Now this topic is just getting derailed for no good reason.

**Comment by Peacock365** [comment]
@MrAlex94 

Well, I've said what I had to say, and you _should_ care about it, especially since I am not the only one massively annoyed by him. I now of course expect his spamming and downvoting behavior to improve, otherwise I see no reason to put up with him any longer, subsequently being banned by you for "profanity" as I deliver a well-deserved and still-too-friendly reply.

Fair enough, you have talked to him, hopefully he has learned his damn lesson, and thus we can return to the topic now.

**Comment by MrAlex94** [comment]
> subsequently being banned by you for "profanity" as I deliver a
well-deserved and still-too-friendly reply.
Excuse you, I have never banned anyone for speaking their mind - but I will
reprimand them for not acting professionally. Do you know the years of
horrid words I’ve seen working on Waterfox?

You want to be a part of this community (this applies to anyone), then I
expect everyone to be courteous and respectful to each other as they would
do so in a professional setting.

If you cannot keep your cool, then this is not the place for you to be. A
downvote or disagreement is not even in the same league as  hurling
profanities.

**Comment by Peacock365** [comment]
Yes, I want to be part of this community _without being triggered all the time for no reason at all_. His behavior is one big nuisance, and I have kept my cool the previous two times he downvoted me _just because the comment came from me_. Honestly, you would be pissed too if I'd follow every comment you publish and downvote it just for the sake of it. This is annoying at a massive scale and ultimately leads to me "hurling profanities" at this "special person". My behavior is fully dependent on whether or not he has learned something from you talking to him.

But hey, you have talked to him. I am fully expecting it to get better now. Hopefully he listens to you.

**Comment by grahamperrin** [comment]
> … @grahamperrin none problem. …

> … Edit 23 may 2018 …

@WagnerGMD sorry, I didn't see your edit, a month ago, until today. (I don't receive notifications when comments are edited; GitHub is not well-suited to such things, it's [not a discussion forum](https://github.com/dear-github/dear-github/issues/44).) 

Re: the other questions, I didn't reply partly because I didn't have answers; partly because some of them seem unrelated to the issue (Close other windows and close tabs on the left).

**Comment by grahamperrin** [comment]
> … annoying to close manually every windows which was open by an adware (ads, popus, etc). …

Mozilla bug [432687 - (eviltraps) [meta] Protect users from websites that trap them or destroy their experience](https://bugzilla.mozilla.org/show_bug.cgi?id=432687) (2008-05-07)

- P3 critical
- thanks to PadaV4 at https://www.reddit.com/comments/8sjdoz/-/e12lx04/?context=3 for direction.  

## [Clear Tabs](https://addons.mozilla.org/addon/clear-tabs/)

> … close all open tabs … except for your currently selected tab. Just click … 
> 
> Only tabs in the current Firefox window …

## [Close Other Windows](https://addons.mozilla.org/addon/close-other-windows/)

> … close all tabs in other windows which are not pinned

:+1: to respecting pinned tabs (good UX). 

@WagnerGMD an extension, or combination of extensions, might come close to what you would like. If you have not already done so, please consider asking in https://www.reddit.com/r/waterfox (and/or searching <https://www.reddit.com/r/firefox>) – other people in Reddit have far more experience, with extensions, than me. 

> MrAlex94 (Alex Kontos) added the [help wanted](https://github.com/MrAlex94/Waterfox/labels/help%20wanted) label 

HTH

**Comment by hawkeye116477** [comment]
In Classic Archive there is addon **Close tabs to the left**.
https://storage-waterfox.netdna-ssl.com/amo/xul/524/524118/close_tabs_to_the_left-1.2-fx.xpi?origin=caa&action=install

There is also webextension on https://addons.mozilla.org/pl/firefox/addon/close-tabs-left/?src=search.
