### ISSUE TITLE
Skia has just been updated to match release branch. Please build and test!

### ISSUE THREAD

**Issue by MrAlex94** [BrowserWorks/waterfox#553]
Hi everyone,

I've [tested out](https://stackoverflow.com/a/35914396/1154632) a new way to keep Waterfox up to date with various projects. 

This is quite a large change, and relates to anything canvas (including WebGL). Please test :-). Currently gfx/skia now matches the release branch of the Mozilla platform. I've done on my platform (macOS 10.13) and seems to work without issue.

Cheers!

**Comment by grahamperrin** [comment]
Thanks! 

Two questions, maybe both are stupid but here goes …

----

The two preferences `gfx.canvas.azure.backends` and `gfx.content.azure.backends` at about:config?filter=azure.backends – if a problem _is_ found with either canvas or content, then would it be sane to experiment with `cairo` in lieu of `skia` for that one preference?

(I never heard of [Skia](https://skia.org/) before today … reading this issue alongside old (2016) <https://forums.freebsd.org/threads/firefox-no-gpu-acceleration-since-50-0.59089/#post-338314>.)

----

If there's a choice of rendering back-ends (e.g. XRender | OpenGL 2.0 | OpenGL 3.1) for compositing, then should the updated Skia be tested against all back-ends?

**Comment by laniakea64** [comment]
So far so good in self build from https://github.com/MrAlex94/Waterfox/commit/941b28140102e33f968ad710548333aee9d1b618 running on Xubuntu 18.04 64-bit.  I play HTML5 games and haven't noticed any problems so far.

**Comment by Peacock365** [comment]
It‘s a great way to keep Waterfox up to date. No problems so far.

I must ask, however, is fixing all the issues mentioned in #538 still on your radar, @MrAlex94 ? I have gone to great lengths to find (hopefully) appropriate fixes for most issues...

**Comment by grahamperrin** [comment]
@Peacock365 if you must bump an issue, please do it in the issue (not in other issues). Thanks.

**Comment by jbeich** [comment]
Builds fine on FreeBSD [10.4 i386](https://ptpb.pw/lO51)/[11.1 amd64](https://ptpb.pw/TuYx).

> new way to keep Waterfox up to date with various projects.

Curiously, it exploded commit history.

```
$ git describe --tags edeb7e6627c40~1 --match 56.1.0
56.1.0-89-g2bb1a86e5dbd6

$ git describe --tags edeb7e6627c40 --match 56.1.0
56.1.0-111168-gedeb7e6627c40
```

**Comment by jbeich** [comment]
@grahamperrin, Skia m66 is part of freebsd/freebsd-ports@564a2bd3c851. Did you notice any stability/rendering regressions?

> if a problem is found with either canvas or content, then would it be sane to experiment with `cairo` in lieu of `skia` for that one preference?

Correct but some places use compile-time checks instead e.g.,

https://github.com/MrAlex94/Waterfox/blob/941b28140102e33f968ad710548333aee9d1b618/image/RasterImage.cpp#L1344-L1345

> If there's a choice of rendering back-ends (e.g. XRender | OpenGL 2.0 | OpenGL 3.1) for compositing, then should the updated Skia be tested against all back-ends?

- XRender is **probably** irrelevant: disabled due to unpredictable performance and interference with OpenGL
- Skia takes advantage of OpenGL compositing via `gfx.canvas.azure.accelerated=true` (aka SkiaGPU)

**Comment by grahamperrin** [comment]
Thanks Jan, thanks all. 

I began testing 56.1.0.111172, built locally, around an hour ago. 

(Poudriere is failing to fetch waterfox-56.1.0.111178, I'll ignore that for now, retry later.)

----

In my 'everyday' Waterfox profile,  

about:config?filter=gfx.xrender.enabled `true`

– I strayed from the default weeks ago, can't recall exactly when. I vaguely recall reading some of the reasons for it defaulting to `false` in Firefox, but I nearly always prefer XRender for desktop effects ‒ 

![2018-05-14 15 35 36 compositor system settings](https://user-images.githubusercontent.com/192271/40003989-a1aff054-578c-11e8-817c-db4be269e320.png)

– because whenever I tried OpenGL 2.0 or 3.1, things felt too rough. So I figured, go for XRender in <strike>Firefox</strike>Waterfox too. 

Now, for Skia test purposes: will it help if I enable a version of OpenGL in System Settings, and make `gfx.xrender.enabled` `false` in Waterfox? 

----

In my lesser-used 'minimal everyday' profile, 

about:config?filter=gfx.xrender.enabled `false`

– I had just one possible glitch. Maybe one tab blank after restoration by Session Boss, but the blankess was transient. An OWA log on dialogue. So far, not reproducible. 

----

Both profiles: multi-process disabled. 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% sh
$ date ; uname -v
Mon 14 May 2018 15:16:32 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ pkg info waterfox | grep Version
Version        : 56.1.0.111172
```

**Comment by grahamperrin** [comment]
> Skia takes advantage of OpenGL compositing via `gfx.canvas.azure.accelerated=true` …

I found it `false` in my 'everyday' profile. No idea when, why or how that happened but now it's reset to its default `true`.

**Comment by grahamperrin** [comment]
> … just one possible glitch. Maybe one tab blank after restoration by Session Boss, but the blankess was transient. An OWA log on dialogue. So far, not reproducible.

The symptom recurred a few hours ago, I paid closer attention. Simply sitting, watching and waiting for a short while (less than five seconds?) was enough for activity to visibly begin i.e. counter-clockwise spin of whatever it's called in the chrome of a tab. 

From what I saw of both incidents: I don't think it's a bug. 

----
