### ISSUE TITLE
56.2 breaks multi-process support on i7-5820k (Win10), leading to micro-stutters

### ISSUE THREAD

**Issue by flolilo** [BrowserWorks/waterfox#588]
**Hardware (Working):**
 - Intel i5-4210U
 - Intel HD4400
 - 8GB RAM

**Hardware (not working):**
 - Intel i7-5820k (latest stable BIOS)
 - NVIDIA GTX 970 (drivers: tried version 397.64 and 397.93, both installed cleanly)
 - 32GB RAM

**Software (same across both machines):**
 - Windows 10 Pro 64bit (v1803) w/ latest updates
 - Windows Defender Antivirus as only A/V solution
 - Waterfox 56.2, both installed (update) and portable (clean installation)
    - HTTPS Everywhere 2018.4.11
    - Kee 2.3.19beta
    - OpenDownload² 4.1.2
    - Privacy Badger 2018.5.10
    - uBlock Origin 1.16.8

**Problem:**
On my workstation, Waterfox 56.2 greys out and disables `Enable multi-process Waterfox`. `Content process limit` also is greyed out and set to `1`. Disabling the add-ons makes no difference, as does using a cleanly installed portable version (no add-ons, no existing profile).
Ever since I noticed this, I have (micro-)stutters (sometimes > 2sec.) and lags - these mostly occur when a demanding website (e.g. Facebook, but it also appears to happen with YouTube) has been open for a few minutes. The problem will not vanish when the tab in question is closed, but only when the browser is restarted. There is no difference whether I use 1 tab or 10 tabs (I usually use no more than 5).

Until Waterfox 56.2, everything worked properly.

On my notebook, everything appears to be working fine. The setup and workload is the same.

----

P.S.: I hope that I have not missed an existing issue here on GitHub. All of the multi-process related issues I found seemed to be linked to incompatible add-ons, which does not seem to be the case here.

P.P.S.: **I really appreciate your work with Waterfox.**

**Comment by WagnerGMD** [comment]
```
## Today I believe the solution is mostly about this first couple of settings :
lockPref("browser.tabs.remote.force-enable",true);
lockPref("accessibility.force_disabled",1);
## But in the case, you must check them too :
lockPref("browser.tabs.remote.autostart",true);
lockPref("browser.tabs.remote.autostart.1",true);
lockPref("browser.tabs.remote.autostart.2",true);
lockPref("dom.ipc.processCount",1);
lockPref("dom.ipc.processCount.web",4);
```
**Just about the PS** : no there is another reason. Because it (**e10s aka electrolysis**) could be disable by the **accessibility tools** which bugs again...
That's why, you must don't forget :
- to check the page **about:config**
- you will need to (re)create a new profil
- repeat the process several times ? Yes because (at the end) the trouble will be gone.

**Comment by flolilo** [comment]
Thanks. Will try that ASAP.

Maybe this should be in the Wiki or in FAQ?

**Comment by WagnerGMD** [comment]
You're welcome @flolilo and let me know if you need more information. Because the **accessibility tools**, sometimes this trouble is very annoying... Another example (as good things to know) : the browser must be configured directly (at the first one launch or before with one file such as the **mozilla.cfg**).

It could be one good idea but (at this moment) I believe : no it doesn't exist yet (for the both). Unless I miss it ? Right now, I didn't find them (on the [Waterfox GitHub](https://github.com/MrAlex94/Waterfox))...

**Comment by grahamperrin** [comment]
> … 56.2 greys out and disables `Enable multi-process Waterfox`. …

Try https://redd.it/7tupr8

**PS** sorry, the [view of this page was stale](https://redd.it/7wth86), comments crossed paths.

**Comment by flolilo** [comment]
Complete Walkthrough:

I saved @WagnerGMD 's code...

```javascript
//
lockPref("browser.tabs.remote.force-enable",true);
lockPref("accessibility.force_disabled",1);
lockPref("browser.tabs.remote.autostart",true);
lockPref("browser.tabs.remote.autostart.1",true);
lockPref("browser.tabs.remote.autostart.2",true);
lockPref("dom.ipc.processCount",1);
lockPref("dom.ipc.processCount.web",4);
```

... as `mozilla.cfg` (with `ANSI`-encoding) and put the file in my installation directory (`C:\Program Files\Waterfox`). Seems like everything now works as it should. Thanks again for helping me!

**Comment by WagnerGMD** [comment]
That's a good news :) !
If one day, you meet this trouble again let me know (and it will be the same if you have one question about this matter).
But I have a good hope : it won't be the case. Because for me these last months, it has totally vanished.

You're welcome @flolilo and thank you for the feedback (indeed I appreciate and one complete, it's even better).
