### ISSUE TITLE
[Request] Compact icons with Compact Light theme like in original Firefox

### ISSUE THREAD

**Issue by bastaynav** [BrowserWorks/waterfox#592]
Hello all! Sorry for my bad english:(

I liked Waterfox and I have one request — make icons and other elements in "Compact Light" theme smaller, like in the original Firefox. 

For comprasion: 
[Firefox](https://i.imgur.com/Uq96c27.png)
[Current Waterfox](https://i.imgur.com/cIhRMIL.png)

Toolbar in Firefox smaller and and me like this view. Thanks!

**Comment by criztovyl** [comment]
In-Line comparison:

![ff](https://i.imgur.com/Uq96c27.png)

![wf](https://i.imgur.com/cIhRMIL.png)

**Comment by criztovyl** [comment]
1st is FF, 2nd WF.
(It's `![alt text](https://i.imgur.com/image.png)`)

**Comment by bastaynav** [comment]
@criztovyl oh, thank you :)

**Comment by WagnerGMD** [comment]
Let's try to understand ! For you it isn't good enough the **small button** ?
Because you can **customize** (just open it) even the size of the button.

I had just check it and yes there is another way :
`pref("extensions.classicthemerestorer.smallnavbut",true);`
But for that you will probably need to install one addon such as the [Classic Theme Restorer.](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/)
Since several months, there is also another setting :
`pref("browser.uidensity",1);`

**Comment by bastaynav** [comment]
@WagnerGMD Oh, i missed that there's a standard setting. My bad. 

The question is solved, I close topic.

**Comment by WagnerGMD** [comment]
None trouble @Mockingj4y (it's a huge software and there are a lot of settings) and I'm just glad by the fact I was able to help you.
