### ISSUE TITLE
Waterfox performance and memory usage issues after using YouTube

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#606]
L-a-n-g-o-l-i-e-r-s wrote: 

> dom.serviceWorkers.enabled true for me results in "ghost window" (viewable in about:memory) from service workers related to outlook and youtube, they don't close/stop after the related tabs have been closed and remain open until the browser is entirely closed.
> 
> I noticed that when this happened my browser would progressively become more sluggish, experience lock ups and eventually the memory usage would climb to 1-2 gb. When I toggled dom.serviceWorkers.enabled to false, this behavior stopped entirely and WF was back to its usual snappiness.
> 
> For the record I am just looking for commiseration, not to submit an in depth report for lack of time. 😞

@L-a-n-g-o-l-i-e-r-s hi, taking as little of your time as possible I'll consider the YouTube aspect. 

Troubleshooting information, please. Text (not raw data) copied from: 

- about:support

Then: 

1. visit https://pastebin.ca 
2. paste the (troubleshooting) text to the paste area of the page
3. in the blue _details_ area below the paste area, expire the post in one month
4. click _Submit Post_ 
5. add the link to this issue. 

Thanks

**Comment by grahamperrin** [comment]
I experimented. 

YouTube with autoplay disabled.

Concurrent playbacks of https://www.youtube.com/watch?v=2cU56SWXHFw (10:44) and https://www.youtube.com/watch?v=Tot8Tf-jSQw (9:30) completed. Then with one or two other tabs open – probably including `https://github.com/MrAlex94/Waterfox/issues/581` – I closed both YouTube tabs. 

First about:memory measurement: https://pastebin.ca/4037401

Second about:memory measurement, 2018-06-06 00:44 (more than twenty-four hours after the first): https://pastebin.ca/4038061

> `0 ── ghost-windows`

– and no problem with memory.

An htop view of things at 00:45 – focus on process ID 2707: https://pastebin.ca/4038062

**Comment by WagnerGMD** [comment]
Accordind to my memories, this trouble was mentionned a few times :
- https://8pecxstudios.com/Forums/viewtopic.php?t=956
- https://8pecxstudios.com/Forums/viewtopic.php?t=937
- etc

How many ? I have forgot but I think there is at least 3 differents topics (good luck to find them)...

If you really want @grahamperrin to discover this bug, first of all you have to :

1. return in the past (you must (re)install one older version : before Firefox-v55 or Firefox-v56)
2. take any long video (at least between 2 and 6 hours)

To resume, the trouble about the Mozilla Leak Memory (specially on YouTube) has start to be rectify when **e10s** was include inside the browser.

**Comment by grahamperrin** [comment]
Thanks, neither of those topics mention ghost windows, and so on … 

At this point (in the absence of troubleshooting information) I'm taking care to not conflate what was reported with any other issue. There are _so_ many issues involving YouTube, many of which are extension-related …

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@grahamperrin https://pastebin.ca/4039028

This isn't during a test, I still have serviceworkers disabled. It wasn't just youtube as I explained another example was outllook.com having a ghost window which was a running service worker. It was not my intention to hijack the issue, only to find out if anyone else had similar issues to what OP put and perhaps missed some other symptoms that I might've been experiencing.

Currently I can see no benefit to leaving service workers enabled on my side, I notice no lost functionality when they are disabled and in my particular case, the better for it. It very well could be an extension, as so much has changed since I first started tolerating the issue (1-2 months ago) to narrow it down. I made a new profile and installed only what was required and I still had the issue. (The pastebin is from this profile.)

I considered for a moment that it might've been a userscript, but then, I don't have any for outlook, so that didn't make much sense.

**Comment by WagnerGMD** [comment]
You're welcome @grahamperrin but I don't believe : it was only one trouble related to any addons. Because as I remember even a clean (or new) profil (without any addons) wasn't able to povide any real solution for this troube (the leak memory require one huge amount of RAM, let's resume (or say at least) between 1 and 2 Go).
And could you explain me that ?
```
defaultPref("media.cache_readahead_limit",60);
defaultPref("media.cache_resume_threshold",30);
//##    Unless there is another trouble ?
pref("browser.cache.memory.max_entry_size",-1);
```
Change the value (for the both) because **Mozilla has made a very bad choice**. It will load faster and totally any videos (no delay, no wait, etc).
What's the correct name (bothering ? etc)... Sorry I had forgot but in fact, that's one solution to avoid this kind of trouble.

PS : I don't use **outllook.com** that's why I can't talk (neither provide) any opinion on this website.
But according to my memories, there is perhaps another trouble with those websites :
- [virustotalcloud.appspot.com](https://virustotalcloud.appspot.com/)
- [virustotal.com](https://www.virustotal.com/)
- etc

And itt was cause by one or the both settings ? Sorry I don't recall exactly... but the(se) website(s)  won't work if you disable it (unless you can find somewhere (another url for) the previous version).
```
pref("dom.serviceWorkers.enabled",false);
pref("dom.workers.enabled",false);
```

**PS :** After a few days, I had found the right (or correct) name it's the : **buffering**.

**Comment by grahamperrin** [comment]
Thanks, 

(**Correcting myself …**)

>> … When I toggled dom.serviceWorkers.enabled to false, this behavior stopped entirely … 

> … new profile and installed only what was required and I still had the issue. (The pastebin is from this profile.) …


For clarity – and this issue focuses on the experience with YouTube – your troubleshooting information at https://pastebin.ca/4039028 is an environment in which: 

- you found sluggishness, lock-ups and abnormally high memory usage during or after use of YouTube whilst `dom.serviceWorkers.enabled` was `true` 

– and issues with the new profile ended **after** you made the preference `false` as shown in https://pastebin.ca/4039028 … do I understand correctly? 

Thanks

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@grahamperrin 

The information collected is from the same profile I experienced the problems on, I installed only what I needed, I experienced the same issues until I turned off service workers. My browser would have high memory usage and freeze occasionally. 

I narrowed the problem down to service workers because I checked the memory page and saw "ghost window" listing outlook.com's service worker and in a separate instance youtubes service worker with a "ghost window" long after their respective pages had been closed. They remained as "ghost window" until the browser was closed. 

Once the browser was restarted "ghost window" was not present, so long as I avoided those websites with the service workers the browser was perfectly fine. Disabling service workers allowed me to use these services with no issue. :confused: 

It sounds like my issue is different from OPs so I hope I'm not derailing it. It's my opinion, besides my browser enviornment that there are some serious issues with workers. :no_good_man:

**Comment by grahamperrin** [comment]
> … sounds like my issue is different from OPs …

Only in that I opened the issue on your behalf :-) with your words – you **are** effectively the opening poster 👍 

Discussion of YouTube here (in this issue) is no way derailing. Thanks for taking the time to share information. 

----

If you wonder why I'm focused on YouTube in this issue, it's because the Outlook Web App that I use (with four different accounts, the nature of my work) is not in scope for any service worker. So I should encourage you to raise a separate issue for your OWA case; the two issues can be read alongside each other. 

----

If you'd like to delete your `https://github.com/MrAlex94/Waterfox/issues/581#issuecomment-394241425`, it will help to keep issue 581 on track. Thanks. 

----

For general pros and cons of service workers – without reference to any particular bug – over to issue 545, please. Also https://redd.it/8m1pxr although NB I'm [still awaiting responses](https://www.reddit.com/r/waterfox/comments/8m1pxr/service_worker_detection_in_waterfox/dzluv61/?context=2) in some areas.

**Comment by grahamperrin** [comment]
Of possible interest, historically, although the symptoms in 2016 seem quite different from what's reported in 2018: 

<https://mozilla.logbot.info/firefox/20161226#c360157> – <https://mozilla.logbot.info/firefox/20161226#c360228> 

@Timvde with the popularity of YouTube as a destination I imagine that there's a fix amongst Mozilla commits somewhere between Firefox 56.0.2 and the present. Or a clue within the troubleshooting information for this case …

**Comment by grahamperrin** [comment]
@L-a-n-g-o-l-i-e-r-s https://pastebin.ca/4039028 has expired, could you (again) let us have troubleshooting information? 

Plain text, please (not the _raw data_ button).

**Comment by grahamperrin** [comment]
Mozilla bug [1328622 - (ServiceWorkers-perf) [meta] Service Worker Performance](https://bugzilla.mozilla.org/show_bug.cgi?id=1328622)

**Comment by Timvde** [comment]
> @grahamperrin: @Timvde with the popularity of YouTube as a destination I imagine that there's a fix amongst Mozilla commits somewhere between Firefox 56.0.2 and the present. Or a clue within the troubleshooting information for this case …

Wait, what exactly does this have to do with me? Are you asking whether I know of a bug that recently landed regarding Youtube/service worker performance? I do not, sorry.

**Comment by grahamperrin** [comment]
@Timvde thanks, 

> … Are you asking whether I know of a bug that recently landed regarding Youtube/service worker performance? I do not, sorry.

👍 yep, that was the question. 

> … what exactly does this have to do with me? 

My bad! I misread the IRC log as you in conversation with purplex88. In fact it was Caspy7, not you. Sorry!

**Comment by grahamperrin** [comment]
A long shot (without reproducing what's in this issue, I can't tell whether it's _truly_ related): 

- [(Mozilla 1466606) audio/video playback: memory corruption issue causing various crashes · Issue #634 …](https://github.com/MrAlex94/Waterfox/issues/634)

**Comment by Squall-Leonhart** [comment]
Graham, the issue certainly seems to affect some html5 players more so than others, and non default threshold and readahead may be implicated

**Comment by grahamperrin** [comment]
Not reproducible (by me); if symptoms recur someone can post to Reddit, or open a new issue.
