### ISSUE TITLE
(Mozilla 1466606) audio/video playback: memory corruption issue causing various crashes

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#634]
Please consider patching Waterfox 56.x for Linux, Mac OS X and Windows. 

Rationale: 

- minimise the possibility of end users encountering issues that will be difficult to troubleshoot. 

NB I have only just begun testing the www/waterfox on FreeBSD-CURRENT that includes the patch. 

## References

Mozilla bug [1466606 - Crash in mozilla::Maybe<T>::ref (from TrackBuffersManager::GetNextRandomAccessPoint)](https://bugzilla.mozilla.org/show_bug.cgi?id=1466606&sourceid=Mozilla-search)

>  RESOLVED FIXED in Firefox -esr60

– <https://bugzilla.mozilla.org/show_bug.cgi?id=1466606#c34> in particular: 

> … crashes,memory corruption. It's very likely this bug is the core reasons for what would appear as unrelated crashes.

Changesets: 

- https://hg.mozilla.org/mozilla-central/rev/4c1f90791492
- https://hg.mozilla.org/mozilla-central/rev/033f5f2b2582
- https://hg.mozilla.org/mozilla-central/rev/1bdee3c3ca7c
- https://hg.mozilla.org/mozilla-central/rev/af8ba448f7d3

https://svnweb.freebsd.org/ports/head/www/waterfox/files/patch-bug1466606?view=markup&pathrev=472349 (2018-06-15) _www/waterfox: apply some FF61 fixes_

Meta, tracking: #538

**Comment by Squall-Leonhart** [comment]
Since upgrading to 56.2.9 from 56.2.7, I'm noticing that mp4uploads player is triggering a leak in the waterfox parent process.

This is strange as the gpu process is meant to be where the video decoding happens, and it is running as well as my other ipc processes.

However, i believe a change on mp4uploads player has facilitated the issue, and it might be related to the Trackbuffer manager as you cite, Graham.

@MrAlex94 can you backport the fix?

**Comment by MrAlex94** [comment]
Good idea - will get on this. Have added it to checklist.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/530933a750573b3bb2fa2f236b7a0376f0b411d6
https://github.com/MrAlex94/Waterfox/commit/bc0a41faa1c62cb8daf29a12708a02478dd11330
