### ISSUE TITLE
Make it easier to download and run executables

### ISSUE THREAD

**Issue by tuaris** [BrowserWorks/waterfox#642]
Mozilla Firefox tries to protect people from themselves by making it 'harder' to download and run an EXE file on Windows.  Its a pointless safety protocol that does more to annoy less tech savvy users that help them.  Take a a look at how Chrome, Edge and (yes) Internet Explorer handle this and apply that same approach to Waterfox.

**Comment by WagnerGMD** [comment]
```
lockPref("browser.safebrowsing.downloads.enabled",false);
lockPref("browser.safebrowsing.downloads.remote.block_potentially_unwanted",false);
lockPref("browser.safebrowsing.downloads.remote.block_uncommon",false);
lockPref("browser.safebrowsing.downloads.remote.enabled",false);
lockPref("browser.safebrowsing.malware.enabled",false);
lockPref("browser.safebrowsing.phishing.enabled",false);
```
Otherwise the easier solution consist to disable those setttings on the page **about:config**.
Then open the page **about:preferences#security** if you want (or need) to check it.

**PS :** The next time, at least try to search. Because the next time, I might decide to refuse to reply.
Because yes it's remind me another(s) topic(s) on the same matter (somewhere ? GitHub, reddit, etc) and the answer was nearly the same as today.

**Comment by MrAlex94** [comment]
Thanks for the help Wagner, I'll close this.

**Comment by WagnerGMD** [comment]
You're welcome @MrAlex94 !
