### ISSUE TITLE
Irritating question when visiting webmail site

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#680]
I keep seeing the question in the image which doesn't include the option to say "No". Even after clicking the Close button, the prompt returns on the next visit. 

According to Tutanota, it's not being generated by them. 

How can I prevent it from appearing? I've already tried using the Permissions menu, but none of the options serves to disable it. 
![annoying](https://user-images.githubusercontent.com/33827636/41898311-01628d54-792a-11e8-9152-f218ea7073a6.PNG)

**Comment by Telmesomething** [comment]
I tracked down the problem which is located in prefs. When `network.protocol-handler.external.mailto` is set to its default "true", the warning appears. 

Setting it to _false_ however prevents the site from loading. 

Here's the link to the webmail where this problem is occurring: https://mail.tutanota.com/

**Comment by WagnerGMD** [comment]
Because it isn't the same url  `https://app.tutanota.com/#login` ? That's why I had never met this kind of trouble.
So **I imagine** yes it could be the (or another one) cause.

**PS :** Which OS ? Which Waterfox ?
The next time I might refuse to reply because the people forget to provide these kind of informations (such as **version**, etc). Because that's true sometimes it could be very important.

But I had check it and apparently it could be a bad idea. Because the website can't be load (page white totally)...
`lockPref("network.protocol-handler.external.mailto",false);`

**Comment by Telmesomething** [comment]
> Because it isn't the same url https://app.tutanota.com/#login ? That's why I had never met this kind of trouble.

That's the link to the old version of Tutanota. The latest one is the one I provided the link to. 

OS is Windows 8.1 (up-to-date). Waterfox v56.2.1 (x64)

In order to get rid of the prompt I allowed it which adds Tutanota to the Applications | Mailto: list but it's not particularly desirable.

**Comment by grahamperrin** [comment]
Mozilla bug [668577 - registerProtocolHandler notification should provide a "don't ask me again" button](https://bugzilla.mozilla.org/show_bug.cgi?id=668577) (2011-06-30)

You can use e.g. this <strike>script </strike>style with legacy Stylish: 

_Suppress the 'Add application' banner for Tutanota_

```text
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

/*
Adapted from https://support.mozilla.org/questions/994658#answer-556629 
for https://github.com/MrAlex94/Waterfox/issues/680
*/

notification[label^="Add Tutanota"][value="Protocol Registration: mailto"] {
  display: none !important; 
}
```

**Comment by Telmesomething** [comment]
> You can use e.g. this script style with legacy Stylish

Thanks for the suggestion Graham, but there seems to be privacy issues with Stylish which I've come across before. The latest report on these can be seen in [this article](https://www.ghacks.net/2018/07/03/it-is-time-to-get-rid-of-stylish/) on the ghacks.net site which states that the addon sends the entire user's browsing history to the developer among other things. 

Anyway, I used the option to add Tutanota to the Applications menu, but then switched it back to Thunderbird. So far, I haven't come across any problems with it.

**Comment by WagnerGMD** [comment]
Do you have @Telmesomething a few articles about the "old and the new version of Tutanota" ?
Because no I wasn't aware and I want to know the difference (between them).

In fact, no you don't need any addon like **Stylish**. Because you should read [this topic.](https://github.com/MrAlex94/Waterfox/issues/563)

**PS :** No I refer only to the first part (inside the profil). To resume, the both files (**userContent.css** and **specially the userChrome.css** must be inside the folder called **chrome**)
By the way **Stylish** could be replace by another addon (such as **Stylus** if the name is correct ? Yes according to my memories).

Thank you @grahamperrin because I wasn't aware this kind of solution.
`lockPref("accessibility.blockautorefresh",true);`
Do you believe we could use the same thing about this one (the autorefresh) ? Because one day I will need to find one addon to replace [Refresh Blocker.](https://addons.mozilla.org/en-US/firefox/addon/refresh-blocker/)
And sorry but right now I'm very busy by one big **trouble IRL...** That's why I didn't yet answer or read the other topics.

**Comment by grahamperrin** [comment]
Legacy Stylish is fine, if you already have it.

[Stylish 3.1.1 block-listed and disabled, 2.1.1 enabled : waterfox](https://new.reddit.com/comments/8wd5wu/-/)

**Comment by maptracker** [comment]
I have been using Stylus for a year or two, it appears to be where the Stylish exodus is headed. Works flawlessly in Waterfox.

https://addons.mozilla.org/en-US/firefox/addon/styl-us/

They also provide [instructions for importing your Stylish library](https://github.com/openstyles/stylus/wiki/FAQ#how-can-i-export-my-user-styles-from-stylish-for-firefox-to-stylus).

**Comment by Telmesomething** [comment]
Thanks for all your replies guys, but I found it easier just to add it to the list of mailto applications and then switch the default back to Thunderbird. So now Tutanota appears in the list along with Yahoo and Gmail of which I don't have an account with.

**Comment by WagnerGMD** [comment]
Like I said, I had never met this kind of trouble (at least it was true by the past).
Now I think I had discover the reason : at this moment, I didn't proceed any update (my browser was probably **WaterFox_v56**. That's why I believe **this banner only appears with the latest releases** (such as  WaterFox_v56.1 or WaterFox_v56.2, etc).

PS : Which one precisely ? Basically I can't say because I don't know the answer. I don't want to try each release just to find the answer (and I'm too busy IRL).

**Comment by WagnerGMD** [comment]
`lockPref("network.protocol-handler.external.mailto",false);`
From my point of view, this the best solution. It was discover by myself a long time ago (at least one year) !

**PS : I will never forgot this lack of respect I** That's why I didn't reply before because I don't care about WaterFox and it didn't deserve anymore my help ! To resume, this a payback (and you can blame the author) !

**Comment by WagnerGMD** [comment]
`lockPref("network.protocol-handler.external.mailto",false);`
From my point of view, this the best solution. It was discover by myself a long time ago (at least one year) !

**PS : I will never forgot this lack of respect !**
That's why I didn't reply before because it didn't deserve anymore my help ! To resume, this a payback (and you can blame the author) ! Now I don't care about WaterFox I
