### ISSUE TITLE
Android: copy/paste not working

### ISSUE THREAD

**Issue by nharward** [BrowserWorks/waterfox#727]
Selecting text and long-pressing a text area does not show a popup menu, so copy/paste is - as far as I can tell - impossible. Tried experimenting with various clipboard settings in about:config but no luck. No problems copy/pasting in other apps.

Pixel running Android 9 build PPR1.180610.009, Waterfox 60.1.0esr.

**Comment by grahamperrin** [comment]
> Selecting …

A symptom of what may be an underlying issue: 

- it seems impossible to extend or contract a selection. 

(Testing with non-editable text; not tested in a form field.)

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by R-OLE** [comment]
This had the additional dimension that one can't (easily, at least) use a password manager, with lots of long random character passwords, since they can't be pasted using the pop up selection feature.
One work around is to use Hacker' Keyboard with it's Ctrl key... But that is really a WORK around, as the dimensions of that keyboard eclipses far too much of the screen and the buttons are way too small for fast comfortable use on most all phones.
This is a major obstacle to both fast causal browsing (pay walls) and to those doing work on the go (professional sites, posts to GitHub!!, Etc).
Please prioritize a patch for this issue.

**Comment by benryanau** [comment]
android plaform support needs attention

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

Should be fixed, please switch to the new app version! Also re-open if you still have issues.
