### ISSUE TITLE
default UI changes?

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#775]
Waterfox could change it's default UI a bit.Instead of been like a blue firefox. It would have it's own character.

I'm not saying rewriting features in C++, just change what is active by default. The kind of stuff classic theme restorer can already do. The addon cutebuttons have some nice pictures too.

For example, for me a more classic look would be nicer, a bit like seamonkey, or firefox before the mutations. Put back the addon bar, remove the hamburger menu, put back the classic search bar, the menu bar. A lot of people freaked out about curved tabs and their positions, so navigation bar on top and tabs bellow.....

All this assuming, that the changes don't brake addons....

**Comment by grahamperrin** [comment]
Mentions of Photon include: 

- https://www.reddit.com/comments/8hz93r/-/dyoabtb/
- [How to avoid Photon? · Issue #379 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/379) (closed)
- https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-376351366

From the latter: 

> … Firefox 57 … switch to Photon and removal of Australis, …

From [The Waterfox Blog | Waterfox, Its Legacy and Looking to the Future](https://blog.waterfoxproject.org/waterfox-its-legacy-and-looking-to-the-future): 

> … The future variant will be:
> 
> - Based on ESR releases
> …

Re: https://wiki.mozilla.org/Release_Management/Calendar the current extended support release is 60.3.

**Comment by ghost** [comment]
not sure what you are trying to say. I'm just saying to change the default appearance. Not just change the theme. Something like removing the hamburger menu, adding back the menu bar and addon bar and tabs going down.

Yes i know about classic theme restorer, i'm proposing to make some of these changes the default.

**Comment by chang-zhao** [comment]
> Something like removing the hamburger menu, adding back the menu bar and addon bar and tabs going down.

I think the problem is in keeping the **independent development**.

Let me start from some history of browser wars.

In 2010, there was a very popular browser, Opera 10 - fast, convenient and beautiful. Opera  was first to implement some features like multi-tabs etc. It had immense popularity: in some countries it was **the most popular** browser (like 45%).

Then something happened.

I think, Google had invested (or "donated") some money into Opera development. (Perhaps something else happened too, but I'm not going to speculate).

Coincidentally _(sarcasm)_, next versions of Opera became dramatically less usable. On some important web sites, you just were unable to login. Many users (myself included) reported bugs to Opera developers, but they **were not going to fix it**.

They claimed that their browser just became more standard-compliant, and it was a duty of those web site developers to improve their standard compliance.

As the result, the popularity of Opera fell from ~45% in some countries (and about 30% overall) to something like several percents.

Eventually, Opera was redesigned on the basis of Chrome engine; it became just another clone of Chrome, and generally users saw no more reason to use it.

Soon something happened to Firefox.

Google donated some money for Firefox development. Firefox guys frantically started to make new releases. From some theoretical point of view, new releases made often might be good, but from the point of view of end users it's a pain in the ass, because every time you waste your time for upgrading - when you actually just wanted to do some web browsing.

The popularity of Firefox was based on its immense extensibility. In the end of 2009, Firefox was the most popular browser in the world (32%), rivaled only by Opera. But with the fast upgrades, add-ons' authors had to change their add-ons very often, to keep with latest browser changes.

Imagine that you did something useful and handy (a Firefox add-on or several of them), and after that you planned to enjoy your improved life, and enjoy gratitude from others. But instead you have - again and again - to upgrade your add-ons just to make them work again... And instead of gratitude you get hundreds of "What the hell! Your sh*t doesn't work again!"

And if you are a user, then upgrading your Firefox often, every time means that some of your add-ons, a lot of which you have carefully installed and tuned, stop to work - demanding a lot of painful sex with your computer.

No wonder that Firefox popularity started to drop, and many add-on authors just were tired and stopped to upgrade them.

Moreover, eventually the brave developers, supported by our kind benefactor Google, have changed the interface to Australis.

We all know the reaction of users was not favorable. Everybody demanded to give us our carefully tuned browser environment back.

But no, they were not going to do that.

Basically they gave 2 explanations:

(1) the new interface was tested and had positive feedback. I have no idea how they tested it, but 'positive feedback' was obvious bullsh*t, considering the reaction of all the users.

(2) They said they had too little resources to maintain 2 separate versions, desktop and mobile; so they moved to one version with uniform interface. Which means "hamburger menu", no add-on bar, and all that other sh*t.

Strangely, they had resources for that frantic racing of upgrades. Wouldn't it make sense to do the opposite? Indeed: mobile interface is not so good on a large desktop screen - that's a certain fact!

With Australis, the popularity of Firefox fell dramatically, just like it happened with Opera before.

The only one who benefited from that was Google Chrome browser. In 2009 it was a new and very ugly program, with poor interface and built-in spying on users. Chrome browser logged every web site and every link you visited and sent all that to Google servers.

I think it was more like proof-of-concept than actually competitive browser. But, over time, Google invested in Chrome; they developed faster engine... and they finally made its main competitors to become basically Chrome clones.

They still spy on users, and they manage to do that even through Opera, Firefox and other browsers. Look in your browser "Options > Security > Block dangerous and deceptive content". If this option is checked - which is by default - it means for every web site you go, your browser sends your link to Google servers "to check if they are malicious". This way all you do in the internet gets monitored and collected, and then your behavioral models help advertising corporations and governments to manipulate you and control your life. Which means, for example, devising better tricks to make you waste your money.

Now, how is it possible to have convenient browser, like we had before Australis?

If it becomes convenient, it becomes popular - which means starting to compete with Google Chrome.

Palemoon tried that, retaining qualities of "Firefox before Australis". But eventually Palemoon had to become its own branch, with its own development. It cannot keep the old interface on the basis of Mozilla code, when Mozilla moved so far away from XUL etc (without any sensible reason, of course).

In other words, either you follow Google-sponsored developers who crazily try to spoil our interface, or you have to develop your own browser yourself. And in this latter case you would likely have to implement yourself all those new web technologies (which develop very quickly) and deal with the fact that most add-on developers would work for FF and/or Chrome, not for your endeavor.

That's how I see the situation - though I would like to be wrong about it.

**Comment by ghost** [comment]
don't post so long comments. And it's also out of topic.... -_-

google chrome won, because google pushes it very hard on their site... Good luck trying to compete with that. The others cut their own noses by them selves. 

Also, it's not possible, to have both an extensible and a fast browser. You are forced to make a trade off. It boils down to, what you value most....

Mozilla decided they needed a faster web browser in order to compete with chrome... and that could happen only by doing what they did...

waterfox is in a niche. It's an extensible web browser. It will never be the fastest. I'm proposing to change some defaults, to clearly differentiate it from the clones of chrome.

**Comment by chang-zhao** [comment]
@pirate486743186 My comment was on topic and just the right size to explain the difficulty we face here, with its historical reasons.

Simply put, either you follow the mainstream, or you need to maintain all the deviations by yourself.

Suppose you include some add-on functionality as the default config in your fork. When (soon) some upgrade of Firefox breaks that functionality, you would have to repair it.

It can be hard, and repeating that again and again can be frustrating.

> Also, it's not possible, to have both an extensible and a fast browser.

I disagree. For example, maintaining XUL interface wouldn't significantly slow down the browser, because that part rarely needs to be repainted. Also, both FF and Chrome are extensible nowadays.

**Comment by ghost** [comment]
I was just saying in this issue, to change some default cosmetic stuff. I'm not saying to do important changes. As for the long term viability of this project.... that's an other issue entirely....

web extensions are less invasive then classic addons. The window of old firefox, is basically a strange web page, with javascript and CSS. Plus other internals that are in javascript. Addons are basically additional javascript for this "webpage". This way you can do profound changes. About speed, here you have a ton of javascript, that must compete with compiled code (chrome)... That can't be done.... It boils down to, what you value more.

**Comment by grahamperrin** [comment]
@chang-zhao (at least) Google Safe Browsing is entirely off-topic.

OT commentaries can/should be moved to Reddit; discussion and corrections there, please.

----
