### ISSUE TITLE
links for more search engines

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#780]
in about:preferences#search

"Add more search engines..." should be replaced by a text and two links

specifically to mozilla website
https://addons.mozilla.org/en-US/firefox/search-tools/

and also to mycroft project
https://mycroftproject.com/
(that i think is far superior in this regard)

**Comment by Ibuprophen** [comment]
I looked into this and it does look like a good idea! :-) 

Here's some additional information that, I hope, can/may/could be helpful:

https://addons.mozilla.org/en-US/firefox/addon/mycroft-project/

https://github.com/Smile4ever/mycroftproject-query

https://github.com/utylee/bookmarks/blob/0beb51a49f47ecec2e57a1e560e952dbe7e937e4/firefox-default-search-bar.html

[mycroft_search.xml.txt](https://github.com/MrAlex94/Waterfox/files/2544145/mycroft_search.xml.txt)


~Ibuprophen

**Comment by WagnerGMD** [comment]
Otherwise you can also use the :
- [Qwant Qwick](https://help.qwant.com/help/qwant-search/searching/how-use-qwick/)
- [DuckDuckGo Bang](https://duckduckgo.com/bang) 
- etc (I guess similar page might exist but I don't know them)

From my point of view, the syntax is very simple to use and to remember.

**For the record :**
```
## In this example, it will replace the default search engine (Google by DDG).
defaultPref("browser.search.defaultenginename",'data:text/plain,browser.search.defaultenginename=DuckDuckGo');
```
