### ISSUE TITLE
hulu live tv

### ISSUE THREAD

**Issue by Commissar0617** [BrowserWorks/waterfox#797]
i don't know if anyone else is having this problem, but the new versions of hulu (live TV) requires location access through your browser. it seems to not be working properly on waterfox, as the site will just sit and spin like its loading, but never loads. hulu support was unable to identify an issue on their end,a nd it works in chrome just fine.

**Comment by Ibuprophen** [comment]
I think that this possibly due to either the lack of, missing or outdated DRM Widevine Decryption within Waterfox. 

I can't be positive myself since I don't use this. I remember someone mentioning this recently regarding both the Waterfox and Pale Moon Browsers. 

I just thought that I'd mention it here to help out the Developers in some way for a resolution. 

Good Luck! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/8xt831/-/e2aekc2/>: 

> Waterfox on Windows and macOS uses the operating system's location function. On Linux it's provided by GPSD `geo.provider.use_gpsd`, assuming you have it set up. There is no Mozilla Location Service fallback.

**Comment by Commissar0617** [comment]
ok, the workaround in about:config works there. is blocking/dysfunction of geoip services intentional?

**Comment by ghost** [comment]
it's deactivated by default for privacy concerns...

**Comment by grahamperrin** [comment]
@pirate486743186 thanks. 

@Commissar0617 would you like to close this issue?

Meta, tracking: #582 in particular https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-398939358
