### ISSUE TITLE
Concerns about purpose of Waterfox.

### ISSUE THREAD

**Issue by hoolaly** [BrowserWorks/waterfox#813]
According to the palemoon developers, the purpose of waterfox is to make profit and to run a business. is this true?

one of them said "I warned him about the size of the task of it when he chose to go it alone instead of working with us, and all I got was a high and mighty attitude about running a business."

**Comment by hoolaly** [comment]
i like the idea of waterfox, but this makes me feel a little bit uneasy about it

**Comment by MrAlex94** [comment]
Very strange, I found it to be the other way around. I wasn't the only one to contact Pale Moon either, and they are the ones who plan to completely fork and maintain XUL which seems rather unrealistic - but so be it, they're free to do whatever they like!

Also I have never been high or mighty about the work it takes, what a strange comment. To each their own I suppose, but seems rather telling of the kind of attitude they take towards other open source projects. I mean, that is the point isn't it? I really am taken aback as I've only ever been pleasant towards any other outside projects. 

Regardless, the only business aspect of Waterfox is the search partnership; and that isn't even forced on anyone (am I not mistaken in that Pale Moon uses start.me, which is much more invasive? How is that any different?). Regardless, I have no feud with anyone, but I don't appreciate issues like this being created either, I'm not quite sure what purpose it serves but to create hostility?

At the end of the day, I volunteer almost all my time to developing Waterfox and its various aspects and I have a search partnership which isn't forced on anyone to support that. The fact that other developers are so hostile or rude is nothing I can control unfortunately. Now as this isn't an actual issue with Waterfox, I've closed it but you can keep on commenting if you'd like since it has already been created.

**Comment by hoolaly** [comment]
thanks for addressing it, i appreciate it. didn't mean to create hostility, was just confused.
this is where i found it btw. https://freenode.logbot.info/palemoon/20180204#c1421207 , there's also some other stuff unfortunately ( https://freenode.logbot.info/?q=waterfox&ch=palemoon&w=a )

**Comment by hook321** [comment]
Personally I would just try to ignore it.
