### ISSUE TITLE
Can Waterfox benefit from Librefox improvements?

### ISSUE THREAD

**Issue by WPFilmmaker** [BrowserWorks/waterfox#827]
Seems that a new soft-fork privacy-oriented FF was created: https://www.ghacks.net/2018/12/24/librefox-firefox-with-privacy-enhancements/ github page is here: https://github.com/intika/Librefox

Seems that a lot of its good sides come from: https://github.com/ghacksuserjs/ghacks-user.js

Among their improvements: 
-User settings updates: gHacks/pyllyukko base is kept up to date.
-Settings protection: important settings are enforced/locked within mozilla.cfg and policies.json, those settings cannot be changed by addons/updates/Firefox or unwanted/accidental manipulation.

My question is, can Waterfox benefit from any of their improvements? Is there they implement which currently Waterfox doesn't?

**Comment by ilikenwf** [comment]
Porting what's there and works should be as simple as merging into the repo or just copy/paste where appropriate...

Going forward, when Waterfox is no longer using XUL, the librefox stuff will be an even better idea since more...nastiness by the "totally not for profit" nonprofit Mozilla has become keeps bolting stuff on.
