### ISSUE TITLE
bad pdf text rendering

### ISSUE THREAD

**Issue by shiftyshady** [BrowserWorks/waterfox#837]
pdf text rendering is bad on Waterfox (at least running on a Win 10 device), as compared to text rendering of normal html files.
I have tested a few browsers; Firefox 52 and 60.4 ESR renders pdf text OK. Firefox 54, 55, 56 renders badly, similar to Waterfox. The worst is Firefox Developer Ed 56.

waterfox:
![waterfox](https://user-images.githubusercontent.com/30387970/50727109-fdb11a00-110d-11e9-85f3-458e9d497922.jpg)

Firefox 60.4 ESR:
![60 4 esr](https://user-images.githubusercontent.com/30387970/50727118-1c171580-110e-11e9-8969-337e3979b7a4.jpg)

Firefox 54:
![54](https://user-images.githubusercontent.com/30387970/50727122-26391400-110e-11e9-970d-62b815e93377.jpg)

Firefox 56 Developer Edition:
![56 dev ed](https://user-images.githubusercontent.com/30387970/50727133-3a7d1100-110e-11e9-8c03-70ad04a0cbb1.jpg)

Any clue on how to make Waterfox render pdf like FF ESR?

**Comment by grahamperrin** [comment]
> … Firefox 54, 55, 56 renders badly, similar to Waterfox. …

> … Any clue on how to make Waterfox render pdf like FF ESR?

RESOLVED FIXED in Firefox 57: 

- [1391484 - Update pdf.js to version 1.9.441](https://bugzilla.mozilla.org/show_bug.cgi?id=1391484)

RESOLVED FIXED in Firefox 60: 

- [1433810 - Update pdf.js to version 2.0.303](https://bugzilla.mozilla.org/show_bug.cgi?id=1433810)
[1435814 - Update pdf.js to version 2.0.332](https://bugzilla.mozilla.org/show_bug.cgi?id=1435814)
- [1442785 - Update pdf.js to version 2.0.402](https://bugzilla.mozilla.org/show_bug.cgi?id=1442785)

I don't imagine a simple fix for Waterfox 56.x. @Ulf3000 any thoughts?

Reading this alongside [Search doesn't work on PDFs viewed via PDF.js · Issue #296 · Quicksaver/FindBar-Tweak](https://github.com/Quicksaver/FindBar-Tweak/issues/296)

If it helps, from <https://github.com/MrAlex94/Waterfox/tree/051177fe7df0c23b54b625968aa7611bd76b2112/browser/extensions/pdfjs>:

> Current extension version is: 1.8.618
> Taken from upstream commit: 21cc2c02

### Notes and workarounds

[PDF.js/fonts - MozillaWiki](https://wiki.mozilla.org/PDF.js/fonts) is old (2011). 

[How to increase print quality of PDF file with PDF.js viewer | Gyrocode.com](https://www.gyrocode.com/articles/how-to-increase-print-quality-of-pdf-file-with-pdf-js-viewer/) (2018-03-04) was about version 1.9.426 of PDF.js but focuses on print (not screen). 

https://www.google.com/search?q="PDF.js"+%2Bquality+-print only one result, loosening the query to https://www.google.com/search?q="PDF.js"+%2Bquality finds (strangely) not much more; https://www.google.com/search?q=PDF.js+quality finds millions of results. 

----

I reckon, the quickest/simplest workaround is to open the PDF in a better viewer. Disallow automated updates to extensions, then try legacy version 6.8.6 of **Open With**: 

- caa:addon/open-with
- or http://web.archive.org/web/20181017010510/https://addons.cdn.mozilla.net/user-media/addons/11097/open_with-6.8.6-fx+sm+tb.xpi?filehash=sha256:c5886be956dd8e94dd563130bfc2284ea5a0fbe529f22ce13d997dbbe7ee61cc

– you might find [7.0.3](https://addons.mozilla.org/addon/open-with/versions/?page=1#version-7.0.3),<strike>for Firefox Quantum</strike> which is also compatible with Waterfox 56.x, less simple to configure and use.

**Comment by Ulf3000** [comment]
on my pc its sharp 
![clipboard image 8](https://user-images.githubusercontent.com/10765339/50901436-70750a80-1418-11e9-97d2-b76edad207e0.png)

for upgrading downgrading , one could try to replace pdf.js (i dont know if it works though , i cant test right now , i have lots of work on my hands at the moment) 

the path is resource://pdf.js/  , it sits somewhere inside the omni.jar in your waterfox install folder, so either replace it there and try (WORK  WITH A BACKUP OF omni.jar IN ANOTHER FOLDER!!!)   or write a simple override extension and pack the other pdf.js version with it  

but i guess flipping the some config could do this too i think theres a force text optimization somewhere , but this could also be linux mac pc related ,i dont know sorry .. i think its sufficient either way though , just install foxit reader or something , thats much better for pdf handling anyways

**Comment by grahamperrin** [comment]
Thanks

https://bitcoin.org/en/bitcoin-paper ▶ English original https://bitcoin.org/bitcoin.pdf

- creator: Writer
- producer: OpenOffice.org 2.4
- format: PDF v. 1.4
- seven fonts, TrueType, embedded (subset)
- looks OK to me in Waterfox 56.2.6 on FreeBSD-CURRENT.

**Comment by shiftyshady** [comment]
Thanks for looking into this. It was very confusing.

about:config setting "privacy.resistFingerprinting" was causing the blur on my waterfox and firefox 56 dev ed. 
I can't reproduce the problems with firefox 54, 55, 56. I was testing clean profiles, so I guess the slight blur was due to having changed monitors with different resolutions during the tests without rebooting Windows.

Actually, the reason I started to look at this was the bad rendering of text of pdf with inverted colors (white on black). ClearType is to blame in this case. 
Firefox 52 somehow disables ClearType on pdf files while it keeps it enabled elsewhere. I would like to replicate that. Perhaps with a tampermonkey script. Or maybe simply move to a 4K display and disable Cleartype completely. I believe with sufficient dpi cleartype becomes useless.
