### ISSUE TITLE
Mac dictation program.

### ISSUE THREAD

**Issue by moonmorph** [BrowserWorks/waterfox#85]
When trying to use the Mac dictation to speak a single comment. Water fox  Will read the whole page every time. This causes an issue for those who are blind and dyslexic because we don't want to listen to the whole page every time when we are just trying to hear one comment.

**Comment by MrAlex94** [comment]
@moonmorph, does this issue still occur?

**Comment by moonmorph** [comment]
yes

**Comment by MrAlex94** [comment]
@moonmorph, do you have Electrolysis enabled? You can check by going about:config and searching for:

browser.tabs.remote
browser.tabs.remote.autostart

If they are set to true then that means you do. Set them to false by double clicking them and then restart Waterfox. Could you then test?

**Comment by moonmorph** [comment]
One of the browser.tab.remotes was labeled false and one was labeled true.
Switch the one to false. Then try to have the computer read a single
sentence on a Facebook page it's still tries to read the whole entire page.

**Comment by grahamperrin** [comment]
Tested with a selection of text from `about:profiles` on build 16G1205 of Mac OS X 10.12.6. This bug is: 

- not reproducible with Firefox ESR 52.5.3
- reproducible with Waterfox 56.0.2, multiprocess disabled, in safe mode
- not reproducible with Firefox 57.0.4. 

I can't find a comparable bug in Bugzilla@Mozilla. 

----

Historical: Mozilla bug [1003452 - Text to Speech API on Firefox for Mac](https://bugzilla.mozilla.org/show_bug.cgi?id=1003452) was

>  RESOLVED FIXED in Firefox 44

**Comment by grahamperrin** [comment]
Not reproducible with Waterfox 56.0.3 on Mac OS X 10.9.5 (I can't recall the address of the page that I used for the test) …

**Comment by grahamperrin** [comment]
The same Waterfox 56.0.3 (the same Mac) with a different OS, slightly outdated pre-release build 17D25b of Mac OS X 10.13.3: 

- if a text selection is made at **about:profiles** then the speech is not limited to the selection
- if a text selection is made at https://www.waterfoxproject.org/blog/waterfox-56.0-release-download then there's the same issue (plus, for me, an extraordinarily long delay before speech begins – and speech continues long after all windows are closed – but (off-topic) those delays are probably because I chose to use Apple File System on a hard disk drive in an already constrained test environment).

**Comment by moonmorph** [comment]
Still an issue, mac os 10.13.2, waterfox 56.0.3

**Comment by grahamperrin** [comment]
Cross reference [Voiceover in macOS not working : waterfox](https://redd.it/7uhefb)

**Comment by qahtani** [comment]
I'm running Waterfox 56.0.4.1 under macOS 10.12.6. When I trigger voiceover I get a notice that says, "Accessibility support is partially disabled due to compatibility issues with new Waterfox features." It will read that alert, and then proceed to read the entire page in full regardless of what text was highlighted. I tested it with the about:profiles page.

**Comment by MrAlex94** [comment]
Please use Waterfox Current for accessibility.
