### ISSUE TITLE
Update Promise implementation to be spec compliant

### ISSUE THREAD

**Issue by charlag** [BrowserWorks/waterfox#857]
**Describe the bug**
Waterfox uses old Firefox Promise implementation which is not spec-compiant.

**To Reproduce**
```js
var request = window.indexedDB.open("toDoList", 6);
request.onupgradeneeded = (event) => {
	console.log("onupgradeneeded")
	let db = event.target.result;
	db.onerror = (event) => console.log("fail", event);

	try {
		db.deleteObjectStore("toDoList");
	} catch (e) {
	}
	db.createObjectStore("toDoList");
	console.log("created object store toDoList")
};
console.log("opening");
request.onsuccess = (event) => {
	console.log("opened");
	let transaction = event.target.result.transaction("toDoList", "readwrite");
	let objectStore = transaction.objectStore("toDoList", "readWrite")
	objectStore.add({id: Date.now()}, Date.now());
	console.log("added 1")
	transaction.onerror = (event) => console.error("transaction error", event)
	transaction.onabort = (event) => console.error("transaction abort", event)
	Promise.resolve()
	       .then(() => objectStore.add({id: Date.now()}, Date.now()))
	       .then(() => console.log("added 2"))
	       .catch(error => console.error("failed write", error));
}
```

**Expected behavior**
Microtask is scheduled in the same event loop and transaction is not commited when `then()` callback is run.
Actually it is scheduled to the next event loop and transaction is already commited at this point.

**Desktop (please complete the following information):**
 - OS: Intel Mac OS X 10.10; rv:65.0
 - Version: 56.2.7

Relevant Bugzilla issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1193394#c16

Waterfox and Pale Moon share the same problem inherited from Firefox. We've already applied workaround for Pale Moon but we would like to eventually get rid of it because it is not very reliable either:
https://github.com/tutao/tutanota/issues/1088

**Comment by MichaelViV** [comment]
It is because of this I can’t SIGN UP / LOGIN on Waterfox Classic in tutanota.com??? If yes, then I confirm the presence of a bug.

**Comment by charlag** [comment]
It's not. It's in the indexing and we have workarounds.

**Comment by wolfbeast** [comment]
I suggest wontfixing this. This is _not_ a spec compliance issue and "non-Chrome-equal" doesn't mean "not spec compliant".
See the big warning at the bottom of WHATWG HTML spec [§8.1.4.3] (https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model). **Per spec**, user experience and the resulting implementation trumps strict adherence to the step order because it implies pausing.

**Comment by charlag** [comment]
Do as you like (I don't anticipate this to be resolved ever to be honest) but there's a reason why Webkit, EdgeHTML and Gecko all fixed their implementations. Yes, Chrome got it right but unlike some other things this is not "just" to be Chrome.
This blog post: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ goes into detail of why and how.
I would also recommend trying to write the app which uses IndexedDB with such Promise implementation and seeing how fun it gets.

**Comment by wolfbeast** [comment]
You know, anyone can write a program using a specific feature to "prove" why that feature "must" be there or some implementation is "the right one". That doesn't mean a thing.
I can make a website that only renders correctly in my browser; that doesn't mean all the others are wrong.

In this case though, the spec is absolutely clear and specifically states that web designers must not rely on specific sequences of timing events here because the client vendors not only are given precedence here in how they implement this but in fact are encouraged to experiment with different timing implementations to find the one that works best (i.e. with the least detrimental effect for performance) for their code.

I don't expect this to be resolved in the various clients either. What I do expect is that in the case of this out-of-the-ordinary explicit spec warning, that web developers **heed** it and find other ways to perform the same tasks that are currently problematic that do **not** rely on one particular implementation. There are plenty of ways to resolve IndexedDB calls that do not hit this particular snag, and whatever solution that is would surely be a lot less work and have a lot less impact than clients trying to rewriting their entire event scheduling or introducing detrimental pauses just to cater to one website (who is the odd one out, really?)

**Comment by charlag** [comment]
Anyone can write a program which won't work but maybe you can write complex indexedDB program which does?
The spec does not emphasize it enough, unfortunately, but the fact is that if the spec is not followed closely enough it makes Promises incompatible with IndexedDB and this is pretty [widely acknowledged](https://dexie.org/docs/Promise/Promise) (who is the odd one, really? the most popular IndexedDB wrapper of course).
You are using the same arguments - IndexedDB can be used anyway and it will somehow magically introduce lags into the browser. But there's really no real-world scenario other than IndexedDB where someone would want to execute many asynchronous tasks inside one event loop. If the page is lagging, shame on me, because it will be the same in every other browser. IndexedDB should be accessed from the worker in any case.
It would be *amazing* to not rely on particular scheduling and it would also be absolutely cool to have less broken transaction semantics but here we are.

I will not argue further, it's in vain in any case, I think we will see if people will add hacks for 0.001% of browser share.

**Comment by wolfbeast** [comment]
IndexedDB is used in many, many web applications that have no issue with the way this is implemented by us. Don't pretend that your specific scenario written one particular way is the only real use for it, because that's being awfully narcissistic.
But I'm done; you're clearly not interested in listening to valid arguments because it would mean you actually have to rethink your implementation, and you're never going to do that. Ohwait, I've seen that before, it's exactly the way Chrome devs approach their browser development. I guess you make a nice pair, then.

Alex: apologies for the noise on your repo; this would have been better discussed on an open forum or in a mailing list but it just happens to have developed here. I won't post any further on this issue.
