### ISSUE TITLE
Re-add about:config preferences that Mozilla removed

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#869]
Mozilla has a habit of stripping out many about:config options because they oftentimes see them as only being useful for testing purposes, or don't see a point of the preference existing because most users wouldn't use it. Stripping out preferences makes the browser less customizable, which in my opinion isn't the direction we want to go.

Some of the preferences that have been removed used to be used or could be useful in projects like ghacksuserjs (https://github.com/ghacksuserjs/ghacks-user.js), and other browser customization projects.

Some examples of preferences that have been removed, just off the top of my head: plugins.enumerable_names, browser.tabs.animate, dom.enable_user_timing

**Comment by WagnerGMD** [comment]
I will assume you are probably not aware about this one :
`lockPref("toolkit.cosmeticAnimations.enabled",false);`

Because Mozilla has chose to rename and combine those settings :
```
lockPref("browser.tabs.animate",false);
lockPref("browser.fullscreen.animate",false);
```

PS : Another bad news because Mozilla has modified the page **"about:config" and it's a crap...**.
At least for the moment (with Firefox-v67), the previous one still exist at this adress : **"chrome://global/content/config.xul"**.

**Comment by hook321** [comment]
I heard that there was a preference to disable all or most browser animations, but even combining them and removing the individual prefs takes away customizability.

**Comment by grahamperrin** [comment]
I'd like these two: 

`datareporting.sessions.current.firstPaint`

`datareporting.sessions.current.sessionRestored`

– probably defaulting to `0`. 

Please, note, the intention is **not** to report data. 

It's to regain compatibility with a legacy extension that seems to require the presence of the preferences. Related: 

- https://github.com/MrAlex94/Waterfox/issues/874#issuecomment-469075532
