### ISSUE TITLE
reCaptchas cannot be solved/verified

### ISSUE THREAD

**Issue by DerGolgo** [BrowserWorks/waterfox#871]
When forced to solve a reCaptcha, this is never accepted. Clicking "verify" _always_, with no exception, results in "please try again". Whatever is protected by that reCaptcha cannot be accessed. The issue is _not_ the user's error in solving the reCaptcha: Solving reCaptchas works **fine** in Firefox 65.0.1, on the same sites where it is not possible with Waterfox.

Problem **persists** when starting Waterfox with **all addons disabled**, in **safe mode**.

**To Reproduce**
Problem was observed on several websites, including the demo.
Go to: https://www.google.com/recaptcha/api2/demo
Solve the reCaptcha, click "verify".

**Expected behavior**
When solving the reCaptcha, and clicking "verify", this should be accepted, and whatever is protected by the reCaptcha should be available/should happen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809
- Build 17763.316
- Waterfox 56.2.7.1

**Additional context**
I first observed the problem yesterday. Maybe the day before. I have to switch to Firefox to get past reCaptchas. I had to do this several times, and tested it on the demo (URL above).
I had updated to the latest Waterfox version on February 21.

**Comment by grahamperrin** [comment]
### Firefox

> … Solving reCaptchas works fine in Firefox 65.0.1, …

Not necessarily. 

Three successive failures: 

#### 2019-02-22T07:41:55Z

![2019-02-22t07 41 55z 0 1](https://user-images.githubusercontent.com/192271/53455846-d6970a80-3a23-11e9-8d53-3dd04d23b6c8.png)

#### 2019-02-22T07:40:18Z

![2019-02-22t07 40 18z 0 3](https://user-images.githubusercontent.com/192271/53455867-ee6e8e80-3a23-11e9-8e84-105c17c03815.png)

#### 2019-02-22T07:43:50Z

![2019-02-22t07 43 50z 0 3](https://user-images.githubusercontent.com/192271/53455875-f9292380-3a23-11e9-87f3-9d5ba98b5fd8.png)

**Comment by grahamperrin** [comment]
### Waterfox

> … works fine in Firefox 65.0.1, on the same sites where it is not possible with Waterfox. …

An example of Waterfox succeeding where Firefox failed: 

#### 2019-02-25 20:12:26

![2019-02-25 20 12 26 waterfox recaptcha v3 success with tracking protection](https://user-images.githubusercontent.com/192271/53455938-3c839200-3a24-11e9-9ce8-db33c0b02429.png)

**Comment by grahamperrin** [comment]
26th February: 

> … first observed the problem yesterday. Maybe the day before …

Did you try any of the supposed bypass extensions that were suggested on the 22nd? 

(Please refrain from trying them. For now, I'd just like to know whether you used any of the extensions before problems began for you.)

**Comment by grahamperrin** [comment]
### reCAPTCHA v2 demo

> Go to: google.com/recaptcha/api2/demo
> Solve the reCaptcha, click "verify".

Verified, success. A frame from a screen recording: 

![2019-02-27 00 27 23 frame](https://user-images.githubusercontent.com/192271/53456746-65f1ed00-3a27-11e9-9b9b-7c07070a537b.png)

The recording: 

[2019-02-27 00:26.zip](https://github.com/MrAlex94/Waterfox/files/2908072/2019-02-27.00.26.zip)

FreeBSD-CURRENT.

**Comment by WagnerGMD** [comment]
**In fact, this version of recaptcha is very very very poor because it always buggy (pictures vanished, etc).**
That's why no you're wrong because this trouble doesn't only concern Waterfox.

The cause could be :
- VPN
- useragent
- DNT (aka DoNotTrack)
- Cookies
- Referer
- Addons
- etc

One or several settings ? I don't have a clue because the people forgot to provide this kind of informations.
To give one example, you can take a look on reddit (etc), you might found a few topic about this boring trouble...
```
https://www.google.com/search?q=site:reddit.com/r/firefox+recaptcha&tbs=qdr:y
https://duckduckgo.com/?q=site:reddit.com/r/waterfox+recaptcha
https://www.google.com/search?q=firefox+or+waterfox+recaptcha+buggy&tbs=qdr:m
https://duckduckgo.com/?q=firefox+or+waterfox+recaptcha+buggy
```

**Comment by grahamperrin** [comment]
> … the people forgot to provide this kind of informations. …

<https://www.reddit.com/comments/amy85w/-/efrg8om/>: 

>> Same issue with new profile.

We have a wealth of information in that post and its commentary.

Producing an issue with a new profile can be a strong indicator of a bug – I, too, can produce the issue with new profiles in Firefox and Waterfox – however: 

- the issue is **not consistently** reproducible.

I should not expect consistency, predictability, with reCAPTCHA. 

To people who find a problem with reCAPTCHA, my strongest advice is: 

- please, resist the urge to 'pick' at the problem. 

In my experience, **unnatural** attention to reCAPTCHA **significantly** increases the likelihood of presentation of CAPTCHAs that will be difficult and/or time-consuming. 

Don't actively seek the problem. 

Browse naturally. 

I have a sixty-nine minute silent screen recording of me finding problems and many (maybe most) of these problems were caused by me. This would be _truly_ boring to watch `:-)` – I have no plan to share/publish the recording. Just one snippet, a few seconds, is special: it proves to me that now – as in the past (over a year or so) – reCAPTCHA can be **extraordinarily user-friendly** with Waterfox.

**Comment by DerGolgo** [comment]
> 
> 
> 26th February:
> 
> > … first observed the problem yesterday. Maybe the day before …
> 
> Did you try any of the supposed bypass extensions that were suggested on the 22nd?
> 
> (Please refrain from trying them. For now, I'd just like to know whether you used any of the extensions before problems began for you.)

No, I have tried none of them.

I will pick away at the problem, because I am confronted by reCaptchas pretty much daily, and having to switch browsers each time one comes up is unacceptable to me.

**Comment by DerGolgo** [comment]
And now, badda-boom-badda-bing, I was able to solve a reCaptcha on the demo site and it was accepted.

I had tried different third-party-cookie settings. Didn't help, so put it back to "never" accept them.
Then I tried setting the proxy from "system proxy" to none. But then realized that the VPN I do sometimes use (and that wasn't involved in this whole conundrum) uses that, so immediately set it back to system proxy.

I had the demo site open, still, and had decided I would try it with the VPN turned on. But before I turned on the VPN, I solved it once more, just out of habit. And suddenly, it is accepted. Got it accepted on another try.

I didn't actually change any settings, but now it works again. 
And now I gotta figure out how to mark this bug as "not really a bug" or however (1st time I ever reported anything on Github).

**Comment by WagnerGMD** [comment]
I have read a lot topic over the internet (these last years). That's why no @grahamperrin  you didn't understand **my point : I wasn't only talking about this report !** So please the next time follow **my advice : stop the down emoji then read again my post and take the time to think.**

~~Recaptcha ? Extraordinarily user-friendly ? Is that a joke ? (No need to answer)~~
In fact, it was true with the previous version. But as today, it's a total mess... How many months ?  I didn't count but very often **no recaptcha doesn't work at all.** It can't be ? No I wasn't joking about the picture (which vanish) because there is bug somewhere...  

At the contrary, I rather the system on the [website filecrypt.cc](https://filecrypt.cc/). Because when recaptcha has totally failed, there is another kind of captcha which works very fine.

**Comment by grahamperrin** [comment]
> take the time to think.

**Comment by ghost** [comment]
Hello. I've exact same problem with waterfox.
I try with Konqueror and captcha is sovled about 2/3 "next", in waterfox required about 10/15 next to resolve.

I not use VPN, i try with clean waterfox profile (waterfox --ProfileManager), things unchanged. :-\
I try also to change user agent, nothing changed.

I think no make sense so differences between two browsers on same pc/ip.

**Comment by DerGolgo** [comment]
And today, I, too, am having this problem again. Can't solve a reCaptcha in Waterfox, no matter how much or how often, clicking "Verify" is always followed by "Please try again".
While it works in Firefox. 

Edit: to go and test the reCaptcha demo, I restarted Waterfox with addons disabled, in safe mode. And it worked. Restarted with everything enabled again, it worked again.

I reopened this issue and will leave it open for now. Unpredictable behavior is an issue, imo.

**Comment by grahamperrin** [comment]
[Captcha's have gotten ridiculous : firefox](https://www.reddit.com/r/firefox/comments/9zysar/captchas_have_gotten_ridiculous/)

**Comment by grahamperrin** [comment]
> a reCaptcha

Can you let us have the address? Thanks.

**Comment by DerGolgo** [comment]
> 
> 
> > a reCaptcha
> 
> Can you let us have the address? Thanks.

Whoops, my bad.
T'was hence:
https://obofood.de/registrieren.php

Just went there again, tried it, no joy.
Also just went and tried the demo (see OP for link). Obviously, that one would work. Can't have any kind of consistent behavior. I guess Google need some way to train their autonomous-driving AI system. But this is indeed ridiculous, at this point. When I've hit comment on this, I'll restart without addons, in safe mode, to try that last link once more.

**Comment by DerGolgo** [comment]
Phenomenal. Now it works in both safe mode and with all my addons enabled.

Am I going crazy here?

**Comment by ghost** [comment]
Hello. I've try captcha in your link for another test, and I do not resolve it too after 10 more screen.
Then I try with konqueror and I get to resolve it after first, yes, first screen. :-\

I think maybe a good idea try an old waterfox version to see if there are some differences, but I do not find a linux package of it.

**Comment by grahamperrin** [comment]
[Eighteen days ago](https://github.com/MrAlex94/Waterfox/issues/861#issuecomment-464279520) (2018-02-16), in another reCAPTCHA-related issue: 

> … I reported to [the reCAPTCHA Google Group](https://groups.google.com/forum/#!forum/recaptcha) but my post has not yet appeared. 

Still no trace of my post. 

2018-02-20: I sent an e-mail to reCAPTCHA support. No response. 

Some other relevant items …

----

**reCatpcah v3 identifies legit users a bots** ▶ [my question to the opening poster](https://groups.google.com/d/msg/recaptcha/5_4YdUZD8PM/t3fNxixPBwAJ) – no response. (The sole response is not an answer to the question.)

----

[**recaptcha v3 returning 0.3 or 0.1 or sometimes 0.9 : not working correctly**](https://groups.google.com/d/msg/recaptcha/TzsnUmBO9c0/FCwiiRjkBwAJ) – whilst I can not comment on correctness, I do sometimes see those three scores – the variation – in a single session with a browser. 

----

[**Remove 'bot' in recaptcha v3**](https://groups.google.com/d/msg/recaptcha/j5d-GXL_zt0/8fPr9o8fCQAJ) 

> Is it possible to make a user, that is marked as a bot, a 'normal' user?

> … I tested so many times the recaptcha that my score is 0.1 (so a bot). And on my website you will only be able to submit the form when the score is 0.5 or higher.
> 
> How can I remove myself (and in the future customers) who aren't a real bot from the list (if you can call it a list?!)?

**Comment by grahamperrin** [comment]
### _reCAPTCHA demo_ at https://recaptcha-demo.appspot.com/

Testing with this UA string: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9 Waterfox/56.2.7`

reCAPTCHA v3 results seem to be close to perfect …

**Comment by MrAlex94** [comment]
Hmm, what do you reckon would be a good overall UA to use?

**Comment by grahamperrin** [comment]
### _reCAPTCHA demo_ continued …

More use of [Custom UserAgent String](https://addons.mozilla.org/addon/custom-user-agent-revived/) 0.1.7. For this round of tests I used a new profile. 

As before, ~56.2.7.1 on FreeBSD-CURRENT. 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9 Waterfox/56.2.8`

#### v3

0.7 (success) x10

- IIRC most of the results for an earlier round https://github.com/MrAlex94/Waterfox/issues/871#issuecomment-472649814 were higher successes e.g. 0.9
- the lower-rated successes, for a new profile, didn't surprise me. 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9 Waterfox/56.2.7`

#### v3

0.7 x8

0.1 x2

- one of the two rose to 0.7 with a retry
- the other rose to 0.9 with a retry. 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9 Waterfox/56.2.8`

#### v2 "I'm not a robot" checkbox

10/10 succeeded, 9/10 with a single array of images. 1/10 required a second array. Later tests were more difficult than the first (e.g. one used grainy images), this didn't surprise me. I expected the next round to be similarly more difficult. 

#### v2 "I'm not a robot" checkbox - Explicit render

9/10 succeeded and as expected, there were increases in difficulty and tedium. One of the nine required more than three arrays of images. In the tenth I made a mistake so without attempting to recover, I reloaded the page and got a success without difficulty. 

#### v2 Invisible

10/10 succeeded. Some slightly difficult images.

**Comment by ghost** [comment]
Very strange, but for me seems working adding "Waterfox/56.2.8" to user agent, no differences changing other UA parts, but adding that captcha seems solved more fast. :-\

Also when I try with old waterfox version I get sometimes (not always) more fast solving.

**Comment by grahamperrin** [comment]
> for me 

With which version of Waterfox, exactly?

(Distribution of 56.2.8 has begun.)

**Comment by grahamperrin** [comment]
### Waterfox 56.2.8

To anyone who found issues with reCAPTCHA with 56.2.7.1, please:

1. update to 56.2.8
2. if you previously set a user agent string for an affected site, **cease the override**
3. tell whether things are better with 56.2.8. 

If you do find a problem, please state: 

- the version of Waterfox
- the operating system
- the version of the OS
- the address where the problem occurred

– and then (the earlier advice): 

- please, resist the urge to 'pick' at the problem.

Thanks

**Comment by DerGolgo** [comment]
Updated Waterfox.
Found the problem occurred again, on cryptopia.co.nz
Then tried the demo at https://www.google.com/recaptcha/api2/demo and it worked fine.
Then I tried cryptopia.co.nz again, and that worked also, this time.

Not sure whether I still have a problem.

Waterfox 56.2.8
Windows 10
Version 1809; or 10.0.17763 Build 17763 (got different things displayed in different places, as Windows does)
Address where problem occurred (and then didn't): cryptopia.co.nz

**Comment by WagnerGMD** [comment]
Just to give another few recent examples :
- [Destroy the evil Google Recaptcha](https://old.reddit.com/r/firefox/comments/b4bmbd/we_need_to_do_everything_we_can_to_destroy_google/) (and for me too, it has become to sound a very good idea)
- [which remain buggy](https://old.reddit.com/r/waterfox/comments/b64p3b/damned_multiple_captcha/) (even today)
- we mght need another addons to [solve this puzzle](https://old.reddit.com/r/firefox/comments/b5gmcx/is_there_an_addon_which_blocksautosolves_captachs/) (apparently it doesn't exist yet)
- etc

The trouble is also visible on any website **Idealo** (such as [idealo.de](https://www.idealo.de/) etc). The main reason ? Sometimes it's obvious : just avoid to use a VPN.

Another reason ? Even if you disable (modify etc) the VPN., it won't change anything... 
**Because Recaptcha doesn't work at all** despite the update.

What can I tell to help ?
- Waterfox-v56.2.8
- Windows 10 version 1607
- No the useragent wasn't modify
- I didn't try another profile because Waterfox doesn't provide any tool to [backup](https://github.com/MrAlex94/Waterfox/issues/563) and [restore](https://github.com/MrAlex94/Waterfox/issues/583) the data

**Comment by grahamperrin** [comment]
> I didn't try another profile 

Create a new profile.

**Comment by MrAlex94** [comment]
This should be resolved now I believe. Any extensions/network connections causing the issue aren't related to Waterfox.

**Comment by DerGolgo** [comment]
It is resolved. Since the update, I had no recaptcha shenanigans anywhere.

**Comment by MrAlex94** [comment]
Excellent! Google really have made it such a hassle.

**Comment by bgvtest** [comment]
I had this problem on version 2020.03, but I solved it by using the audio captcha.
