### ISSUE TITLE
Firefox better for privacy than Waterfox?

### ISSUE THREAD

**Issue by dm17** [BrowserWorks/waterfox#920]
Here's a discussion I started:
https://github.com/privacytoolsIO/privacytools.io/issues/856

It doesn't seem to have much support from Waterfox users; perhaps you can add your main arguments for Waterfox over Firefox for privacy?

**Comment by angela-d** [comment]
It's not that there isn't support, there's been some big threads that beat the subject to death and moderators simply won't link the forks: https://github.com/privacytoolsIO/privacytools.io/issues?q=waterfox

The motivations of Waterfox devs over Mozilla are both *very* different.

Nothing stops Alex from one day being bought out or persuaded, but he's also had no scandals, whereas Mozilla has had (and continues to have) many.

Waterfox also didn't partner with Google.

The primary argument against Waterfox seems to be "How many developers are there / slower security patches" type stuff.

Quality over quantity, right?

There's a small group of people that merge commits over there and they have odd reasoning (if any at all) for posting Brave but not something like Waterfox.  Because of Brave's commercial nature it is very curious.

**Comment by dm17** [comment]
I didn't realize it had been suggested so many times before. It seems pretty valid to be skeptical of PTIO when they refuse to reveal their arguments for recommending mainstream privacy-violating software.

**Comment by angela-d** [comment]
Alot of users over there have a serious hate-on for Pale Moon, too.

Arguments against Pale Moon always go back to PM's use of "old Firefox" as the base, which is most definitely ridicule coming from people that aren't developers themselves.  (The Linux kernel of today is using code bits from 1991.. with their logic, this is a glaring issue, right??)

If a browser was written from scratch today and released tomorrow, that would be one I'd be most skeptical of, opposed to one with tried and tested code.


This is also interesting:
> Pale Moon is too small to be added to PTIO imo.
>
> This thread is very long so the Waterfork/IceCat discussion should be moved to a separate thread imo.

So Pale Moon is too small, but Waterfox was still encouraged to be discussed.  Again, very weird stuff.

I really like PTIO, so I am not intending to dump on them, but I've grown "interested" in how content on that site is handled.  There's really not much point in debating on anything over there if you're serious about content being added or changed.  Even if there's a majority consensus, if a moderator doesn't agree, they will let the thread die out and then silently close the issue.

Options are good, they're (privacytools.io) supposed to be a guide of sorts - shouldn't a guide offer as many relevant *options* and present users with pros/cons of those options and let the informed users choose for themselves?

There's nothing inherently wrong with either Waterfox or Pale Moon with regards to privacy, yet they chose a browser that bases its existence around ad injection as an offering, built on an engine from enemy number 1 when it comes to privacy (Google).

**Comment by Petros606** [comment]
Still wondering myself after the bug that shut off FireFox add-ons: 

As of this date only FireFox users who have latest version 66.0.4 can download add-ons at the Mozilla website. Waterfox and older FireFox versions get a message that says, "Download Failed. Check your Internet connection." Looks to me like they've created an incentive to encourage FireFox users to get the latest edition for plugin access. Anyone who prefers older version of FireFox or Legacy plugins still can't use them without a fix, and FireFox doesn't seem to be too concerned. That's why I just switched my browser to Waterfox. It just looks to suspicious to me.

**Comment by dm17** [comment]
> Still wondering myself after the bug that shut off FireFox add-ons:
> 
> As of this date only FireFox users who have latest version 66.0.4 can download add-ons at the Mozilla website. Waterfox and older FireFox versions get a message that says, "Download Failed. Check your Internet connection." Looks to me like they've created an incentive to encourage FireFox users to get the latest edition for plugin access. Anyone who prefers older version of FireFox or Legacy plugins still can't use them without a fix, and FireFox doesn't seem to be too concerned. That's why I just switched my browser to Waterfox. It just looks to suspicious to me.

Totally... PTIO needs to come to terms with this... This is just another example that has happen just right now that did not affect Waterfox et al. PTIO...?

**Comment by grahamperrin** [comment]
OT from privacy, 

> suspicious

I think not. If you haven't already seen it: 

- https://discourse.mozilla.org/t/-/39047/23?u=grahamperrin
