### ISSUE TITLE
"Waterfox Current" is support "description" in bookmark?

### ISSUE THREAD

**Issue by ChiaYen-Kan** [BrowserWorks/waterfox#921]
Hi
"Waterfox Current" is support "description" in bookmark?
https://support.mozilla.org/ja/questions/1232882

i story many notes in "description", if "Waterfox Current" don't support "description", i will lost this notes
thank you

**Comment by grahamperrin** [comment]
From https://www.mozilla.org/firefox/62.0/releasenotes/#changed for Firefox 62.0: 

> Removed the description field for bookmarks. Users who have stored descriptions using the field may wish to export these descriptions as [html](https://support.mozilla.org/kb/export-firefox-bookmarks-to-backup-or-transfer) or [json](https://support.mozilla.org/kb/restore-bookmarks-from-backup-or-move-them#w_backup-and-restore) files, as they will be removed in a future release.

Associated Mozilla bugs: 

- [1276819 - Support bookmark descriptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1276819) (RESOLVED WONTFIX)
- [1402890 - Stop supporting and remove the description annotation](https://bugzilla.mozilla.org/show_bug.cgi?id=1402890) (RESOLVED FIXED in Firefox 63)
- [1467131 - Clean up bookmark annotation data once annotations have been removed](https://bugzilla.mozilla.org/show_bug.cgi?id=1467131) (NEW)

The dependency tree for 1467131 includes some interesting bugs.

**Comment by ChiaYen-Kan** [comment]
Hi
i know bookmarks can be export to html/json
but i can't see it in bookmarks, can't modify it in bookmarks again 
thank you

**Comment by MrAlex94** [comment]
I'll add this to the checklist.

**Comment by ChiaYen-Kan** [comment]
> 
> 
> I'll add this to the checklist.

Hi MrAlex94
the description of bookmark is will be removed from Waterfox Current ?
thank you

**Comment by p1usminus** [comment]
Hi,

I was wondering if this is still planned?

Thanks

**Comment by grahamperrin** [comment]
Cross reference [Bookmark Descriptions in Current : waterfox](https://old.reddit.com/r/waterfox/comments/fcpg3x/bookmark_descriptions_in_current/)

I assume that Firefox Sync will not support synchronisation of descriptions. If anyone discovers otherwise, please add a comment. 

----

@ChiaYen-Kan or @MrAlex94 you might like to edit the subject line of this issue. Instead of: 

> "Waterfox Alpha for v68" …

– it should (now) be: 

> Waterfox Current …

Thank you

**Comment by ChiaYen-Kan** [comment]
@grahamperrin:
i change title and issue of description to "Waterfox Current"

**Comment by AkazaAkarinn** [comment]
Any news on this? This feature is what is preventing me from making the switch to Current.

**Comment by AkazaAkarinn** [comment]
I think we can consider this feature dead. I've brought up the subject several times on the subreddit and @MrAlex94 has never responded. As much I'd like this feature returned an affirmative no would have been nice.

**Comment by Striker243** [comment]
This would be really sad as I am also halting my upgrade to Waterfox Current because I would lose hundreds of descriptions :(
