### ISSUE TITLE
Amazon prime not working again

### ISSUE THREAD

**Issue by Clydefrosch22** [BrowserWorks/waterfox#927]
useragent override doesn't seem to work, neither with the provided 65.0 setting, nor changing it to 66.0

**Comment by grahamperrin** [comment]
<strike>https://amazon.co.uk/gp/video/detail/B00X674KKU/ref=atv_dp_pb_core?autoplay=1&t=0</strike> https://www.amazon.co.uk/gp/video/detail/B00X674KKU/ ▶ aim for the trailer (worked with pre-release 56.2.8)

56.2.9 on Manjaro Linux: 

![image](https://user-images.githubusercontent.com/192271/56864431-09289980-69ba-11e9-85df-03dfc65c2132.png)

**Comment by grahamperrin** [comment]
Outdated 56.2.8 <strike>seems to no longer play the content</strike> mixed results. First this: 

![image](https://user-images.githubusercontent.com/192271/56864527-5ce7b280-69bb-11e9-9578-673f1e120566.png)

– then this: 

![image](https://user-images.githubusercontent.com/192271/56864544-7ee13500-69bb-11e9-8e47-29d5182962b9.png)

Later, this: 

![image](https://user-images.githubusercontent.com/192271/56864623-ad134480-69bc-11e9-8f53-d52f31a82f02.png)

#### Postscript

Hmm, it seems that 56.2.8 and 56.2.9 on Manjaro **can** play the trailer (without showing a DRM icon in the address bar) but not whole film. 

I previously believed that Amazon trailers required DRM because they do not play (without DRM) on FreeBSD. My bad. Apologies for any confusion.

**Comment by Clydefrosch22** [comment]
Just to clarify, I'm on windows 7, latest waterfox and my issue is not with DRM, but with amazon believing I'm not on a high enough version.

**Comment by Clydefrosch22** [comment]
Ok, scratch this. 
I didn't notice it before, since I always looked for config strings with amazon in them, but for some reason, i had 
general.useragent.override active too, and it was set to firefox/55.0 for some reason. I guess that one overrode the amazon-specific strings.

After setting all the overrides to
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

everything works now.

**Comment by grahamperrin** [comment]
Thanks!
