### ISSUE TITLE
v68: extensions.update.url and extensions.update.background.url are blank

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#948]
**Describe the bug**
Title says it all.  This causes Add-ons Manager to be unable to check for updates, and hang when attempting to do so.

Browser Console message -
```
NS_ERROR_ILLEGAL_VALUE: aUri must be a non-empty string AddonManager.jsm:1076
```

**To Reproduce**

new profile

1) Install any old version of an addon, e.g. Violentmonkey 2.10.3 https://addons.mozilla.org/firefox/addon/violentmonkey/versions/
2) Tools > Add-ons Manager, *either* click the gear > Check for updates, *or* click Violentmonkey > right-click > Find updates.

**Expected behavior**
It should check for updates and find the update for the addon.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04 64-bit
 - Waterfox 68.0a1

**Additional context**
Copying the values of these two prefs from Firefox does get it working.

**Comment by GitCurious** [comment]
Confirming the same behavior on Windows.

Copying the values of these two prefs from Firefox does get it working. +1

This is one reference to Mozilla I would suggest is better left functional.

**Comment by Peacock365** [comment]
Resolved by this pull request:

https://github.com/MrAlex94/Waterfox/pull/1157

Waiting for MrAlex94 to merge it.

**Comment by Peacock365** [comment]
@laniakea64 

Off-topic: We need to get rid of the "View Pocket List" entry in Library, both in the Library button and the Library entry in the hamburger menu. Pocket is disabled in Waterfox 68, it has no functionality anymore. Under _about:preferences#home_ there is also a "Pages saved to Pocket" entry under Highlights. I recommend locking the setting _browser.newtabpage.activity-strem.section.highlights.includePocket_ to _false_ and then removing the entry in _about:preferences#home_.

Furthermore, there are still the "Recommend extensions as you browse" and "Recommend features as you browse" entries under _about:preferences#general_, Browsing section. The related about:config settings are _browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons_ and _browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features_. I recommend locking the two settings to false and then removing the related entries in _about:preferences#general_.

Meddling with the UI exceeds my competence, which is why I am asking you. Hopefully you can help.

**Comment by laniakea64** [comment]
@Peacock365 Please do not go off-topic in my issues/pull requests.

> Furthermore, there are still the "Recommend extensions as you browse" and "Recommend features as you browse" entries under _about:preferences#general_, Browsing section. The related about:config settings are _browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons_ and _browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features_. 

https://github.com/MrAlex94/Waterfox/issues/1058

**Comment by Peacock365** [comment]
Uhm, @laniakea64, there is no contact form in GitHub (not that I am aware of), so I must mention it in an issue you were involved in if I want you to read it. Thanks for the downvote, much appreciated.

**Comment by laniakea64** [comment]
> I must mention it in an issue you were involved in if I want you to read it. 

No.  I get notification when someone mentions me by writing @laniakea64 .

> Thanks for the downvote, much appreciated.

You're welcome! :slightly_smiling_face:

**Comment by Peacock365** [comment]
I take it you are unwilling to actually resolve the issues I mentioned, and prefer bickering about off-topic / completely irrelevant questions?

**Comment by laniakea64** [comment]
> I take it you are unwilling to actually resolve the issues I mentioned, and prefer bickering about off-topic / completely irrelevant questions?

You take it that way even though I already filed an issue on one of the issues you mentioned, and suggested there that I might be able to do a pull request given more information?

Also, how is it "bickering" to inform you how to contact me without going off-topic?

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/waterfox/comments/bt55qf/waterfox_680a1_updating_addons/eoy5k1i/

>> … working on getting an AMO like system …
