### ISSUE TITLE
V68 DownThemAll! Add-In is not working ..

### ISSUE THREAD

**Issue by hansii99** [BrowserWorks/waterfox#952]
I installed the DownThemAll Add-In from https://github.com/MrAlex94/Waterfox/releases/download/68.0a1/DownThemAll.xpi in Waterfox V68.0a1.
Unfortunately the Add-In don't work:

- The DownThemAll! Selection Window can scan the Websites and shows links, but:
- A queued Download don't work to download the status is only starting ....
- The option Window is mostly blank, in input possible
- The Input Fields in the Selection for Download - Directory and the Filter are not visible, no input is possible

System: Window 10 V1903 18362.86

**Comment by jiangzhenjerry** [comment]
Same here. Thank you for confirming that it is not just me.

BTW I posted in [reddit](https://www.reddit.com/r/waterfox/comments/bmvy1x/is_downthemall_working_ok_for_everyone_on_68/). I believe it is the same syndrome as yours.

**Comment by unicorndreams** [comment]
For me, DownThemAll doesn't install correctly in v68.0a1, at all. On the customisation screen, none of its icons are available (DTA, OneClick, nothing...) On the context menu (right-click or context menu key), there are no DTA options. On "about:", there is no "about:downthemall". On the Tools menu, no DTA actions. The add-on appears as installed (with "LEGACY" label) on the Add-ons screen, but doesn't work at all.

**Comment by marty60** [comment]
Not working for me either.

This is xiaoxiaoflood'a project, might be a good idea to post there as well and let him know:

https://www.reddit.com/r/XUL_for_Quantum_Dev/comments/a9rzcz/legacy_addons_in_firefox_65/

**Comment by Ibuprophen** [comment]
The following is the Official DTA repo... 

https://github.com/downthemall/downthemall

... It looks like this Addon hasn't been updated in quite some time too. 


~Ibuprophen

**Comment by jiangzhenjerry** [comment]
@ibuprophen1 @unicorndreams 

Please don't be confused by the official DTA and xiaoxiaoflood's modification. The official DTA is not supposed to work on Waterfox 68 at all.

What we are talking about in this thread is mainly xiaoxiaoflood's modification, which aimed to revive DTA for later versions of Firefox/Waterfox. Unfortunately it still doesn't work, at least on Windows 10. Therefore, I agree with @marty60 that it will be better to contact xiaoxiaoflood.

**Comment by unicorndreams** [comment]
@jiangzhenjerry 
Ah, now I got it! So, that means old add-ons are destined to be dead, anyway. That's sad to know, because I still like some of them, DTA is just the most important, of course. Without it, I would have wasted hours or days of my life downloading thousands of files manually, instead of editing the links and importing them into DTA for automatic downloading.

Will the XUL structure be ditched? FireGestures is the best mouse gestures add-on. FoxyGestures is somewhat better implemented, but it has all the WebExtension limitations, like not working on special Pages (about:, blank tabs etc.) or while the Pages are still loading...

**Comment by grahamperrin** [comment]
> Will the XUL structure be ditched? 

Please see https://github.com/MrAlex94/Waterfox/wiki#waterfox-68-add-ons
