### ISSUE TITLE
v68 about:config search is broken compared to Waterfox 56

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#954]
**Describe the bug**
In Waterfox 68 the `about:config` search doesn't seem to search preference values.  Nor does it understand regex or wildcard searches.  This is regression compared to Waterfox 56.

**To Reproduce**
1) Go to `about:config`

2) Search for `mozilla.com`

3) Search for `/\d+\.com/`

4) Search for `moz*a`

**Expected behavior**
At (2) it should list all prefs where either name or value contains `mozilla.com`.
At (3) it should list all prefs where either name or value matches that regex.
At (4) it should list all prefs where either name or value matches that wildcard pattern.

**Actual behavior**
No results are listed for any of these searches.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04 64-bit
 - Waterfox 68.0a1

**Additional context**
Searching for e.g. `services.settings.` does give a result where value contains `mozilla.com`.  And searching for `1.com` does return a result.  So the searches in the steps-to-reproduce should definitely return more than zero results.

**Comment by Lorienna** [comment]
The issue appeared along with the new `about:config` page: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?changeset=cd4c2708c960b0db005a5e26a73417cb66dd16ee

---

<blockquote>
Actually, after looking at the ABOUT_CONFIG_FEATURES_USAGE probe, I don't think we need to implement the regular expression search any time soon. It's been used on 33 page loads, versus more than 7,260 for regular search, in the last week on Nightly, and exactly 1 time on Beta. Maybe favorites is something that might cover the only rare use case I can see of it, of showing multiple preferences for easy access without using multiple pinned tabs.
</blockquote>

https://bugzilla.mozilla.org/show_bug.cgi?id=1497725#c2

<blockquote>
Searching just the name seems fine to me. At the moment, the findbar can be used as well to look for specific values.
</blockquote>

https://bugzilla.mozilla.org/show_bug.cgi?id=1497725#c4

<blockquote>
In the new "about:config" page this can be achieved with the find-in-page functionality. Actual filtering based on anything else than the preference name would in fact make the code in bug 1501410 more complicated.
</blockquote>

https://bugzilla.mozilla.org/show_bug.cgi?id=1501658#c4

---

So at the moment, you can click on `Show All` in `about:config` > press <kbd>Ctrl</kbd><kbd>F</kbd> > perform a "normal" search on the page.

**Comment by WagnerGMD** [comment]
Hello,

according to [this page](https://www.waterfox.net/releases/), for the moment I believe it isn't yet available. That's why I will wait because I can't check neither download (or build) this version.

But I have one idea : try to open this page `chrome://global/content/config.xul` instead of `about:config`. Because as today, it's still exist even with the latest **Firefox Nightly** (v68 Alpha01).

Kind regards.

PS : Damn right, Mozilla has lost is mind with the new `about:config`... Because from my point of view, **it's a huge regression !**
Why the people didn't use the regex ? It's simple to explain : they don't know (even me until today) !

**Comment by laniakea64** [comment]
> I have one idea : try to open this page `chrome://global/content/config.xul` instead of `about:config`

Thanks @WagnerGMD , this page works well! :smiley: 

What in Waterfox is setting `about:config` to point to `chrome://browser/content/aboutconfig/aboutconfig.html` instead of `chrome://global/content/config.xul`?  I don't seem to be able to find the relevant code.

> for the moment I believe it isn't yet available. That's why I will wait because I can't check neither download (or build) this version.

You can download Waterfox 68 alpha from https://github.com/MrAlex94/Waterfox/releases or build yourself from https://github.com/MrAlex94/Waterfox/tree/gecko68

**Comment by MrAlex94** [comment]
It certainly looks slightly better but I think I’ll switch back to use the old config for now until it reaches feature parity.

Also [here](https://searchfox.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp#56) is where the redirect is handled. Should be a straightforward change!

**Comment by WagnerGMD** [comment]
```
Pref("browser.startup.homepage",'about:config');
// Each time you launch the browser, it will open the new about:config
Pref("browser.startup.homepage",'chrome://global/content/config.xul');
// At the contrary if you replace the value, it will open the older about:config
```

Great you're welcome @laniakea64 and for the moment, I see 2 solutions :
1) you can create a bookmark
2) or change this setting (when you need it, you just have to click on the button **House**)

Thank you for the link, I didn't check it because I excepted an announce (on the [Waterfox Blog](https://www.waterfox.net/blog/) etc).
Build myself ? Well perhaps one day I will have the time and the knowledge. **But at this moment, that's not the case...** And I didn't find a complete guide (for W10) and it's sound very hard.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/67d6d33ec6d331523a4d1b790265dcebc58a262c
