### ISSUE TITLE
armagadd-on 2.0: Mozilla's legacy hot-fix for Firefox 52 through 60: feedback from users of Waterfox 56.2.9

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#956]
### To users of Waterfox 56.2.9 whose profiles may be bitten by Mozilla armagadd-on 2.0

If your interest is in the forthcoming update to Waterfox: 

- please see #936

----

If you would like to add Mozilla's hot-fix to Waterfox 56.2.9: 

- please share your feedback in this issue

– please do **not** address Waterfox feedback to Mozilla. 

If you're new to Waterfox, it may help to know that historically, Waterfox 56.0 was based on Firefox 56.0.2. 

### Mozilla's hot-fix: a test routine for users of Waterfox 56.2.9

1. At `about:addons` (**Add-ons Manager**) please make a written note of the name of any extension that has a **red** alert (_… could not be verified for use in Waterfox and has been disabled_) – most users will find no such alert
2. in a new window or new tab, at https://addons.mozilla.org/extensions/ – the extensions area of AMO – please find, for yourself, an extension that will not download (a different **red** alert: ***Download failed. Please check your connection.***)
4. in a new window or new tab, visit https://bugzilla.mozilla.org/show_bug.cgi?id=1550793#module-attachments-title
5. click **Legacy hotfix for Firefox 52 through 60 (signed)**
6. when prompted to allow installation of software, click **Allow**
7. when prompted to allow installation of the add-on, click **Add**
8. after completion of the installation, click **OK**
9. bring to front the tab for the extension that could not be downloaded
10. **without reloading** the page, click the blue **+ Add to Firefox** button. 

For step (2) above, if you can not easily find an extension that is bugged by the download-specific red alert, try this one: 

- [Custom UserAgent String](https://addons.mozilla.org/addon/custom-user-agent-revived/)

**Comment by grahamperrin** [comment]
After following steps 1–9 above, please respond to this poll. 

Click **no more than once**:

[![](https://api.gh-polls.com/poll/01DAKD6JXC1XB87EF8EJNT0V7P/Yes%2C%20addition%20of%20Mozilla's%20extension%20resolved%20things%20for%20me)](https://api.gh-polls.com/poll/01DAKD6JXC1XB87EF8EJNT0V7P/Yes%2C%20addition%20of%20Mozilla's%20extension%20resolved%20things%20for%20me/vote)
[![](https://api.gh-polls.com/poll/01DAKD6JXC1XB87EF8EJNT0V7P/No%2C%20Mozilla's%20extension%20seemed%20to%20make%20no%20difference)](https://api.gh-polls.com/poll/01DAKD6JXC1XB87EF8EJNT0V7P/No%2C%20Mozilla's%20extension%20seemed%20to%20make%20no%20difference/vote)

(A second click will not reveal the identities of respondents. A second click will be misinterpreted as another vote.)

**Comment by grahamperrin** [comment]
To the anonymous person who found no difference after adding Mozilla's extension: can you describe your situation? 

If not here (maybe you have no GitHub account) then you might add a comment under https://redd.it/bnblfe

Thanks

**Comment by LeeBinder** [comment]
The extension approach ONLY works for Waterfox 56.2.9 Desktop, NOT for Waterfox 56.1.0 Android!

I have uploaded the certificate to my server with the correct MIME type and compiled a write-up how to import the certificate which works for both. You can find it [here](https://github.com/MrAlex94/Waterfox/issues/936#issuecomment-491090950).

**Comment by grahamperrin** [comment]
Mozilla bug [1551289 - publish armagadd-on 2.0 hotfixes on AMO for self-install - to versions 52-56](https://bugzilla.mozilla.org/show_bug.cgi?id=1551289)

> … ready to ship …

Thanks to those of you who tested and responded to the poll. 

All six of you! (I was two of the eight voters.)

**Comment by grahamperrin** [comment]
<strike>https://redd.it/boa46w</strike>

https://redd.it/boazxg

**Comment by LeeBinder** [comment]
@grahamperrin : https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-52-56/ **working in Waterfox Android 56.1.0** fresh virgin account: the add-on installs, is NOT and can NOT be enabled in Add-ons (even after WF force-quit and re-launch), but affected Add-ons DO nevertheless install. 

When force-quitting WF, remove cert9.db, re-launch WF, questionable Add-ons again do NOT install as before. Did some more tests [..] - in short, this hotfix WORKS even for WF Android. It installs the certificate then disables itself.

**NOT immediately working for Waterfox Desktop 56.2.9**: "_This add-on is not compatible with your version of Firefox_"  due to Waterfox pretending to be Firefox 57 on AMO in about:config?filter=general.useragent.override (credit to laniakea64 for the hint). It can however be downloaded manually, be dragged into about:addons and is even active. In a fresh virgin account, affected Add-ons DO then install.

**Comment by laniakea64** [comment]
> **NOT immediately working for Waterfox Desktop 56.2.9**: "_This add-on is not compatible with your version of Firefox_".

This is due to Waterfox pretending to be Firefox 57 on AMO, and this addon not being compatible with Firefox 57.  You could also right-click the greyed out "Add to Firefox" button > Copy link location, then right-click Waterfox address bar > Paste & Go.

> Change of useragent (tried many 51-66, Mac/ Windows/ Linux) does not change that.

What method were you using to change user-agent?  Changing the value of `about:config` > `general.useragent.override.addons.mozilla.org` to a Firefox 56 user-agent worked for me.

**Comment by LeeBinder** [comment]
oh, you are right! I was using User Agent Switcher and Manager v.0.2.8. In older versions it would overwrite settings in about:config?filter=general.useragent.override, but v.0.2.8 acknowledges them and treats them superior. Thanks for the correction! However keeping that setting on 57 UA would most likely mean a regression in regards to the # of extensions that can be installed (most of which seem to be working fine in WF even though Mozilla would like them to only work in Quantum versions of FF), so I will keep that setting on UA 56.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/56.0

**Comment by grahamperrin** [comment]
Please see https://www.reddit.com/r/waterfox/comments/boazxg/-/ene52ae/ – there's a direct link to Mozilla's extension.
