### ISSUE TITLE
Youtube Enhancer DeLazifies the browser (maybe needs a shim?)

### ISSUE THREAD

**Issue by Squall-Leonhart** [BrowserWorks/waterfox#962]
Install Youtube enhancer to do things like disable auto play of youtube videos
> https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/

Have waterfox set to multi process

Restart Waterfox

Load a Youtube video and start it

Result
All content processes up to the limit of the ipc value will be started.

Youtube HD breaks some game web pages recently, hence the change but did not cause this problem.

**Comment by grahamperrin** [comment]
I don't have the symptoms with 68.0a1 on Linux or 56.2.9 on FreeBSD-CURRENT, I played a few videos including https://youtu.be/as78wJIHGOs?t=187

![image](https://user-images.githubusercontent.com/192271/57578459-dc2db980-7484-11e9-937d-46be79e04ddf.png)

**Comment by Squall-Leonhart** [comment]
i've dropped it for Iridium, the enhancer addon seems to touch a whole lot of stuff in the window and leads to poor performance, excess memory use and this issue.

I'm also pretty sure the developer has bought reviews to get the extention to the top of the list.

**Comment by grahamperrin** [comment]
> … pretty sure the developer has bought reviews …

Its popularity is more likely the result of promotion by Mozilla. Re: https://blog.mozilla.org/addons/2016/12/01/decembers-featured-add-ons/ it was _Pick of the Month_ in December 2016. 

In October 2017, whilst using Firefox 56.0.1 – before I knew of Waterfox – I found a problem with (or involving) the extension. I wrote to the developer and received a quick reply but the problem was inexplicable, so I posted some details publicly – https://discourse.mozilla.org/t/-/20463?u=grahamperrin 

I never found the time to properly follow up on that topic but for what it's worth: in later months, on the rare occasions when I enabled the extension with Waterfox, symptoms were not (or not easily) reproducible.
