### ISSUE TITLE
List of differences between Waterfox and Alpha?

### ISSUE THREAD

**Issue by Henrietta1989** [BrowserWorks/waterfox#994]
It would be really nice if you would create page which lists accurately what are differences between latest Waterfox and latest alpha.

Then it would be easier to know when all the features you need is in alpha and you could start to use it more or even change it to your main browser.

**Comment by grahamperrin** [comment]
### Generally

Novelties in desktop Waterfox 68 – compared to desktop Waterfox Classic – will be something like a cumulation of these novelties in Firefox: 

- https://www.mozilla.org/firefox/57.0/releasenotes/#new (the first of the Firefox Quantum releases)
- https://www.mozilla.org/firefox/58.0/releasenotes/#new
- https://www.mozilla.org/firefox/59.0/releasenotes/#new
- https://www.mozilla.org/firefox/60.0/releasenotes/#new
- https://www.mozilla.org/firefox/61.0/releasenotes/#new
- https://www.mozilla.org/firefox/62.0/releasenotes/#new
- https://www.mozilla.org/firefox/63.0/releasenotes/#new
- https://www.mozilla.org/firefox/64.0/releasenotes/#new
- https://www.mozilla.org/firefox/65.0/releasenotes/#new
- https://www.mozilla.org/firefox/66.0/releasenotes/#new
- https://www.mozilla.org/firefox/67.0/releasenotes/#new
- https://www.mozilla.org/firefox/68.0beta/releasenotes/#new 

### Notable differences between desktop Firefox Quantum and desktop Waterfox 68

<https://www.mozilla.org/firefox/57.0/releasenotes/#note-787321>: 

> A revamped new tab page that includes top visited sites, recently visited pages, and recommendations from Pocket (in the US, Canada, and Germany)

Users of Waterfox might not benefit from the revamp. 

Features missing from the Waterfox home screen in the first alpha (68.0a1): 

- <strike>web search</strike> 
- [top sites](https://github.com/MrAlex94/Waterfox/issues/979)
- visited pages
- <strike>bookmarks</strike>
- most recent download
- pages saved to Pocket.

From <https://www.mozilla.org/firefox/57.0/releasenotes/#note-787319>:

> Firefox now exclusively supports extensions built using the WebExtension API, and unsupported legacy extensions will no longer work. …

As far as I can tell, Waterfox 68 will: 

- be compatible with extensions that use WebExtensions APIs
- have limited compatibility with a few non-adapted legacy extensions
- be compatible with legacy extensions that are adapted/ported as shown at https://github.com/MrAlex94/Waterfox/wiki

### System requirements for desktop Waterfox 68 

These will probably be the same as for Firefox Beta 68.0beta: 

- https://www.mozilla.org/firefox/68.0beta/system-requirements/

----

HTH

**Comment by Henrietta1989** [comment]
Thanks. How these two are different in privacy/security/phoning home?

**Comment by grahamperrin** [comment]
Good question. 

From the general overview at <https://www.waterfox.net/about/>: 

> no data or telemetry is sent back to Mozilla or the Waterfox project.

**Generally**: what's true for Waterfox Classic should be true for Waterfox 68. 

**Specifically**: I should expect a few logical exceptions to the _no data_ overview. Things such as:

- allowances for `versioncheck.addons.mozilla.org` and `versioncheck-bg.addons.mozilla.org` – these should be no surprise, because compatibility with Mozilla's add-ons service is [a feature](https://www.waterfox.net/addons/) (and re: https://redd.it/bt55qf maybe a Waterfox-provided add-ons service will become available, although I should not expect this with the first stable release of 68.0)
- allowance of `detectportal.firefox.com` for desktop Waterfox to function normally in [captive portal](https://wikipedia.org/wiki/Captive_portal) environments (… broad range of _mobile and pedestrian broadband services – including cable and commercially provided Wi-Fi and home hotspots_ … _enterprise or residential wired networks, such as apartment houses, hotel rooms, and business centres_ …)

– and other logical allowances that might be expected with a modern, full-featured fork of Firefox ESR for 'power users'. 

------

Re: your opening post, 

> It would be really nice if you would create page which lists accurately what are differences …

+1 to the wish for a detailed list (to complement an overview at <https://www.waterfox.net/about/>) however I don't imagine this level of detail for 68.0a1. 

Looking ahead: after 68.0a1 progresses to 68.0 alpha 2 (or a beta), it should be possible to view a GitHub-generated log of changes between the two versions. 

Like, https://github.com/MrAlex94/waterfox/compare/56.2.9...56.2.10 details the changes between two versions (56.2.9 and 56.2.10) of Waterfox Classic; we'll be able to see the changes between two versions of Waterfox 68.
