### ISSUE TITLE
Orientation for newcomers to Waterfox Current

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#999]
Newcomers who begin at https://www.waterfox.net/releases/ have no directions to pages such as <https://github.com/MrAlex94/Waterfox/wiki>. 

Two possible examples (there are others): 

- https://redd.it/btsrxq
- https://www.reddit.com/comments/butb8h/-/eplcn4c/?context=2

### Suggestions

1. add an anchor/ID e.g. <https://www.waterfox.net/releases/#alpha>
2. add a link from the alpha section of the downloads page, to the wiki. 

Use a phrase such as _Essential reading_ and make the link unmistakable, above the three download boxes. 

The Help menu in Waterfox 68 alpha should not lead to help for Mozilla Firefox. Instead, the **Waterfox Help** menu option should lead to the Waterfox wiki. (I know, there's a comparable enhancement request for Waterfox classic but for now, let's do this in as simple a way as possible in the code for Waterfox alpha.)

Add a little more to the wiki :-) FWIW I suggest a very concise home page, comprising links to pages with details. One such page might be _Useful links_ …

HTH; just suggestions. 

Meta: #582

**Comment by ilu33** [comment]
Important necessary information for testers: Will waterfox alpha steal the profile or will it use ~/.mozilla/waterfox? How to best go about a parallel install with waterfox classic?

Just in case anyone's interested: To be safe I added a new profile to ~/.waterfox/profiles.ini
[Profile2]
Name=W-alpha
IsRelative=0
Path=/home/youruser/yourpath/W-alpha

and started the browser with "/opt/waterfox68/waterfox %u -p W-alpha -no-remote"
- which actually did not work, due to bug #995

**Comment by grahamperrin** [comment]
> … Will waterfox alpha steal the profile …

Moving on from alpha, to beta: #1152

**Comment by grahamperrin** [comment]
### NPAPI

https://www.reddit.com/comments/bnihh4/-/enbdijs/?context=1 (2019-05-13): 

>>>> … 68 …

> Am actively working on keeping support.
